### ISSUE TITLE
Recovery options

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#1]
# What is this feature about? (1 sentence)
Users are able to choose recovery options including but also beyond backing up their mnemonic.

# Why is it needed? What is the value? For whom do we build it?
Account recovery beyond backup up private keys is one of the nice things about smart contract wallets. Fund recovery is still one of the biggest friction points when using crypto.

# High-level overview of the feature
- Users can choose between one or more recovery options.
  - Mnemonic, Hardware wallet (Keycard, Ledger)
  - More than 1 can be active, only 1 is required for recovery
- For each one, user can configure if recovery happens right away or if there is a timelock.
  - Safe can stop the timelock by making a transaction.

### Related links:
- https://github.com/gnosis/fund-recovery  <- outdated, but lists most important options.
- https://www.argent.xyz/ <- contract wallet, social recovery 
- https://airgap.it/ <- social recovery via Sharmir’s secret sharing
- https://docs.google.com/document/d/1-3CoPazVOomEU8AywDE9dn-FUqsMg7taA92SqXWV_CQ/edit  <- start of a recovery doc
- https://docs.google.com/document/d/1sUpR1SI5Dh8A2BRueHAiEs0odDBGz9UCwoFLxu_fRIc/edit <- really early overview of recovery options from beginning of the year
- HTC Exodus 1 phone - social recovery via Shamir’s secret sharing

**Comment by liliya-soroka** [comment]
test
