### ISSUE TITLE
Please rate app/extension popup

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#10]
**Background**
In order to get more traction, it's always important to get store ratings and reviews.

**Details**
* We could ask the user via a popup once to rate the app.
* We could add an entry to the sidebar to ask for a review / rating.
* Are they libs/SDKs that facilitate this?

**Comment by sche** [comment]
On iOS there is a native way to rate the app not leaving the app. We should specify a business logic on when and how often to suggest user to rate the app.

**Comment by tschubotz** [comment]
closing since this is now included in #82
