### ISSUE TITLE
Align create password flow

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#101]
iOS is using card-based designs now: #36

**Comment by biocom** [comment]
Created a proposal for Android to re-align with iOS more:

Policyhttps://invis.io/ARPG0XSTJMZ#/344183280_Startscreen_-_Conditions

Password:
https://invis.io/KSQ9VCSF26W
https://invis.io/NEQ9VD2FTAQ
https://invis.io/9VQ9VDD45AZ
https://invis.io/EXQ9VDLM2YB

Fingerprint:
https://invis.io/9UQ9VDNSEBT
https://invis.io/BCQ9VDU8Z5P

One of the differences with iOS is that on iOS we use the gradient/valley background for the passwords cards/view. On Android I specifically chose to not do this for these reasons:
- The valley background on Android has been exclusively used for the launch/unlock/start screen.
- In terms of were we use cards, it's seems to be mostly an in-app feeling (grey background etc.) and I feel we should keep it that way. From the iOS screens I've seen, the password cards are the only ones using the valley background.

After discussing with @posthnikova in her opinion:
> I think valley background is attractive and entertaining and it's distinguishable among competitors. It's in marketing materials and I would like to see more of it

Given we have different thoughts in terms of implementation on this, we'd like to get yours so we can decide what's the best way forward.

**Comment by biocom** [comment]
Also as @lukasschor pointed out, there are differences in wording between Android/iOS for the password flow:

Android:
> Your password is used to unlock the Safe and confirm transactions. 
> No more than 2 identical characters in a row

iOS:
> Your confidential password is used to unlock the Safe and confirm transactions. 
> No triple characters

As for the title, I shortened it so that it first on Android. As for the 2 characters/triple characters, is this an actual implementation difference? Let me know your thoughts.

**Comment by lukasschor** [comment]
I like the fact that the valley background is repeatedly used throughout the iOS app. Especially on the main wallet overview screen.

**Comment by tschubotz** [comment]
Here's my 2c concerning the valley background:
If I remember the insights from Minette's user testing, people felt there is a disconnection between the start screen (valley background)  and the create password flow (white background). That's why she started using the valley background throughout onboarding. I think this makes sense. 
If we agree on this, then we should also start using this approach on Android.

What do you think?

I'm against using different approaches on both clients.

**Comment by fmrsabino** [comment]
Made some small comments on invision. And I agree that we should align the usage of the valley brackground across both clients!

**Comment by biocom** [comment]
Based on the feedback you gave, I updated one screen as an example:
https://invis.io/ARPG0XSTJMZ

This screen should much more align with iOS. One question I have is if it's fine for us to put the back button at the bottom, where we have the stepper.

Once we approve this screen, I'll update the others.

**Comment by tschubotz** [comment]
This link opens the start screen for me. Di you intend to link this one instead? https://projects.invisionapp.com/share/ARPG0XSTJMZ#/screens/344172249

> put the back button at the bottom

Was it ever somewhere else on Android?

I think the position of the buttons could differ per client if there is a good reason. What's the reasoning to put it lower? Easier access with fingers/thumb?

**Comment by biocom** [comment]
@tschubotz Sorry, somehow I fail the 'share' feature today, heh. Indeed I meant the screen you referred to. 

Before the back button was in the status bar (on top). But I thought to bring it in the stepper at the bottom, allowing for pushing the card more up (creating more vertical space).

**Comment by tschubotz** [comment]
Ah, that's the difference, ok, didn't know. Then I think this makes sense. What do our Android power users @fmrsabino and @rmeissner think about this?

**Comment by biocom** [comment]
Please review screen https://invis.io/ARPG0XSTJMZ#/344172249_Choose_Password_I if we can move forward with this card style for the other passwords screens.

**Comment by posthnikova** [comment]
👍

**Comment by biocom** [comment]
Final review, as I also updated the fingerprint view with the valley background:
https://invis.io/P8QEC91AKJ2

Also from my understanding we don't show the 'fingerprint confirmed' view as we directly jump to the 'Create Safe' screen.

**Comment by tschubotz** [comment]
Looks good from my perspective. I would like to get @fmrsabino's and @rmeissner's view on not having a navigation bar.

Regarding 
> Also from my understanding we don't show the 'fingerprint confirmed' view as we directly jump to the 'Create Safe' screen.

Directly jumping also feels weird, no? Should we show some kind of success screen for ~1s and then automatically forward? I think that's what other apps do.

**Comment by rmeissner** [comment]
I would directly jump and show a toast (system toast)

for the cards and title it feels non-standard but I like it (if we show the background at least)

**Comment by fmrsabino** [comment]
Jumping directly with a toast can work well yes and removes one action that the user needs to perform.

I like the designs 👍

**Comment by biocom** [comment]
Thank you for your feedback and the toast sounds like a good solve. Added screens for production:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c5c5ea12d78a204fca15eb0

**Comment by tschubotz** [comment]
What should be written on this toast? Could you add a screen for this as well please?

@lukasschor @KristinaMayman This could be part of the UX testing of the onboarding this week, i.e. "Do users need a confirmation when enabling fingerprint/touch ID or not?"

**Comment by biocom** [comment]
Yes can add it. I'd say something like "Fingerprint confirmed!" or "Fingerprint confirmed successfully!"

**Comment by biocom** [comment]
Toast message example https://invis.io/P8QEC91AKJ2#/345790286_Setup_Fingerprint_-_Confirmed

I envision that you'd proceed to the next screen after the fingerprint is confirmed, but the toast message would persist for a moment?

**Comment by tschubotz** [comment]
> Toast message example https://invis.io/P8QEC91AKJ2#/345790286_Setup_Fingerprint_-_Confirmed

👍 

> I envision that you'd proceed to the next screen after the fingerprint is confirmed, but the toast message would persist for a moment?

Yea I think so.

**Comment by fmrsabino** [comment]
> I envision that you'd proceed to the next screen after the fingerprint is confirmed, but the toast message would persist for a moment?

Yes. It persists across screens.

**Comment by posthnikova** [comment]
I don't have comments 👍

**Comment by tschubotz** [comment]
Maybe needs wording changes after #119

**Comment by tschubotz** [comment]
merging this with the iOS ticket #36

**Comment by biocom** [comment]
Updated screens are on production https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c5c5ea12d78a204fca15eb0
