### ISSUE TITLE
Align create Safe flow

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#104]
- iOS is proposing a card layout: #48.
- Android should be aligned.

**Comment by biocom** [comment]
@posthnikova For iOS I saw this screen:
https://zpl.io/2vKXr3Q

We seem to use the title *Safe is secured. Password setup complete.*

On Android we currently have:
*Device setup succesful!*

I'm not sure if 'Safe is secured' confuses the user into thinking they already setup a Safe? While what we man is that the device itself has been setup (and now you can create a Safe).

**Comment by biocom** [comment]
Created a proposal to both re-align the Android/iOS and start using cards where applicable:

https://invis.io/KYQ9SN9BEMG
https://invis.io/KGQ9SNFHEWX
https://invis.io/3CQ9SNP7AU4
https://invis.io/UQQ9SNT7WAM
https://invis.io/UZQ9SNYGDRW
https://invis.io/38Q9SO32EDQ

The only screen missing is the actual recovery phrase display/input, as we discuss to leave those untouched.

**Comment by tschubotz** [comment]
I commented a bit on Invision 💬 
iOS and Android are still quite different here.

**Comment by posthnikova** [comment]
I also noticed it differs from iOS. Looks rather like a totally new version than realigning. Also iOS is not using card layout everywhere, only in special cases.

> I'm not sure if 'Safe is secured' confuses the user into thinking they already setup a Safe? 
> While what we man is that the device itself has been setup (and now you can create a Safe).

I agree that Safe is secured isn't the right wording. Maybe "Device setup successful. Password is created"?

**Comment by tschubotz** [comment]
> Device setup successful. Password is created.

Agree, sounds better. Instead of "Password is created" we could also say "Password is set"

**Comment by biocom** [comment]
Please review the updated Android screens:
https://invis.io/RZQDYUJWHYC

**Comment by posthnikova** [comment]
This screen might be affected by yesterday's user tests: https://invis.io/ARPG0XSTJMZ#/343633719_New_Safe_-_Deposit_Received. See discussion here: https://invis.io/QRQ97T1NBES#/343967918_05_Connecting_In_Progress_

Other than that I don't have any comments :+1:

**Comment by biocom** [comment]
Thank you @posthnikova . Could you elaborate on how it might be affected?

**Comment by tschubotz** [comment]
- For Safe creation: Progress bar is needed. The Safe does not exist, so showing the Safe overview doesn't make sense yet.
- For other txs like "Connect extension": Not progress bar needed since we can lead the user to the transaction list already. (Potentially via an intermediate success screen)

**Comment by biocom** [comment]
Added screens to production:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c504b5b505721bf1335da4c

zpl://project?seid=5c504b5b505721bf1335da4c&pid=5af063c9b4dc859b6bdaf897

**Comment by tschubotz** [comment]
@biocom @posthnikova During specs writing I noticed the following missing screens/inconsistencies:

(1) 
- On iOS tapping "link to the Chrome browser extension" opens the iOS share sheet: https://zpl.io/agzEOWO
- On Android, tapping the link just copies it to the clipboard: https://zpl.io/VOP3pYk
- We need to align it. I'm in favor of the iOS version since it allows for greater flexibility including copying. @biocom could you please adapt?
- @posthnikova could you please add the word "the", i.e. "link to **the** Chrome browser extension"?

(2)
- The wording on the recovery phrase guidelines screen is different: [Android](https://zpl.io/b6y0jxP), [iOS](https://zpl.io/VOP3pP1)
- I'm in favor of the Android version. @posthnikova could you please adapt?

(3)
- The correctness of the confirmed recovery phrase is only checked after all words are filled on the user hits "submit", hence on https://zpl.io/bzN7ke8 all words need to be filled in. The wrong ones will be marked with the red outline.
- @posthnikova could you please adapt the screen so all 4 words are filled but 2 are marked with red?
- @biocom could you please create the same screen for Android? I wasn't able to find it.

(4)
- After the user tapped the address on the deposit screen, we show a small popup "copied" on iOS: https://zpl.io/2Gy3Rwd
- @biocom could you please create a similar screen? I think we used toasts on Android for this.

(5)
- When the user hits "share", we open the share sheet of the operating system: https://zpl.io/aNP35Q9
- For completeness reasons, @biocom could you please create that screen for Android?

(6)
- To explain the Safe opening fee, we have this popup: https://zpl.io/2ZLAmE4
- @biocom could you please create this screen for Android?

(7)
- Wording on the progress screen differs: [iOS](https://zpl.io/2Gy3RZ9), [Android](https://zpl.io/aMmE6NN)
- I prefer Android since it's a bit more concise.
- @posthnikova could you please adapt the wording for iOS?

**Comment by biocom** [comment]
Here some comments:
1) Added a screen for this https://zpl.io/a3eGRB8
The only comment I have here, is that perhaps the text "Copy the Link to the Chrome browser extension to your desktop computer." isn't very accurately describing the fact that it opens the (native) share dialog? Perhaps we could focus on the goal, e.g.: "Visit the link to the Chrome browser extension on your desktop computer."

3) Added -> https://zpl.io/2v7QPJv and https://zpl.io/agz7wYN 
4) Added -> https://zpl.io/bLPXG9m
5) Added -> https://zpl.io/VqWr54N
6) Added -> https://zpl.io/aR1A0jN

**Comment by posthnikova** [comment]
1) corrected https://zpl.io/VqWMkWY

2) corrected https://zpl.io/VOP3pP1

3) added https://zpl.io/aw4j4r1, also see in action on Invision: https://invis.io/FXPSG91SV8B#/354871087_06_Confirm_Recovery_Phrase_Empty_

7) corrected https://zpl.io/2Gy3RZ9

**Comment by tschubotz** [comment]
Ux sync: Yes, let's change the wording to "Open the link to the Chrome browser extension on your desktop computer."

**Comment by biocom** [comment]
> Ux sync: Yes, let's change the wording to "Open the link to the Chrome browser extension on your desktop computer."
Updated for the existing Zeplin screens. 

@posthnikova I checked the iOS screen https://zpl.io/VqWMkWY and I think the primary action here would be to scan a QR code. On Android we have https://zpl.io/V18Bzpm

Are we missing a button for that? As NEXT in the right corner right now brings you to the recovery phrase step?

**Comment by posthnikova** [comment]
> Are we missing a button for that? As NEXT in the right corner right now brings you to the 
> recovery phrase step?

The button should be "Scan", not "Next". Updated this.

I corrected the wording on browser extension screen: https://zpl.io/VqWMkWY

Also updated this text in:
Connect browser extension flow:
Connect browser extension https://zpl.io/bWqXJAK
Insufficient funds https://zpl.io/a3e98X8

Recover Safe flow:
Pair with browser extension https://zpl.io/2v701K7

@biocom Could you please update too https://zpl.io/VkGeXvG, https://zpl.io/aw4O6eJ, https://zpl.io/VDBK9Wq

**Comment by biocom** [comment]
@posthnikova Updated them, thank you for pointing out. 

I wonder if we should change the text here too:
iOS: https://zpl.io/bzNDgl4
Android: https://zpl.io/aRqRQJN

So that we could use a single string everywhere ("Open the link to the Chrome browser extension on your desktop computer.")

**Comment by posthnikova** [comment]
> I wonder if we should change the text here too

I think this https://zpl.io/bzNDgl4 is the different case. In this case the browser extension is already installed and we are telling to open it.

**Comment by biocom** [comment]
> I think this https://zpl.io/bzNDgl4 is the different case. In this case the browser extension is already installed and we are telling to open it.

Should we in that case remove the hyperlink/action? Because what was our intention right now on tap of 'Safe browser extension' ?

I could see a case where an user wants to replace the browser extension but hasn't the (new) extension installed yet. I think in that case we should catch that case already in the first screen (https://zpl.io/VDBYyxq).

Let me know your thoughts.

**Comment by posthnikova** [comment]
To replace browser extension I assume the user has installed it at least once and already knows how to install it. What we currently don't say here is that it has to be a new browser extension. Maybe say "Open the NEW browser extension" or "Make sure you have the new browser extension installed". The link could stay in case the user doesn't have it.

**Comment by biocom** [comment]
In that case, I'd write it like this:

1. Open the *new* Safe browser extension in Google Chrome on your desktop computer or [open this link](https://safe.gnosis.io/) to download and install first.

**Comment by biocom** [comment]
@tschubotz @posthnikova Let me know if we want to go for the text string I mentioned above.

**Comment by tschubotz** [comment]
I would not put in specific wording for replacing the browser extension. Was this a problem during user tests? Or did we ever test this? 

I incorporated the new screens into the spec, thanks! See the overview here: https://github.com/gnosis/safe/blob/ccf828da723ca3e261926ae45d98719f4c40eb56/specs/create_safe/02_user_interface.rst

There is still one difference:
- https://zpl.io/aR1A0jN vs.https://zpl.io/2ZLAmE4
- "Safe opening fee" was a problem during user tests, right? I would then opt for "network fee" again. Let's discuss in the sync later.

**Comment by tschubotz** [comment]
UX sync:
- Link should go directly to Chrome web store
- No need for adding "new" right now.
- Let's use "Safe creation fee" (based on user testing insights)

**Comment by biocom** [comment]
Updated to 'Safe creation fee' on Android -> https://zpl.io/aR1A0jN

I think when @posthnikova updates iOS we can close this ticket.

**Comment by posthnikova** [comment]
iOS updated: zpl.io/2ZLAmE4
