### ISSUE TITLE
When to use cards and where?

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#106]
Let's think about this again.

Outcome: Please create a doc with an overview when to use cards and when not.

**Comment by posthnikova** [comment]
Please review here: https://docs.google.com/presentation/d/1OCRKooWamDFP2qEZB95oEpqvOknugP4cjm950JLSjR4/edit#slide=id.g4deaf73c3a_2_55

**Comment by posthnikova** [comment]
Updated version: https://docs.google.com/presentation/d/1OCRKooWamDFP2qEZB95oEpqvOknugP4cjm950JLSjR4/edit#slide=id.g4e06b795a6_5_49
