### ISSUE TITLE
UX test review transactions screen

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#108]
Do user test with the screen where the user reviews their tx and wait for confirmation from browser extension.

**Comment by posthnikova** [comment]
I tried to implement some ideas from testing (https://docs.google.com/document/d/1NaeoGESLLaq61B9Osmag2vU3Yq6dUC93lg2f0MQJAy4/edit). 

- When pressing on a shortened address/amount, a tooltip appears with the full amount. 
Address: https://invis.io/FBPH0OFQ57P#/344732445_21_Send-ETH_Tooltip_
Amount: https://invis.io/FBPH0OFQ57P#/344732461_22_Send-ETH-Filled_Tooltip_

- Change Next to To Review: https://invis.io/FBPH0OFQ57P#/344732445_21_Send-ETH_Tooltip_

- Animation on Review screen

![send_animation.gif](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/7eb0923d-d22e-413b-adee-17f0ab7fd201)

- Wording in browser extension

- Address book (#112)

- Add another confirmation screen or pop up: https://invis.io/FBPH0OFQ57P#/344732516_23_Connecting_In_Progress_Copy_. This screen could be the same for all types of transactions, only wording and icon would change. From here you can go to tx list, tx details, etherscan. For Create Safe and Recover Safe the same screen could lead to Assets overview & etherscan

When the user goes from there to transaction list for the first time, I propose to point them to the latest transaction details: https://invis.io/FBPH0OFQ57P#/344732516_23_Connecting_In_Progress_Copy_

**Comment by tschubotz** [comment]
> When pressing on a shortened address/amount, a tooltip appears with the full amount.

I like the tool tip.

> Change Next to To Review: https://invis.io/FBPH0OFQ57P#/344732445_21_Send-ETH_Tooltip_

Why not just "Review"?

> Animation on Review screen

The last time we had an animation on that screen, people thought that they have to wait since something is "processing". Could we try this prototype with testers?

I like Lukas comment in that regard. Using a more active voice could help!

> Add another confirmation screen

I like it.
