### ISSUE TITLE
Hardware wallet integration

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#11]
**Story**
As a user I am able to use my hardware wallet with the Gnosis Safe so I get more security.

**Details**
- How should this look in details?
  - Would this be another owner?
  - Would this be instead of the recovery phrase?
  - How would they connect to the mobile phone?
  - Can we leverage Metamask's integration for this?
- Which hardware wallets? Trezor, Ledger, Status?

**Comment by felixmacht** [comment]
Multi-sig with, signed with hardware wallets would be awesome

**Comment by tschubotz** [comment]
Hardware wallet integration will be dealt with in #77
