### ISSUE TITLE
Pushing wallets to the users

### ISSUE THREAD

**Issue by miohtama** [gnosis/safe#110]
We want to non-cryptocurrency people to adopt using our product and for this reason they need to install a wallet. Our product runs on a public blockchain and is not related to cryptocurrencies.

- How can we push wallets to the users through their web browser

- How can we pay the initialisation fee - these people are unlikely to never hold/use any ETH

**Comment by tschubotz** [comment]
Hi @miohtama,

> Our product runs on a public blockchain and is not related to cryptocurrencies.

Which public blockchain are you using? The Gnosis Safe is running on Ethereum only. 
Also, could you please provide more details about your product and the use case you have in mind? This would help us thinking about it.

> How can we push wallets to the users through their web browser

The Gnosis Safe is currently only available for mobile devices in connection with a browser extension. The only way I can currently think of, is that you provide a download link for your users. Alternatively you would have to write a JS wrapper or something for the [Safe smart contracts](https://github.com/gnosis/safe-contracts).

> How can we pay the initialisation fee - these people are unlikely to never hold/use any ETH

I assume you would be also paying fees for all future transactions of your users? 
We don't have a solution for this scenario, yet. One approach would be that you have some kind of balance on our relay service from which the tx fees would be deducted. But there is no specific plan, yet.
