### ISSUE TITLE
Address book screen

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#112]
This includes
- Address book list (with entries and empty state)
- Search
- Adding an entry
- Viewing an entry
- Editing an entry
- How "using address book entries" would look like in the Send flow and on the tx details screen.
More?

**Comment by posthnikova** [comment]
Project is up for review here: https://invis.io/GPQCMX8E4HA (interactive)

There are more states than I expected :)

**Comment by tschubotz** [comment]
Really nice and extensive prototype 👍 
I added some comments on Invision 💬

**Comment by biocom** [comment]
As for re-aligning Android too and given the recent updates, I created some proposals for Android here:
https://invis.io/UEQFLI9WAQ8

**Comment by tschubotz** [comment]
Thanks for adapting Android @biocom. I added some comments to the invision 💬

**Comment by biocom** [comment]
Updated screens on InVision and replied to comments. I see two questions pending:
- New address: Should we call it 'New entry' as per @rmeissner 's comment?
- Should we allow to change a contact/entry's address ? (https://invis.io/UEQFLI9WAQ8#/345954373_Addressbook_-_Detail_-_New_IV)

**Comment by tschubotz** [comment]
> * New address: Should we call it 'New entry' as per @rmeissner 's comment?

"New address" sounds fine to me. Why would we call it "New entry" instead?

> * Should we allow to change a contact/entry's address ? (https://invis.io/UEQFLI9WAQ8#/345954373_Addressbook_-_Detail_-_New_IV)

Yes I think we should allow it. Why wouldn't we?

**Comment by tschubotz** [comment]
About the address details view:

**Comment by biocom** [comment]
Updated the Android screens - https://invis.io/UEQFLI9WAQ8

**Comment by posthnikova** [comment]
I replied to everyone and made changes to iOS: https://invis.io/GPQCMX8E4HA

**Comment by biocom** [comment]
@posthnikova I added two screens as an example for address options in a transaction detail view:
https://invis.io/N3QIEAYH9JB#/346792488_Transaction_Receipt_-_Outgoing
https://invis.io/N3QIEAYH9JB#/346873286_Transaction_Receipt_-_Outgoing_-Add_Address-

In my view the 3 dots after the address, work best when they are right aligned. In my opinion the 3 dots action icon conflicts with the trimmed address (also uses 3 dots...).

Let me know your thoughts.

**Comment by posthnikova** [comment]
> In my view the 3 dots after the address, work best when they are right aligned. In my opinion
> the 3 dots action icon conflicts with the trimmed address (also uses 3 dots...).

@biocom I still think right aligned dots are closer to ETH than to the address

**Comment by biocom** [comment]
I think the most screens are re-aligned. There's only one element, which is the 3 dots action on the recipient address: In my opinion this should be right aligned, and in Sasha's opinion this should be part of the address:

<img width="200" alt="screen shot 2019-02-19 at 16 05 45" src="https://user-images.githubusercontent.com/31534717/53025209-c9e14800-3460-11e9-90ec-aaf7a7e40655.png">
<img width="200" alt="screen shot 2019-02-19 at 16 05 39" src="https://user-images.githubusercontent.com/31534717/53025210-c9e14800-3460-11e9-86e1-780af913fcf7.png">

In my opinion, given the address is already abbreviated with 3 dots, it think it's not so clear/consistent to have it there. 

Let me know your thoughts so we can re-align and close the ticket.

**Comment by lukasschor** [comment]
I agree that it can look a bit confusing having it right next to the address. So either use something different than three dots or have it right-aligned. But also agree with Sasha that when it's right-aligned it doesn't look as connected to the address anymore.

**Comment by KristinaMayman** [comment]
I find both options a bit confusing but the right-aligned version looks cleaner to me.

**Comment by tschubotz** [comment]
> I find both options a bit confusing but the right-aligned version looks cleaner to me.

Agree with that. However, the right-aligned version doesn't have the visual connection to the address anymore. Know what I mean? 

Also, some smaller inconsistencies are still there:
- "Enter address" (iOS) vs "Input address" (Android)
- "Entry details" (Android) vs. "View entry" (iOS). I thought we go with the later since we also have "New entry" and "Edit entry"

**Comment by biocom** [comment]
Updated wording differences on Android: https://invis.io/UEQFLI9WAQ8
Let's discuss the 3 dots during UX weekly.

**Comment by tschubotz** [comment]
Idea:
Instead of 3 dots, we could also put 2 explicit buttons.
- Might be a problem if there are more actions.
Let's design for right now and use 2 buttons.

**Comment by tschubotz** [comment]
iOS search: Let's use a similar search like we do for managing tokens.

**Comment by biocom** [comment]
Sasha and I discussed some drafts and ended up with this proposal:
<img width="763" alt="screen shot 2019-02-21 at 18 09 56" src="https://user-images.githubusercontent.com/31534717/53187700-fda8a300-3603-11e9-8b60-9d06b7bb0194.png">

Let me know your thoughts.

**Comment by KristinaMayman** [comment]
I think "Add address" makes sense, but editing anything after the transaction has already gone through sounds a bit confusing. 

Also, is there a reason the "Resend" button is for ETH specifically? Would it not be possible to change the currency for a second transaction?

**Comment by biocom** [comment]
@KristinaMayman 
- I tend to agree that, all things considered, 'Edit Address' should probably exclusively be part of the Addressbook. Alternatively what we could do, for addresses already in addressbook shown in the transaction detail screen, that on tap it would open the '(Address) Entry View'.

- I think given our existing flow, where you always pick the token first before sending (Assets overview) the choice was made to restrict it to ETH. That being said, I'd be much more in favour to keep it more open ended like 'Resend Funds' and where in the next screen you pick the token you'd like to use for (re)sending. Question is, if we want/can implement it like that at this stage.

**Comment by tschubotz** [comment]
I also prefer "Add address" over "Edit address". It's not 100% ideal though. Just looking at the screen, it could also mean that you add an address to the tx, which obviously wouldn't work. So what you actually could do is "Add address to address book" or essentially "Save address". 

If an address is already in the address book, the "Resend" button would slide to the left?

I see your point @biocom about "Resend funds". If we call it "Resend funds" we would have to have the user select which funds to send. Let's not do that at this point, but rather keep "Resend ETH" whcih would open that Send funds page with the address and same amount preselected. (similar for tokens)

**Comment by biocom** [comment]
@tschubotz Also to your first comment:
- 'Edit Address' was meant as a separate action from 'Add address'. Shown for addresses already present in the address book (I know the mockup doesn't reflect that well, my apologies). See my previous comment on why we perhaps should leave that out.

> If an address is already in the address book, the "Resend" button would slide to the left?
Yes. Assuming we don't go for 'Edit Address'.

> I see your point @biocom about "Resend funds". If we call it "Resend funds" we would have to have the user select which funds to send. Let's not do that at this point, but rather keep "Resend ETH" whcih would open that Send funds page with the address and same amount preselected. (similar for tokens)
Opening the Send Funds page with the same address makes sense. Using the same amount I don't see being ideal for several reasons. 

I'd rather let it up to the user to input the amount again. I think a scenario where the user would like to send any other amount outweighs a scenario where user wants to send the exact same amount (which in case the user would have to manually remove the amount to enter their own amount..)

**Comment by tschubotz** [comment]
> * 'Edit Address' was meant as a separate action from 'Add address'.

Ah ok. I think that's not the screen where a user should have access to editing the address. 

> I'd rather let it up to the user to input the amount again.

Also fine with me, no strong preference here.

**Comment by KristinaMayman** [comment]
> Ah ok. I think that's not the screen where a user should have access to editing the address.

Yes, but "View in Address Book" or something like that could work.

**Comment by biocom** [comment]
> Ah ok. I think that's not the screen where a user should have access to editing the address.
> Yes, but "View in Address Book" or something like that could work.

What if on tap of the recipient name (address) we either:
- Directly open the 'View entry' view.
- Or show bottom action sheets. Although, might as well then have the 'Resend...' action in there, heh.

**Comment by posthnikova** [comment]
New version with system search and buttons on transaction details screen: https://invis.io/GPQCMX8E4HA

I'm for leaving out "Edit address" action in case the address is already in address book. I think it's a rare case

**Comment by biocom** [comment]
@tschubotz One use case were on tap of 'Resend ETH' it would make sense to use the same amount, is when a transaction failed. You think we could create an exception there?

**Comment by biocom** [comment]
Updated the Android mockups https://invis.io/N3QIEAYH9JB

**Comment by rmeissner** [comment]
Could you share why the 2 buttons instead of a longpress/ 3 dots? 

Also how would this look for incoming transactions (where the "unknown" address is on the top")

**Comment by biocom** [comment]
> Could you share why the 2 buttons instead of a longpress/ 3 dots?

I think the consensus was that the 3 dots weren't clear enough to convey actions in relation to the address. Therefore we discussed to do it with explicit buttons.

> I think the consensus was that the 3 dots weren't clear enough to convey actions in relation to the address. Therefore we discussed to do it with explicit buttons.

Yes, will prepare such screen.

**Comment by biocom** [comment]
![Uploading Screen Shot 2019-02-22 at 12.38.53.png…]()

I think the only sensible way for having the 'Add address' for addresses on top, is to have it right aligned. I just don't like that it's not consistent in terms of location with the other screens. Which could be a good case for having it as a bottom sheet action instead. It then would be triggered by simply tapping on the address. 

We could have a tooltip/hint (you can click away) the first time the user lands on the transaction details screen, explaining that they can tap on addresses to see more actions.

**Comment by rmeissner** [comment]
Personally I prefer the 3 dots (this is a common pattern), I can see that it is far away from the address, but to be honest I feel it would even work with out the 3 dots ... but that might be very specific to my behaviour in the app

**Comment by biocom** [comment]
> Personally I prefer the 3 dots (this is a common pattern), I can see that it is far away from the address, but to be honest I feel it would even work with out the 3 dots ... but that might be very specific to my behaviour in the app

I agree. Both would work for me too. Though during the last UX weekly/review it was concluded to use explicit buttons. After reviewing the incoming transaction screen, I realize it's a bit of a messy implementation. We overlooked the consistency aspect of the incoming transfer screen.

With that knowledge know, I'd vote for having a bottom sheet on tap. With or without the 3 dots.

**Comment by lukasschor** [comment]
I like the idea of having a tooltip/hint, it allows for simple design while still making it easy for the user to understand. 

How about, we try the three dots approach with a hint during the first open? 

Also, I have mentioned this before, but I think here it could be very usefull to have the three dots in a circle to make it look more like a button and have less confusion with the three dots in the address. Something like this: https://previews.123rf.com/images/solargaria/solargaria1706/solargaria170600053/80110051-chat-sign-three-dots-icon-icon-iconic-symbol-inside-a-circle-on-transparency-grid-vector-iconic-desi.jpg

Of course, this is not in line with the three dots we have for adding an address in the Send flow, but one could argue that it's a different situation here as the three dots are not in an input field but stand on their own.

**Comment by rmeissner** [comment]
We can also try the vertical buttons, maybe that helps some how 🤔 

But yeah, I do agree to test it with a tooltip (with or without 3 dots)

**Comment by posthnikova** [comment]
I made a tooltip which shows when you view transaction details for the first time. This is a version with 3 dots: https://invis.io/GPQCMX8E4HA#/348699636_25_TxView_Tooltip_

There is also a version with vertical dots: https://invis.io/GPQCMX8E4HA#/348699673_28_TxView_Tooltip_Vertical_Dots_

And dots in a circle: https://invis.io/GPQCMX8E4HA#/348699699_29_TxView_Tooltip_Circle_

We also have tooltip with full address: https://invis.io/GPQCMX8E4HA#/348699667_27_TxView_Copy_Tooltip_Address_

**Comment by biocom** [comment]
Thank you @posthnikova 

Personally I find the vertical dots and the dots with the circle, by comparison with what we have/use on Android, being an anomaly.

All options considered, I think the one time tooltip is definitely helpful. With or without dots.

**Comment by posthnikova** [comment]
I would go with 3 dots because we also have tooltip with full address both for the sender and recipient.

**Comment by rmeissner** [comment]
For me the vertical dots are normal (you have them in a lot of places on Android), but I still feel having them right aligned looks better

**Comment by tschubotz** [comment]
- circle looks too much like a button
- Vertical dots looks too Android-y (i.e. not applicable for iOS)
Vote:
- Lukas: close to address because of connection to it.
- Tobi: same
- Kristina: prefer right aligned
- Sasha : close to address
- Michel: right aligned
-> Let's go with 3 dots close to address with tooltip.

**Comment by posthnikova** [comment]
Zeplin is here:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c757cb52e478f51fffeba97

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c757cb52e478f51fffeba97

**Comment by biocom** [comment]
@posthnikova We also need a screen for an incoming transaction. Both for a known (address book) and unkown address.

**Comment by biocom** [comment]
Android production screens:

Address book:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c76558485e8aabc48c8df90

Transactions (which includes related actions)
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5af0659352d29dbf244f76e4

**Comment by posthnikova** [comment]
Missing screens for incoming transactions:

https://invis.io/GPQCMX8E4HA#/349232416_28_TxView_Incoming_

https://invis.io/GPQCMX8E4HA#/349232421_29_TxView_Incoming_With_Address_

**Comment by biocom** [comment]
Looks fine with me. Close this ticket?

**Comment by tschubotz** [comment]
Looks fine to me as well at this point. As soon as the iOS screen are on Zeplin, we can close the ticket. I'll start writing the spec then and will let you if I encounter problems :)

**Comment by posthnikova** [comment]
Zeplin for ios is here:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c757cb52e478f51fffeba97

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c757cb52e478f51fffeba97

**Comment by tschubotz** [comment]
@biocom @posthnikova could you please add a screen for when the user enters an invalid address or name on the ["new entry" screen](https://zpl.io/29OwjnB)?

- For the address I imagine something like "Invalid address" (Same like during the send flow)
- For the name, users can use any character, but we should just limit the length (it's bad security practice to not limit the length of input fields. I would set the length so 200 (can be any number). So the error should say "Name too long" in red.

- Also, should we disable the "Done" button as long as the input is invalid or the user hasn't put in something into name or address?

**Comment by tschubotz** [comment]
4. How does the address book list look like if there are no entries, yet

**Comment by tschubotz** [comment]
The Android "View entry" screens still has the 3 dots (https://zpl.io/2vlDlmn)
We just put "Delete entry" there, right? We decided to put that on the "Edit Entry" screen. -> Please remove the 3 dots.

**Comment by tschubotz** [comment]
The edit entry screen needs a delete button: https://zpl.io/a8ZDyyx
The 3 dots can be removed.

**Comment by tschubotz** [comment]
Android puts "Edit entry" on the tx detail action sheeet. iOS doesn't https://zpl.io/br8vpW5

**Comment by biocom** [comment]
Updated for Android: https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c76558485e8aabc48c8df90

**Comment by posthnikova** [comment]
Error screen: https://invis.io/GPQCMX8E4HA#/349334887_28_Address_Errors_

When there are no entries: https://invis.io/GPQCMX8E4HA#/349336848_31_Address_Book_No_Entries_

Tx details action sheet with known address: https://invis.io/GPQCMX8E4HA#/348799790_24_TxView_With_Address_Action_Sheet

Zeplin updated as well:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c757cb52e478f51fffeba97

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c757cb52e478f51fffeba97

**Comment by biocom** [comment]
Looks to be all aligned. One minor note is the error validation text for 'Name too long":
Android: https://zpl.io/VkGX6JW
iOS: https://zpl.io/25OpBkW

Even though we don't know what limit we'd apply, I think it's worth it to indicate how long is 'long'. In other words, the users then knows the max. amount of characters they can type. Which then I wonder if we'd need a character counter, which looks like a better validator:
https://i.imgur.com/eEYwIO3.png

**Comment by posthnikova** [comment]
It is unlikely that someone would want to input 200 characters, it's not a text area field.

**Comment by biocom** [comment]
While unlikely, from my understanding we limit the amount of characters for input. If we show an error 'Name too long' it's not informing the user what the actual limit is. So I would suggest:
- We will have a limit in amount of characters for the name.
- But we don't inform the user a name is too long, but just cap it off after say 200 characters.

Otherwise, if we do wan't the 'Name too long' error, I'd at least inform them how many characters they used. But I agree that, that probably that is overkill for a name input field.

**Comment by lukasschor** [comment]
As this is an edge case, I would just not allow to add new characters as soon as the limit is reached / cut off the input if it‘s copy-pasted.

**Comment by tschubotz** [comment]
Thanks for the updates. Usually we show an error. It's an easy thing to just display this error. The code is anyway there. I guess we can make it explicit and say "Too long, max x chars". 

Besides the aligned error screens, I'm missing the following screens for Android:
- Popup to confirm delete: https://zpl.io/agzQW3D 
- Transaction details action sheet when address is in address book - https://zpl.io/bzNNGk7
- Send funds screen with address book entry filled - https://zpl.io/aR1xX4g
- Screen above with an action sheet - https://zpl.io/bzNqL3l

**Comment by biocom** [comment]
Android screens:

- Popup to confirm delete: https://zpl.io/VqWnDMm
- Transaction details action sheet when address is in address book: https://zpl.io/br8vpW5
- Send funds screen with address book entry filled: https://zpl.io/bAZR888
- Screen above with an action sheet: https://zpl.io/VQKNee4

All Android production screens specific for the Address book views:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c76558485e8aabc48c8df90

**Comment by tschubotz** [comment]
Thank you
