### ISSUE TITLE
[iOS] Texts in Sketch/Zeplin do not reflect iOS behavior

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe#113]
## Problem
I found out that all of the current screen designs delivered do not reflect the actual behavior of iOS for displaying fonts.

For example, for the font size of 20 points and up, the font used in the mockups should be SF Pro Display, and it should have tracking of 0,38 points (according to [HIG Typography](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/)).

![Screenshot 2019-01-29 at 10.37.34.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/0377cd49-20f1-4353-a6c4-056d2878f6e4)

Apart from that, in the example with header texts, the line spacing is also wrong as it is less than the font size.

## How it should be
The font typeface should be correctly selected according to the font size in points, and there should be a correct tracking setting on the font in the interface mockups, as it is specified in Apple's Human Interface Guidelines for Typography in iOS.

## What to do
We need to gradually proof and change all texts on all of the screens so that interface mockups would reflect the actual default iOS behavior. In that way, it is easier to develop the user interface screens, as the default behavior of the system would be matching the design mockups.

Documentation and tables are needed which specify which font and which track​ to use for different point sizes in iOS.

**Comment by posthnikova** [comment]
I updated fonts in Replace Browser Extension:

https://app.zeplin.io/project/5b8e45a7e1140d2c63bc08d1/dashboard?seid=5c0136de321dec2c78be0d91

zpl://project?pid=5b8e45a7e1140d2c63bc08d1&seid=5c0136de321dec2c78be0d91

In old iOS designs you can find SF Compact sometimes (although it's originally for WatchOS). In iOS Integration there should be no Compact.

**Comment by tschubotz** [comment]
Can this ticket be closed? @DmitryBespalov @posthnikova

**Comment by posthnikova** [comment]
I updated fonts everywhere in integration designs. I think this can be closed @DmitryBespalov @tschubotz
