### ISSUE TITLE
Restore Safe flow

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#120]

**Comment by posthnikova** [comment]
Redesigning Recover Safe as part of iOS integration. Project is here: https://invis.io/RGQEV7F8KDJ

**Comment by biocom** [comment]
@posthnikova Commented on this screen on inVision.

**Comment by tschubotz** [comment]
Okay from my side.

**Comment by biocom** [comment]
@tschubotz Have you reviewed the comments on InVision? It seems they are unaddressed yet.

**Comment by tschubotz** [comment]
True, there are still open comments, my bad. Commented on them.

**Comment by biocom** [comment]
@tschubotz No worries! :) - Thanks for reviewing.

**Comment by biocom** [comment]
First proposal for re-aligning Android https://invis.io/9RQHSFT42CK - Some elements differ which will be discussed internally.

**Comment by biocom** [comment]
Right now the start screen (no safe) differs between iOS and Android:
iOS: https://invis.io/RGQEV7F8KDJ#/345591294_01_SetUpSafeOptions_
Android: https://invis.io/2BQIU8GP36M

Please read my comments on the iOS screen. I think there might be a conflict in terms of:
- The fact that on Android we have the hamburger menu, is that weird to use with the valley bg?

**Comment by biocom** [comment]
In regard to my last comment: What has been discussed internally:
- The hamburger menu conflicts with the blue valley background for Android, therefore we decided to keep those screens separated.

Let's discuss in the UX weekly.

**Comment by tschubotz** [comment]
white |||

**Comment by posthnikova** [comment]
Setup options are on white now: https://invis.io/RGQEV7F8KDJ#/345591294_01_SetUpSafeOptions_

**Comment by biocom** [comment]
@posthnikova Looks good. Updated the text on Android to not be bold, so that it matches. 
@tschubotz Good to go for production?

**Comment by tschubotz** [comment]
The start screen looks good, yes. 
The rest of the screens still use quite different wordings (How it works, Input recovery phrase etc)
Android: https://projects.invisionapp.com/share/9RQHSFT42CK#/screens/346612360
iOS: https://projects.invisionapp.com/share/RGQEV7F8KDJ#/screens/345591295

Could you please align on that, too? :)

**Comment by biocom** [comment]
Left some comments on inVision for both Android and iOS. Once we've resolve those we can close this ticket.

**Comment by biocom** [comment]
No card usage for recover/create safe (Android).

**Comment by biocom** [comment]
Updated or Android https://invis.io/K7QQE6P26YJ - Please review.

**Comment by tschubotz** [comment]
Looks good to me, can be closed imo if the following is fixed and screens are on Zeplin:
- Android wording needs to be adapted on according to [this comment](https://projects.invisionapp.com/share/9RQHSFT42CK#/screens/346612358/comments/111364626 ) 
- Android header should be changed to the iOS header on [this screen](https://projects.invisionapp.com/share/9RQHSFT42CK#/screens/346612356) ([iOS](https://projects.invisionapp.com/share/RGQEV7F8KDJ#/screens/345591301)
  - Same on the [success version of the screen](https://projects.invisionapp.com/share/9RQHSFT42CK#/screens/346612357)
- I would also use the iOS wording on this [Android screen](https://projects.invisionapp.com/share/9RQHSFT42CK#/screens/346612355) ([iOS](https://projects.invisionapp.com/share/RGQEV7F8KDJ#/screens/345591303))

**Comment by biocom** [comment]
> Android header should be changed to the iOS header

Isn't this Android specific where the header (with back arrow) covers the existing step you're on?

**Comment by biocom** [comment]
Android production screens:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5b03c9bc49016f526bd97a76

**Comment by posthnikova** [comment]
Android is missing Insufficient funds screen https://invis.io/RGQEV7F8KDJ#/348757264_17_Insufficient_Funds_ETH_

Zeplin for ios is here: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c7689aa2e478f51ff1381ce

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c7689aa2e478f51ff1381ce

**Comment by biocom** [comment]
Should 'Amount received' be renamed to 'Safe balance' on that screen? So:

Safe balance...............
Amount needed..........

Send at least:
........................

**Comment by posthnikova** [comment]
You don't send anything, it's deducted, so it should be "Safe balance". Corrected.

**Comment by tschubotz** [comment]
On insufficient funds screen:
- no cancel/"x" button
- Use back button instead and allow the user to go back to the previous screens (enter recovery phrase)

**Comment by biocom** [comment]
Added the insufficient funds screen:
https://zpl.io/29OKRjw

**All screens:**
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5b03c9bc49016f526bd97a76

**Comment by posthnikova** [comment]
Cancel button changed to Back: https://invis.io/RGQEV7F8KDJ

Zeplin for ios updated: 

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c7689aa2e478f51ff1381ce

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c7689aa2e478f51ff1381ce

**Comment by biocom** [comment]
I reviewed Android/iOS and I think the ticket can be closed. @posthnikova can you do also a final review and close the ticket?

**Comment by posthnikova** [comment]
Android looks good

**Comment by tschubotz** [comment]
I noticed some more things:

(1)
- @biocom could you please change the title on thescreens to enter the address to "Recover Safe"?
  - https://zpl.io/aw4OL1N
  - https://zpl.io/bABWjE8
  - https://zpl.io/am5eOyv
  - https://zpl.io/bJ7W5Zr
  - https://zpl.io/b61gZ3R
  - https://zpl.io/2GyAvWd
  - https://zpl.io/VDBK9Wq
- iOS does that and I feel the current Android version has duplicated info. It helps to have the flow name on top in the title. iOS screens:
  - https://zpl.io/2yOW8y9
  - https://zpl.io/VxLw81R
  - https://zpl.io/VKPypo6
  - https://zpl.io/2yOW8lo
  - https://zpl.io/aw4OLmM
  - https://zpl.io/2GyW79E
  - https://zpl.io/2v701K7

(2) 
- Could you please create the following screen for Android?
  - https://zpl.io/VYKowGM
  - https://zpl.io/bzNDOLz (Camera screen to scan a QR code)
  - https://zpl.io/aR1GrzE (Review screen without 2fa)

(3)
- Wording is different on https://zpl.io/agzM5m0 and https://zpl.io/2p4kyMj
- I would use a wording similar to during the [creation flow](https://zpl.io/aMmE6NN), i.e. "Your transaction was submitted. Your Safe will be recovered now. This can take a couple of minutes."
- What do you think? Could you please adapt @posthnikova @biocom 

(4)
- When there is an error scanning the QR code, Android currently shows a error toast and iOS an error alert. Could you please create designs for this, as well?

**Comment by biocom** [comment]
1) Yes, looking at it now it's duplication. Updated the screens (same URL's).

2) Added:
Share - https://zpl.io/a8wkvRE
Camera - https://zpl.io/V1Nk53Z
Review (no 2FA) - I think the existing screen for that is already without 2FA? --> https://zpl.io/aXP9LPE

3) I think the text change is fine. Changed it here: https://zpl.io/agzM5m0

4) Added: https://zpl.io/2GykwYj
Currently on Android whenever you scan an incorrect QR code its says: `Error pairing device.` 
In the screen I created I opt for using: `Error pairing your device or incorrect QR code.`. That should cover all scenarios. Let me know your thoughts.

**Comment by posthnikova** [comment]
3) Updated https://zpl.io/2p4kyMj

4) Added https://zpl.io/V1NkXnJ 
On ios it's currently "Invalid QR code". To align with android maybe say "Error pairing your device or invalid QR code"?

**Comment by biocom** [comment]
@posthnikova 

On 4: Yes, I'd say so. Reason being that if we'd only have 'Invalid QR code' for all types of errors, that may misinform the end-user in thinking that the QR code they're scanning is at fault. Unless we can make the errors explicit for specific errors, I'd say keep a general error text.

**Comment by biocom** [comment]
For point 3.:
On iOS we've got the link 'Follow its progress on Etherscan.io'. I'd keep it as:
'Follow progress on Etherscan.io'.

**Comment by tschubotz** [comment]
I like the idea, then let's use "Error pairing your device or invalid QR code"

Also for the progress screen, "Follow progress on Etherscan.io" sounds good to me, i.e. without the "its".

**Comment by posthnikova** [comment]
Corrected error text: https://zpl.io/V1NkXnJ

Progress screen: https://zpl.io/2p4kyMj

**Comment by biocom** [comment]
Looks good to me. Close this ticket?

**Comment by tschubotz** [comment]
> Review (no 2FA) - I think the existing screen for that is already without 2FA? --> https://zpl.io/aXP9LPE

That screens says "The existing Safe will be recovered and associated with this device and connected browser extensions."

We need the Android equivalent of https://zpl.io/aR1GrzE that says "The existing Safe will be recovered and associated with this device." :) @biocom

**Comment by biocom** [comment]
**Updates:**
- Recover Safe [with extension] -> https://zpl.io/aXP9LPE
- Recover Safe [no extension] -> https://zpl.io/2EBzKJn
