### ISSUE TITLE
Replace browser extension

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#121]
Check that Android and iOS flows are similar.

**Comment by posthnikova** [comment]
Redesigning Replace browser extension as part of iOS integration. Project is here: https://invis.io/RGQEV7F8KDJ#/345591747_01_Replace_Browser_Extension_

Current android designs: https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897?seid=5b03c9a6c2fcab5116b66baa

Current iOS designs: https://app.zeplin.io/project/5b8e45a7e1140d2c63bc08d1?seid=5c0136de321dec2c78be0d91

**Comment by biocom** [comment]
Updated the Android screens:
https://invis.io/T2QIEF9B3KM

Some differences we need to discuss:

- Did we decide to have the Safe's balance on top (where the actual Safe is) or at the bottom?
Android - https://invis.io/T2QIEF9B3KM#/346793330_Replace_Browser_Extension_-_VII
iOS - https://projects.invisionapp.com/share/RGQEV7F8KDJ#/screens/345591758

- Will we have 'View Transaction details' (or at least secondary action) on this screen:
https://invis.io/T2QIEF9B3KM#/346793329_Replace_Browser_Extension_-_VIII
https://projects.invisionapp.com/share/RGQEV7F8KDJ#/screens/345729235
And text differs so we would need to discuss.

**Comment by sche** [comment]
My comments:
1) Do we need "Enter current password" screen here? Currently, on iOS all restricted operations require "unlock" procedure. I would keep it for current operation as well.
2) For setting up a new password we could use already existing screens that we use during onboarding. It will save dev time.
3) IMO design should be consistent with setting a password during onboarding. So I would change it in onboarding as well or would make it here as two separate screens.

**Comment by tschubotz** [comment]
Concerning balance on top or not. I don't have a real preference. I like the option with the balance on top more since that's the starting point. In any way, we should probably keep it in syn with The send flow (e.g. https://projects.invisionapp.com/share/FBPH0OFQ57P#/screens/339971945)

Concerning "View tx details": I think it's unnecessary. Clicking the other button would lead the user to the tx list from where they can check the details still.

**Comment by biocom** [comment]
- Balance on top: Yes, has my preference too and is in line with what we do with Send Funds.
- View tx details: It was my initial thinking too: Why show two actions buttons if 1 single action make it less complicated? You'd end up in the TX overview where the last sent Tx is on top in the 'PENDING' section.

@posthnikova Let me know your thoughts.

**Comment by posthnikova** [comment]
Small changes:

1) Added divider and current balance on Start screen: https://invis.io/RGQEV7F8KDJ#/345591747_01_Replace_Browser_Extension_

2) Corrected error state for input fields: https://invis.io/RGQEV7F8KDJ#/345591756_07_My_Recovery_Phrase_Error_

3) Changed transaction type to "Settings change": https://invis.io/RGQEV7F8KDJ#/345591760_11_TxView_Replace_Browser_Extension_

4) On Congratulations (Replacing in progress) screen there is now one button

5) On Review screen remover balance on top, added current balance to amounts at the bottoms: https://invis.io/RGQEV7F8KDJ#/345591758_09_Review_

**Comment by biocom** [comment]
Updated Android: https://invis.io/T2QIEF9B3KM

**Comment by tschubotz** [comment]
The flow looks good to me. I put some comments. Mainly wording differences between iOS and Android. And sometimes different numbers are in bold typeface.

**Comment by biocom** [comment]
Some screens were update based on your comments @tschubotz 
Please review: https://invis.io/T2QIEF9B3KM

**Comment by tschubotz** [comment]
Can be closed if texts and alignment match and screens are on Zeplin.

**Comment by posthnikova** [comment]
Zeplin is here:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c6ebc6c92623b407fa908c2

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c6ebc6c92623b407fa908c2

**Comment by biocom** [comment]
Android production screens:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5b03c9a6c2fcab5116b66baa

[zpl://project?seid=5b03c9a6c2fcab5116b66baa&pid=5af063c9b4dc859b6bdaf897](url)
