### ISSUE TITLE
Replace recovery phrase

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#122]

**Comment by posthnikova** [comment]
Redesigning Replace recovery phrase as part of iOS integration.
Project is here: https://invis.io/RGQEV7F8KDJ#/345591608_01_Replace_Recovery_Phrase_

Current ios: https://app.zeplin.io/project/5b8e45a7e1140d2c63bc08d1?seid=5c015359bbce2c79496b0a03

Current android: https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897?seid=5b03c9dbb0161ad12b5733ea

**Comment by tschubotz** [comment]
I like it, just made 1 comment on Invision about showing the current Safe balance on the intro screen. What do you think?

**Comment by posthnikova** [comment]
Prototype for user tests: https://invis.io/RGQEV7F8KDJ#/345591608_01_Replace_Recovery_Phrase_

Changes:

1) Changed text on card on Review screen: https://invis.io/RGQEV7F8KDJ#/345591614_07_Review_

2) Added divider on Replace recovery phrase screen: https://invis.io/RGQEV7F8KDJ#/345591608_01_Replace_Recovery_Phrase_

3) Added current balance: https://invis.io/RGQEV7F8KDJ#/345591608_01_Replace_Recovery_Phrase_

4) Illustration aligned with android on New recovery phrase screen: https://invis.io/RGQEV7F8KDJ#/345591611_04_New_Recovery_Phrase_

5) Transaction type changed to Settings change

**Comment by biocom** [comment]
Updated Android screens https://invis.io/8FQIGR6P5YT
Do we need a prototype for Android?

**Comment by tschubotz** [comment]
Flow looks good to me :)
There are still some wording differences. Other than that good to go from my side.

I think there's no need for a prototype on Android.

**Comment by biocom** [comment]
@tschubotz Mostly re-aligned now https://invis.io/8FQIGR6P5YT 
Some visual differences do exists which I left comments for in inVision. Need to review With Sasha if /how we want to re-align.

**Comment by tschubotz** [comment]
Waiting for changes and zeplin uploads.

**Comment by biocom** [comment]
Android production screens:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5b03c9a6c2fcab5116b66baa

[zpl://project?seid=5b03c9a6c2fcab5116b66baa&pid=5af063c9b4dc859b6bdaf897](url)

One note: I chose to keep the blue gradient bg in the area where you confirm the recovery words: We're using a grey background above, so using a grey bg there doesn't provide the right contrast. Same for using white, given we have white buttons, also doesn't provide enough contrast.

**Comment by posthnikova** [comment]
Zeplin is here:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c6ed17cdbd858406dcf8a21

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c6ed17cdbd858406dcf8a21
