### ISSUE TITLE
Link to the Rinkeby version of the browser extension on mobile apps

### ISSUE THREAD

**Issue by germartinez** [gnosis/safe#124]
Currently, on the onboarding process, the mobile apps only show a link to the Mainnet version of the Safe Browser Extension. It would be convenient to show a link to the Rinkeby version of the Safe Browser Extension when the mobile app is running on Rinkeby.

**Comment by tschubotz** [comment]
Good idea! We have at least 1 report where users connected a Rinkeby app with a mainnet extension. We should resolve this as part of #67 and in all the Epic about adding / replacing the browser extension (#73 #60 )

**Comment by fmrsabino** [comment]
One suggestion would be to use `rinkeby.safe.gnosis.io` what do you think?
