### ISSUE TITLE
Screens for loading balances & no internet connection.

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#125]
During spec writing, I noticed that we are missing some screens:

1: How should it look when the balances are loading? (Initially and when the user "pulls to refresh")
2: When there is no Internet connection (There are 2 cases: (2a) When the balances are cached, (2b) when the balances have no been loaded before.)

Could you please come up with UI for these cases? @posthnikova @biocom

**Comment by posthnikova** [comment]
I made static screens and added references for animation.

1) When balances are loading - initially


![Loading.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/20e2d527-3030-4d38-a961-ffa83f996612)


When overview screen is opened I suggest shimmer animation. Examples: https://www.dropbox.com/s/75ug5kz7bitytoo/funnel.mp4?dl=0, https://dribbble.com/shots/4891695-Loading-States,  https://dribbble.com/shots/1756495-Loading-Explorations

2) When balances are loading - when the user pulls to refresh


![Pull_to_refresh.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/e3cebd4d-5518-4f6a-adde-e307a150714d)


I had a proposal for pulling to refresh previously https://www.dropbox.com/s/k5ww8nfu4jyu7kb/Pull-to-refresh-tokens.gif?dl=0
We can reuse this. After the user releases finger we can show shimmering rectangles plus "Loading" and spinner in nav bar.

3) No internet connection when the balances are cached

If balances are cashed and we know that there is no internet I propose we only show error message.

4) No internet connection when the balances have not been loaded before

If the balances have not been cashed and we know that there is no internet I propose we show balances as rectangles and "Waiting for network" and spinner in nav bar

**Comment by tschubotz** [comment]
I really like these user flow overviews!

I'm not sure about the following 3 things:
(1)
Why is the loading indicator different when initially loading and when using pull to refresh? In the end, the same things happening, right? So I would use in both cases the version of the pull to refresh loader. (+ initally these "empty rows" that you suggested)

(2)
When there is not internet connect, I would go for either the red indicator or the popup. I prefer the red indicator because it can't be dismissed.

(3)
I like your loading indicator (the gif) visually a lot! I think we should leave that in the designs, however we'll have to see how much effort it is to implement. If it's too much, I would use the system spinner instead to save time.

@biocom what's you take on this?

**Comment by biocom** [comment]
1 - Agree, I'd consolidate the refresh/loading pattern.
2. Red indicator is good. But I think what @posthnikova tried to showcase, is when you try to refresh (manually) to show the pop-up (correct?). In that case I think it's important to prompt the user with that dialog to inform they can't do that. (Could also be a toast message on Android).

**Comment by posthnikova** [comment]
New version:

![Loading.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/4a3e3ddd-9979-4b2c-850b-4eed858171ff)

![Pull_to_refresh.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/b9254973-af88-4e6e-84cd-7b70632fb126)

What's been done:

> Why is the loading indicator different when initially loading and when using pull 
> to refresh? 

Agreed

> When there is not internet connect, I would go for either the red indicator or the popup. 

Red indicator shows always when we know there is no internet. Popup shows only when the user attempts to refresh to indicate it's impossible. I corrected the screen with popup because it opens from a screen with red indicator. 

I also attach example of shimmer animation:

![shimmer.gif](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/583fe60c-2156-43bb-8ed3-4a73b9839a96)

View screens fullsize: https://invis.io/PEPL75H7ZV6#/350318534_01_Loading_Initially

**Comment by tschubotz** [comment]
I feel this proposal is too complex. There is a spinner/movement in 2 places. Why don't we reuse the current solution implemented on the clients?

**Comment by biocom** [comment]
After a second look on the UI proposals, I think the shimmer animations are probably enough on its own and I think they also fulfill an 'expectation management' role. It's what other apps seem to use, so we could assume users understand something is loading. 

In case something fails, we could throw an explicit error (for example: NO INTERNET CONNECTION).

**Comment by tschubotz** [comment]
- Shimmering: not ideal when there are already balances -> let's not do that.
- Spinner
 - Top spinner not ideal when there is pull to refresh
 - Is pull to refresh needed? Ideally balances would always automatically load (Similar to telegram / whats app)

-> UX sync: 
- No pull to refresh. To check with mobile devs how often auto refresh happens and if there's other things to consider.
- If there is no internet connection?

Do we always put that spinner in the top bar?

@biocom to clarify these questions and check what other apps do. 🔥

**Comment by biocom** [comment]
I created a document with questions, comments and notes: https://docs.google.com/document/d/1X2jpVwCXk7d31c5x_qGBOtcdPrQ40FmyKAfCmYpAQ9Q/edit?usp=sharing

Please review and let me know your thoughts. 

For now I'm under the impression that:
- Pull to refresh can be useful, in case the automatic background refresh takes (for example) more than 30 seconds. A side question there is: Is there any other data being refreshed, other than the token balance? And what is the background refresh interval.

- Android and iOS both have a default different implementation of the pull to refresh / spinner. 
The fundamental differences:
 1. For iOS, the Pull-to-Refresh is embedded as part of the list.
 2. For Android, the Pull-to-Refresh is not part of the list, but on top of it.

- For Android I think we could stick to our existing spinner in the assets overview. We could distinguish between: 'Pull to refresh' spinner (like we have now for assets) and for when a view is being loaded (E.g. searching tokens, a view is loading) which in case we could show a centered spinner in the view.

- For iOS we could show the spinner Sasha posted (GIF) but it would pull the content down: https://cdn-images-1.medium.com/max/1600/1*wOQlX4HQnqK32t0iTzl43Q.gif - When doing a search or a view is being loaded, we could do something like https://i.gifer.com/Hatm.gif (centered spinner) - @posthnikova Please let me know your thoughts on the iOS aspects.

- As for the message when there's no internet: I think having the message fixed at the bottom would be the most ideal, given it doesn't interfere with the top section of the app.

**Comment by tschubotz** [comment]
yes

**Comment by biocom** [comment]
### Offline state

**Android**
For android I got the offline state in a snackbar message with a single 'RETRY' action:
https://invis.io/C2RI1TD5HAE#/357537828_LUKAS_REVIEW_TITLE-_-_-ANDROID-_Safe_Overview_-_NO_INTERNET
- As discussed in the UX sync today: In 'offline' mode we allow the user to still go to the 'SEND ETH' view. User can't from there as long as there's no internet connection
- I assume internet connection is checked regularly as a background task? But on tap of 'RETRY' it would force a re-check of internet connection. I would propose the same action for pull-to-refresh. In the current app version a 'spinner' is shown for quite a long time. I would try to show this much quicker/sooner.

**iOS**
- Up to Sasha where to place the 'NO INTERNET CONNECTION' banner, but if it's up to me it's probably fine where it is now. It only 'hides' the 'SAFE' title, but that shouldn't be an issue.

---

### Loading balances / spinners / pull to refresh

**Android**
- As discussed in one of the latest UX syncs, we'd keep the pull to refresh functionality.
- Would propose to leave the balances spinner unchanged. Right now we show the 'standard' activity spinner circle when balances are loading. 
- The same spinner is used when certain content is loading. E.g. searching for a token in 'Manage tokens'. 
- The activity spinner overlays the content and no content is actually being pulled down (only the spinner itself..).

**iOS**
- I think the activity spinner for the balances could be in the same position as Sasha proposed here:
<img width="377" alt="Screen Shot 2019-04-11 at 17 19 54" src="https://user-images.githubusercontent.com/31534717/55969450-1b969980-5c7e-11e9-9ac5-0fd26750f777.png">
With or without the blue valley bg, is up to Sasha. 
- I would not show this additional spinner on top:
<img width="377" alt="Screen Shot 2019-04-11 at 17 20 05" src="https://user-images.githubusercontent.com/31534717/55969494-2cdfa600-5c7e-11e9-96ab-5a09bb71d559.png"> 
Also for when loading views/results (e.g. search for tokens) I'd probably show the spinner where the content should go. But I'll leave that up to Sasha.

**Comment by posthnikova** [comment]
*Offline state*

*• Error message*
Show No internet connection message: https://invis.io/PEPL75H7ZV6#/358393269_01_AssetView_-no_Internet-
Ideally it would slide out and shift down all the other content, and slide away after a few seconds. Pull down re-checks if there is connection. If on pull down there is still no connection, the message slides out again.

![no_internet.gif](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/e8013fac-e997-44f1-a18a-19516de397cd)

*• Spinner in nav bar while there's no internet connection*
On assets overview there is no spinner in the nav bar. On other screens which require network requests there's a spinner in the nav bar (creating a Safe, recovering, loading network fees, loading balances, loading available tokens, token search, load tx list, load tx details, submit tx, send push to extension).
Example of Send screen: https://invis.io/PEPL75H7ZV6#/358393270_02_Send_Input_-no_Internet-

*• Inline error while there's no connection*
If we know there's no internet we show inline error where balances failed to load.
Example of not being able to load network fees on Send screen: https://invis.io/PEPL75H7ZV6#/358393271_03_Send_Input_-filled_No_Internet-.
Example of not being able to load balances: https://invis.io/PEPL75H7ZV6#/358393272_04_Connect2FA_-no_Internet-

*• Alert*
Alert shows after user's action, for example trying to scan qr code https://invis.io/PEPL75H7ZV6#/358393273_05_Sessions_List_Network_Error

*Loading balances / spinners / pull to refresh*

*• Pull to refresh on Assets view*
Use existing spinner https://prnt.sc/ncna99 on (static) valley background: . Don't use spinner in nav bar on this screen.

*• Spinner in nav bar*
Show while loading everywhere except Assets screen. Don't show spinner in content (it's already in nav bar)
Example of loading on Send screen: https://invis.io/PEPL75H7ZV6#/358394679_06_Send_Input_-loading-
Example of not being able to load network fees on Send screen: https://invis.io/PEPL75H7ZV6#/358394680_07_Send_Input_-filled_Loading-
Example of not being able to load balances: https://invis.io/PEPL75H7ZV6#/358394681_08_Connect2FA_-loading-

*• Loading search results*
Use spinner in content: https://invis.io/PEPL75H7ZV6#/358396277_09_ManageTokens_-loading_Search-

**Comment by posthnikova** [comment]
### Offline state

*• Error message*
Show No internet connection message: https://invis.io/PEPL75H7ZV6#/358393269_01_AssetView_-no_Internet-
Ideally it would slide out and shift down all the other content, and slide away after a few seconds. Pull down re-checks if there is connection. If on pull down there is still no connection, the message slides out again.

![no_internet.gif](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/b4c36bd3-6ea3-4501-a0b1-915d3559a508)

*• Spinner in nav bar while there's no internet connection*
On assets overview there is no spinner in the nav bar. On other screens which require network requests there's a spinner in the nav bar (creating a Safe, recovering, loading network fees, loading balances, loading available tokens, token search, load tx list, load tx details, submit tx, send push to extension).
Example of Send screen: https://invis.io/PEPL75H7ZV6#/358393270_02_Send_Input_-no_Internet-

*• Inline error while there's no connection*
If we know there's no internet we show inline error where balances failed to load.
Example of not being able to load network fees on Send screen: https://invis.io/PEPL75H7ZV6#/358393271_03_Send_Input_-filled_No_Internet-.
Example of not being able to load balances: https://invis.io/PEPL75H7ZV6#/358393272_04_Connect2FA_-no_Internet-

*• Alert*
Alert shows after user's action, for example trying to scan qr code https://invis.io/PEPL75H7ZV6#/358393273_05_Sessions_List_Network_Error

### Loading balances / spinners / pull to refresh

*• Pull to refresh on Assets view*
Use existing spinner https://prnt.sc/ncna99 on (static) valley background: . Don't use spinner in nav bar on this screen.

*• Spinner in nav bar*
Show while loading everywhere except Assets screen. Don't show spinner in content (it's already in nav bar)
Example of loading on Send screen: https://invis.io/PEPL75H7ZV6#/358394679_06_Send_Input_-loading-
Example of not being able to load network fees on Send screen: https://invis.io/PEPL75H7ZV6#/358394680_07_Send_Input_-filled_Loading-
Example of not being able to load balances: https://invis.io/PEPL75H7ZV6#/358394681_08_Connect2FA_-loading-

*• Loading search results*
Use spinner in content: https://invis.io/PEPL75H7ZV6#/358396277_09_ManageTokens_-loading_Search-

**Comment by lukasschor** [comment]
UX Sync Decision: Looks good.

**Comment by lukasschor** [comment]
After discussing with @biocom, let's go with the following solution to allign with the Rinkeby label:
- Rinkeby sized banner
- Light-blue background
- Center-algined
- *No* retry icon or button
- Entire banner clickable (to refresh)
- Banner stays until internet connection is recovered

If there are no objection, let's implement it this way.

**Comment by lukasschor** [comment]
Looks good to me. 👍

**Comment by lukasschor** [comment]
Looks good to me. 👍

**Comment by lukasschor** [comment]
Looks good to me. 👍

**Comment by posthnikova** [comment]
Updates to no internet connection message after UX sync (persistent, not clickable):
With token payment: zpl.io/V0L4eOK
Without token payment: https://zpl.io/agQjWwO

**Comment by biocom** [comment]
Looks good to me. Both Android/iOS production screens are on Zeplin, for both with and without the token payment functionality.

**Comment by lukasschor** [comment]
Perfect. Will add the screens to Lokalise and close the ticket. 🥳
