### ISSUE TITLE
Align transaction list & details

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#126]
While writing the spec for this, I noticed some missing screens and also some inconsistencies between Android and iOS. We need to align this.

### Transaction list
[Android](https://zpl.io/VDOglMq), [iOS](zpl.io/adr8ZZ7)
- Some icons are different.
- Android screens needs to be updated with the new top part (identicon)

### Transaction list - Empty
[Android](zpl.io/Vqx3y9N), [iOS](https://zpl.io/VqKRpd4)
This looks good to me, but the Android screen doesn't use yet the new top layout (Identicon)

Transaction details
[Android](https://zpl.io/agnwKgQ), [iOS](https://zpl.io/aByYr4k)
This screen looks different on both platforms:
- Android still uses a wrong short address format
- iOS doesn't mark the amount in red. I think that's better.

### Transaction details - Failed
How does a failed tx details screen look like?
I found this one for [Android](https://zpl.io/boKNxEg)
- We need one for iOS

### Transaction details - Pending
How does a pending tx screen look like?

### Transaction details - Data
When e.g. interacting with a dapp like slow trade, how should the tx be displayed?

### Transaction details - Settings change
[Android](zpl.io/boBjO1X), [iOS](https://zpl.io/aXwd06E)
I think we should define how this screen looks like in the following scenarios:
- Add browser extension later
- Replace browser extension
- Replace recovery phrase
- Restore Safe
- Remove browser extension

**Comment by biocom** [comment]
Android updates:

Transaction details:
https://invis.io/N3QIEAYH9JB

Transaction list/overview:
https://invis.io/5JQJD5ZX7MF

Including a scroll state of the transaction list, where the header gets minified.

**Comment by posthnikova** [comment]
Transaction list - empty: https://invis.io/PEPL75H7ZV6#/341738903_01_OverviewTxList-Empty

Transactions list: https://invis.io/PEPL75H7ZV6#/336600645_02_OverviewTxList

Transaction details: https://invis.io/PEPL75H7ZV6#/336618171_04_TxView

Transaction details - pending: https://invis.io/PEPL75H7ZV6#/348150354_06_TxView_Pending_

Transaction details - failed: https://invis.io/PEPL75H7ZV6#/348150351_05_TxView_Failed_

Transaction details - Data: https://invis.io/PEPL75H7ZV6#/348152382_07_TxView_Data_

Transaction details - settings change:

Add browser extension later https://invis.io/QRQ97T1NBES#/343967926_09_TxView_Pending_
Replace browser extension https://invis.io/RGQEV7F8KDJ#/345591760_11_TxView_Replace_Browser_Extension_
Replace recovery phrase https://invis.io/RGQEV7F8KDJ#/345591621_13_TxView_Replace_Recovery_Phrase_
Restore Safe https://invis.io/RGQEV7F8KDJ#/345591312_23_TxView_Recover_Safe_ETH (without extension: https://invis.io/RGQEV7F8KDJ#/347647309_24_TxView_Recover_Safe_W-O_Extension_)

Remove browser extension - what is remove browser extension? Do we have this feature?

**Comment by tschubotz** [comment]
iOS screens look good.
Android is still missing: 
- Transaction details - Pending
- Transaction details - Data
- Transaction details for all the setting changes

> Remove browser extension - what is remove browser extension? Do we have this feature?
We don't have it yet, true.

**Comment by biocom** [comment]
Updated transaction details:
https://invis.io/N3QIEAYH9JB

Transaction list:
https://invis.io/5JQJD5ZX7MF

One difference I noticed is that on iOS for the transaction list https://projects.invisionapp.com/share/PEPL75H7ZV6#/screens/336600645 the last group has the label 'PAST" whereas on Android they are grouped by a day/date e.g. (FEB 11).

**Comment by tschubotz** [comment]
Thanks for the updates!
Concerning the section headers in the transaction list, here's what I think we should do:
**Time/data**
- Display the date + time in each row for all txs. Currently we have the following:
  - Android: "Just a moment ago", "x minutes ago", "x hours ago", date + time for older txs. (I know designs are different, but that's what the app does)
  - iOS: "Just now", "x minutes/hours/days/months ago"

**Sections**
- "Pending" section for all transactions in progress. 
- "Today" section for transactions of today
- "Yesterday" section for transactions of yesterday
- "Past" section for transactions that are old. I think it does not make sense to display the date because we already have it on every row.
- Sections are not visible when there are not txs to display

What do you think @posthnikova @biocom? :)

**Comment by biocom** [comment]
Some thoughts:
- Having a 'past' (older?) grouped label, for me is of no added value. I'd rather see them grouped by a single date (e.g. I might do a lot of transactions on a specific day). Or alternatively grouped on a monthly basis. In my opinion we can come up with a better solution than grouping them in a single 'past' group.

- In case we decide to not group by date (e.g. FEB 11), then yes we need DATE + TIME. If we do group by dates, we could keep the records shorter and just display TIME.

**Comment by posthnikova** [comment]
Do you propose changing "1 min ago", "5 min ago" etc to actual time and date?.

The sections on iOS are as you mentioned. On android we have date instead of "Past"

**Comment by tschubotz** [comment]
> Having a 'past' (older?) grouped label, for me is of no added value. I'd rather see them grouped by a single date (e.g. I might do a lot of transactions on a specific day). Or alternatively grouped on a monthly basis. In my opinion we can come up with a better solution than grouping them in a single 'past' group.

Right now, there's barely more than 1 tx per day.
But sure, we can also put the day in the section header and then just the time on the cell.

> Do you propose changing "1 min ago", "5 min ago" etc to actual time and date?.

Yes, I was thinking about that. What do uyou think.

> On android we have date instead of "Past"

Yes, in the design, not inside the app.

**Comment by biocom** [comment]
> Right now, there's barely more than 1 tx per day.
> But sure, we can also put the day in the section header and then just the time on the cell.

I think we need to account for scenarios beyond the amount of transactions right now. Assuming the Safe will be used more extensively by its user base in the (near) future, this feature will become self evident in my opinion. Please let me know counter arguments if any, but I'm forming this opinion based on self use of banking apps and how other token wallets group their transactions.

> Do you propose changing "1 min ago", "5 min ago" etc to actual time and date?.
> Yes, I was thinking about that. What do uyou think.

What is the argument for against using 'xxx ago' type of labels for very recent transactions?

**Comment by tschubotz** [comment]
Some inspiration from other apps: 
<img src="https://user-images.githubusercontent.com/1380529/53483753-7c796200-3a82-11e9-8442-760637c77dad.png" width="200px"><img src="https://user-images.githubusercontent.com/1380529/53483754-7c796200-3a82-11e9-8195-ab6bc2ef4fcc.png" width="200px"><img src="https://user-images.githubusercontent.com/1380529/53483755-7c796200-3a82-11e9-8ac8-0daef67132ad.png" width="200px"><img src="https://user-images.githubusercontent.com/1380529/53483756-7c796200-3a82-11e9-90cb-671ac69880cf.png" width="200px"><img src="https://user-images.githubusercontent.com/1380529/53483770-84390680-3a82-11e9-8bba-654309c61091.png" width="200px"><img src="https://user-images.githubusercontent.com/1380529/53483771-84390680-3a82-11e9-88b0-c555b95dacfe.png" width="200px">

**Comment by tschubotz** [comment]
> What is the argument for against using 'xxx ago' type of labels for very recent transactions?

None really, other than not have any special cases. I didn't see any value in "2 months ago on all transactions in my Safe. That's why I think for txs long ago, we should use the datetime.

What is you specific proposal, what format would you use where?

**Comment by biocom** [comment]
> What is you specific proposal, what format would you use where?

Essentially the Android mockup like here https://invis.io/5JQJD5ZX7MF#/347081404_-ANDROID-_Safe_Transactions
- Group by TODAY / YESTERDAY / then by EACH DAY (e.g. FEB 11)
- Only use 'xxx ago' for very recent transactions. 'Very recent' we could define as <24hrs or <12hrs, whatever makes most sense. In case this is hard to implement, I'd be fine with just having the timestamp.

The only downside I could think of having TODAY and YESTERDAY is when somebody doesn't know what date TODAY/YESTERDAY is. Which could be an argument for saying to always group by DATE.

**Comment by posthnikova** [comment]
> Group by TODAY / YESTERDAY / then by EACH DAY (e.g. FEB 11)
> Only use 'xxx ago' for very recent transactions. 'Very recent' we could define as <24hrs 
> or <12hrs, whatever makes most sense. In case this is hard to implement, I'd be fine with just 
> having the timestamp.

I agree, only I propose not to use 24 or 12 hours and display 'xxx ago' for today. For everything that was yesterday display the exact time without date. Cutoff should be at 00:00 of the current day. For earlier transactions use date in the section header and exact time in the list item.

**Comment by tschubotz** [comment]
Perfect, that works for me, I like the proposal! 
Let me summarize for future reference and to see if I got it right:

**Section headers**
- "Pending" for pending txs
- "Today" for all txs that happened today, i.e. on the same calendar day like the current day.
- "Yesterday" for all txs that happened yesterday, i.e. the previous calendar day.
- "<month day>" for all previous txs that happened this year. We use the format depending on the user's locale settings, i.e. e.g. "Feb 12"
- "<month day, year>" for all previous txs of the previous year. We use the format depending on the user's locale settings, i.e. e.g. "Dec 31, 2018"

**Time indicator on the tx row**
- If tx happened on current calendar day (today):
  - "Just now" if < 1min ago
  - "x minutes ago" if >= 1min & < 1h ago
  - "x hours ago" if >= 1h & < 24h ago
- If tx happened before today: Please put the time (hours + minutes only, not seconds), depending on the selected locale.

Is this correct?
(I added the year for txs that happened last year.)

**Comment by biocom** [comment]
@tschubotz Sounds right to me!

**Comment by biocom** [comment]
Added to production for Android:

Transaction list:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c767749d391d651e7027789

Transaction details:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5af0659352d29dbf244f76e4

**Comment by posthnikova** [comment]
Updated ios in zeplin:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c4f17d87a8bebbfe8c4163f

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c4f17d87a8bebbfe8c4163f

**Comment by biocom** [comment]
Differences spotted:
- Wrapping of the token symbol on the transaction list. iOS wraps it to a new line, Android doesn't.
- For Android we have a scrolled view where the top header shrinks: https://zpl.io/VQBvYp5 - I imagine we need such a view for iOS too?
- Do we have the equivalent screens for actions belonging to 'unknown' and known (as in, saved in the Address book) addresses? See:
https://zpl.io/am5dw7D
https://zpl.io/br8vpW5 (did we discuss to **not allow** editing here, but leave that up to the Address book? Which in case I would remove this screen.)

**Comment by posthnikova** [comment]
Updated tx list: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/screen/5c766da4c7bd5051ed45cb0f

Small header: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/screen/5c781866760bbd51f309d133

All possible digits: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/screen/5c766da4be5823bd1115b9bf

**Comment by biocom** [comment]
@posthnikova Looks good. I think we can close this ticket.

One question I had, was if we'd also use those 3 dots for known/unkown addresses on a screen like https://zpl.io/VOPAN4Y

**Comment by posthnikova** [comment]
I wouldn't add it on Review screen because we don't want the user to leave Send flow

**Comment by posthnikova** [comment]
Last missing screen: small header on Overview Assets
https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/screen/5c7d02d28663ddbcaebee28e

Other than that zeplin didn't change:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c4f17d87a8bebbfe8c4163f

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c4f17d87a8bebbfe8c4163f

**Comment by biocom** [comment]
Added a screen to production, showing the small header (on scroll) for the Assets overview:
https://zpl.io/bLP1QJ7

All production screens for Android:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c41c8bc4def2a015b85322f
