### ISSUE TITLE
Add touch ID / face ID to iOS menu

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#127]
While writing the spec, I noticed that we don't have a way to enable / disable face/touch ID in the iOS menu.
Could you please add that?

cf. Android: zpl.io/VYAlyZe

**Comment by posthnikova** [comment]
Menu is up for review here: https://invis.io/3HQ098MTCPU

We prompt to use face id/touch id after password setup. After that it's only available in the menu. We don’t show the option at all if it is not enabled in system settings.
