### ISSUE TITLE
UX test: Token payment for Safe creation

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#132]

**Comment by tschubotz** [comment]
We need screens / prototype by Tuesday evening since the testing is supposed to happen on Wed (13th)
@biocom @posthnikova 

One client is enough.

**Comment by posthnikova** [comment]
Specification for testing: https://docs.google.com/document/d/1z2Sd9Dots6g_9_ue5BGL7Er_dccdWNbZil5j85HSOK4/edit
