### ISSUE TITLE
Add licenses / libraries page to website

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#135]
# Background
In the app settings, we'll start linking to used open source libs (legal requirement).
I suggest adding a page similar to https://safe.gnosis.io/terms or https://safe.gnosis.io/privacy to our website.

# Task
- Please add a page to our website at the url https://safe.gnosis.io/licenses/
- Content: https://docs.google.com/document/d/1hg_0dsWMlIF_WSk5GjQFz-gzhsjVIndc6Q9GmglKZko/edit#
- Please add a page to our website at the url https://safe.gnosis.io/licenses#ios should link to the iOS section.
- Please add a page to our website at the url https://safe.gnosis.io/licenses#android should link to the Android section.

**Comment by biocom** [comment]
Please view the proposal: https://safe.staging.gnosisdev.com/licenses

Android direct anchor url: https://safe.staging.gnosisdev.com/licenses#android
iOS direct anchor url: https://safe.staging.gnosisdev.com/licenses#ios

**Comment by tschubotz** [comment]
Look nice! Just have small feedback:

- Could you please capitalize Gnosis **S**afe in the first sentence?
- Could you please make the links clickable?

**Comment by biocom** [comment]
Updated :) - https://safe.staging.gnosisdev.com/licenses

**Comment by tschubotz** [comment]
Looks good from my side 👍

**Comment by biocom** [comment]
Live on production https://safe.gnosis.io/licenses - closing this ticket.
