### ISSUE TITLE
Send information of the device when Firebase token is registered

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe#136]
## Story
As a developer of the notification service, I would like to have more information of the devices registered in the service.

## Background
- Currently just the `firebase token` and the `ethereum address` is stored for every device
- It would be very useful for new functionalities to store information about the device (operating system, version, client), so we can use different logic for every device depending on `iOs`, `Android`, `Web`...

## Acceptance criteria
* Device information should be gathered and stored when a device is registered in the service.

## Open questions
* What information should be stored?

**Comment by rmeissner** [comment]
I would add the client ( `android`, `ios`, `extension`) a package id (e.g. `io.gnosis.safe` or whatever the client uses, this should indicate what build it is probably) and a buildnumber (integer, not sure how it is called on iOS)

I would use a buildnumber rather than a version name, since it is easier to compare numbers than to parse semantic versioning

**Comment by sche** [comment]
Should this be part of auth() request? Or do you want to have a separate endpoint for that?

**Comment by fmrsabino** [comment]
> I would add the client ( `android`, `ios`, `extension`) a package id (e.g. `io.gnosis.safe` or whatever the client uses, this should indicate what build it is probably) and a buildnumber (integer, not sure how it is called on iOS)
> 
> I would use a buildnumber rather than a version name, since it is easier to compare numbers than to parse semantic versioning

Agreed. These 3 fields should be enough.

> Should this be part of auth() request? Or do you want to have a separate endpoint for that?

While I agree this in theory should be sufficient, if the app is updated there's no guarantee that the push token will be updated as far as I know.

> The registration token may change when:
> 
> - The app deletes Instance ID
> - The app is restored on a new device
> - The user uninstalls/reinstall the app
> - The user clears app data.

See: https://firebase.google.com/docs/cloud-messaging/android/client#sample-register

**Comment by DmitryBespalov** [comment]
Hi all, we need this spec to be done by the April 5th, end of the day.
