### ISSUE TITLE
WalletConnect UX/UI

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#138]
Following up from our Kick off meeting ([Notes](https://docs.google.com/document/d/1f-lvFPaCJFDGLAWxvUnFA5JYnka_cRHERen1eSAR5CY/edit#), let's create designs of the WalletConnect integration.

Generally, we need to support the following features/flows:
- Connect to dapp (via QR code scan)
- Close connection to dapp
- View list of open connections
- Confirm/reject tx from dapp

**Comment by posthnikova** [comment]
Project is up for review: https://invis.io/3ER8F3INR48

What has been done:
1) Getting started and connecting to dapp:
• In the Menu there are now multiple Safes
• I added a state when notifications are disabled on a system level
• Onboarding texts are now more close to real, illustrations will be created later

2) Other flows shown:
• when qr code belongs to a dapp that already has an active session with current Safe. We allow only one active connection for a dapp with current Safe
• when qr code belongs to a dapp that already has an active session with another Safe. We offer to close that connection and start a new one with the current Safe
• Closing connection to dapp from Safe
• When connection is closed by dapp
• Transaction request and signing transaction

**Comment by biocom** [comment]
@posthnikova Thanks for the updates. Left some comments.

**Comment by posthnikova** [comment]
New version: https://invis.io/3ER8F3INR48
What has been done:

1) Disconnecting: https://invis.io/3ER8F3INR48#/354630638_18_Swipe_Left_
There was a comment from Kei at design sync to make an option to disconnect more visible. But after some deliberation I decided to keep the swipe because we have it in other places (address book). If it works for address then I don't know why it wouldn't work here.
2) Dapps - the wording is consistent everywhere
3) More refined onboarding texts and illustrations
4) Sessions list: https://invis.io/3ER8F3INR48#/354630517_16_Sessions_List_
Added a line with the length of connection. The sorting is now latest sessions to oldest. If connection is longer than 24 h I suggest we display the exact date

**Comment by tschubotz** [comment]
UX sync:
- iOS designs look good :)
-> next step: Android

**Comment by biocom** [comment]
After reviewing the inVision slides more in-depth, I still would like to have these comments addressed before starting with Android. The comments are available in InVision but here's a summary:

- Should we hide the 'SKIP' button? IMO yes but see the comments > https://projects.invisionapp.com/share/3ER8F3INR48#/screens/354457395/comments/113304533
- The final 'GET STARTED' action button. Should we dive straight into QR code scanning (camera) or first let the user finish the mini on-boarding and see the connection overview list? I made a suggestion in the comments here > https://projects.invisionapp.com/share/3ER8F3INR48#/screens/354630113/comments/113091668
- In the connection overview screen, should we do either of these:
   - Suggest some Dapps to get started.
   - Inform the user that there are no Dapp connections and to add their first Dapp connection by scanning a QR code (could be an immediate action in itself). See comments > https://projects.invisionapp.com/share/3ER8F3INR48#/screens/354630139/comments/113130418
- The notifications banner was suggested to be used also in other screens. Left some comments about it here > https://projects.invisionapp.com/share/3ER8F3INR48#/screens/354630178/comments/113091788

**Comment by tschubotz** [comment]
UX sync:
- Skip -> Lert's remove
- Get start to QR code: -> straight to camera (closing the camera would go to empty list)
- Notifications banner: Let's test this here first and think about other parts later.

**Comment by posthnikova** [comment]
New version: https://invis.io/3ER8F3INR48

What's been done:

- Removed "Skip"
- Get started now leads to QR code scan, closing camera screen opens list of sessions
- Tapping on an item in sessions list opens action sheet, now there's only one option - to disconnect

**Comment by posthnikova** [comment]
New version https://invis.io/3ER8F3INR48

What's been done:
- Added "Connecting" state https://invis.io/3ER8F3INR48#/357848254_08_Sessions_List_Connecting
- Added error alert in case of network error https://invis.io/3ER8F3INR48#/357848302_09_Sessions_List_Network_Error
- Message to enable push notifications is no longer applicable, we don't show system notifications. Transaction request opens review screen immediately

**Comment by DmitryBespalov** [comment]
👍approve

**Comment by biocom** [comment]
@posthnikova Thank you, looks good. Some comments:

- The error for when there's no connection (https://projects.invisionapp.com/share/3ER8F3INR48#/screens/357848302_09_Sessions_List_Network_Error) when would this show exactly? Would this be a different from a general 'No internet connection' banner as discussed in issue #125 ?
- I noticed '23.5 hours ago'. Would it be better to indicate hours + minutes if < 24 hrs? E.g. `23 hours and 30 minutes ago`. It reads more natural and we've got space for it. Which in case we'd also do `11 hours and 13 minutes ago`.

> Message to enable push notifications is no longer applicable
Does that apply to this notification https://projects.invisionapp.com/share/3ER8F3INR48#/screens/354630178 ?

**Comment by posthnikova** [comment]
> Would this be a different from a general 'No internet connection' banner as discussed in issue
>  #125 ? 

This is in line with the proposal in #125 and only shows after user taps Scan. "No internet connection" message shows when the screen opens and after pull to refresh. 

> 23.5 hours ago

Corrected https://invis.io/3ER8F3INR48#/354630565_17_Sessions_List_

> Does that apply to this notification
> https://projects.invisionapp.com/share/3ER8F3INR48#/screens/354630178 ?

We don't have system notifications so I propose this screen https://invis.io/3ER8F3INR48#/359569644_22_Dapp_Closes_Connection

**Comment by biocom** [comment]
As for this screen:
https://invis.io/3ER8F3INR48#/359569644_22_Dapp_Closes_Connection

Given we have quite some space, would it be nice to make the Dapp icon (and maybe title) bigger?

**Comment by lukasschor** [comment]
Agree with @biocom

**Comment by posthnikova** [comment]
I made the icon bigger but I have no text style with bigger font on iOS (except the tagline on launch screen): https://invis.io/3ER8F3INR48#/359569644_22_Dapp_Closes_Connection

**Comment by biocom** [comment]
@posthnikova Looks good, I think that works.

**Comment by biocom** [comment]
Hereby my proposal for WalletConnect on Android:
https://invis.io/S9S72W8FHKE

The screen contain several text/design decisions which slightly differ from iOS. I'd like to highlight these in one of our next meetings.

**Comment by tschubotz** [comment]
Michel update the prototype. 
Looks good for me beside one [minor thing](https://projects.invisionapp.com/share/S9S72W8FHKE#/screens/365283888/comments).

@posthnikova @lukasschor what do you think?

If you are cool with it, we can go through the steps to push it to zeplin and close the ticket.

**Comment by biocom** [comment]
@posthnikova in the tx view, the header section (with the logo) differs. So we need to align that portion.

**Comment by posthnikova** [comment]
I have one comment here https://invis.io/S9S72W8FHKE#/365283888_Send_Review_-Dapp_Request-, other than that it looks good, I have to add missing iOS screens (Dapp without icon etc)

**Comment by posthnikova** [comment]
Added missing screens on iOS with "Unnamed" tag: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5ceead9fbcc3711dbcbb093f 
This needs to complete checklist for closing.

**Comment by biocom** [comment]
Added the Android screens to Zeplin: https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5cf0c5346e245a5d9a6d0ce6

- Checked the text contents and they seem in sync (Android/iOS)
- @lukasschor I matched screen names with Sasha's Zeplin screens. Please review as there are some screens only on iOS and only on Android.

**Comment by biocom** [comment]
Added some screens for Android on Zeplin:
- Connecting state -> https://zpl.io/agkrvMQ
- Re-connecting to a Dapp -> https://zpl.io/bz61n47

**Comment by posthnikova** [comment]
Missing iOS screens:

Initial connecting: https://zpl.io/a3jKvoN
Reconnecting: https://zpl.io/VKjo0r6
