### ISSUE TITLE
Multiple Safes on iOS

### ISSUE THREAD

**Issue by posthnikova** [gnosis/safe#140]

**Comment by posthnikova** [comment]
Project is up for review: https://invis.io/3HQ098MTCPU#/354436623_01_Overview_With_Safe_Name_

I have two versions, the first is with all options on one screen, the second has general settings on separate screen. I tried to avoid double menu android has. 

Editing Safes list is like mail on iOS, there is editing mode where we can remove items but at the same time swipe left also opens editing mode (Edit changes to Done) (https://prnt.sc/n37urx).

Some open questions I have:

When there is only one Safe, do we allow removing it? What happens then? Maybe we show something like this screen? https://invis.io/PYPF44ESJ6X#/336311775_14_SetUpSafeOptions_

When Safe is in the process of creating, do we allow editing or removing it? Do we allow creating a new Safe while another one is already in the process of creating?

**Comment by lukasschor** [comment]
I prefer version 1, as in version 2, very important settings seem to be hidden away behind "General settings". 

> When there is only one Safe, do we allow removing it? What happens then? Maybe we show something like this screen? https://invis.io/PYPF44ESJ6X#/336311775_14_SetUpSafeOptions_

Yes, would allow to remove the safe and show the screen where the user can select/recover a safe. Do we need a warning? Like "Are you sure you want to remove this safe?"

> When Safe is in the process of creating, do we allow editing or removing it?

I would vote for yes, it's only removing it from the UI anyways. Might complicate things if we make an exception for these in-progress safes.

> Do we allow creating a new Safe while another one is already in the process of creating?

Would also vote for yes here.

**Comment by rmeissner** [comment]
I would recommend to create a spec for https://github.com/gnosis/safe/issues/80 (just a placeholder) and add these questions there.

**Comment by tschubotz** [comment]
I also prefer version 1.

> When there is only one Safe, do we allow removing it? What happens then? Maybe we show something like this screen? https://invis.io/PYPF44ESJ6X#/336311775_14_SetUpSafeOptions_

Yes exactly, that screen. Again

> Do we need a warning? Like "Are you sure you want to remove this safe?"

Yes, removing should always ask for confirmation. I think Sasha has that already everywhere in the prototype.

> When Safe is in the process of creating, do we allow editing or removing it?

Removing should be possible, yes. We do the same on Android. 
What won't be possible is changing the recovery phrase and the connection to the Chrome extension. Also WalletConnect doesn't make sense and should not be shown.

> Do we allow creating a new Safe while another one is already in the process of creating?

Yes. 


I saw you removed the options ot change the Safe name and to view the Safe on Etherscan. Did you move them somewhere else?

**Comment by tschubotz** [comment]
UX sync: 
- Let's put "Edit Safe name" and "View on etherscan" back to the main list.
- Let's go with version 1

**Comment by posthnikova** [comment]
New version: https://invis.io/3HQ098MTCPU#/354436052_Divider_

What's been done:

1) Etherscan and editing name moved to the main list: https://invis.io/3HQ098MTCPU#/354436639_02_Menu_Multiple_Safes_

2) "This Safe's settings" renamed to "*custom Safe name*'s settings"

3) When Safe creation is in progress you can edit name, view on Etherscan and remove: https://invis.io/3HQ098MTCPU#/354440832_11_Creating_In_Progress_One_Safe_

4) Added screen when all Safes have been removed from device: https://invis.io/3HQ098MTCPU#/355767365_21_Safe_Removed_

5) When all Safes have been removed you can still access Menu: https://invis.io/3HQ098MTCPU#/355767377_22_Menu_No_Safes_

**Comment by biocom** [comment]
4. I get the idea for the screen, but find the red cross icon to have a negative connotation. I wonder if we should try to have an universal screen where we can cover the scenario of having no Safes setup. That would allow to also consolidate with this screen https://zpl.io/VYKNdpJ . Let's discuss.

**Comment by posthnikova** [comment]
> Let's discuss.

"No Safes added yet. Let's get started." sounds good but the blue checkmark doesn't fit. Maybe a plus icon? 

![Unknown.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/aee36555-817c-4667-aea6-0da54a7e1264)

**Comment by biocom** [comment]
@posthnikova Perfect!

**Comment by posthnikova** [comment]
A couple of changes: https://invis.io/3HQ098MTCPU#/354436052_Divider_

What's been done:

- Safe specific settings section renamed to simply "Settings": https://invis.io/3HQ098MTCPU#/354436639_02_Menu_Multiple_Safes_
- No one had any objections to "Let's get started" screen so I changed it everywhere: https://invis.io/3HQ098MTCPU#/355767365_21_Safe_Removed_

**Comment by posthnikova** [comment]
Changes after user tests are ready: https://invis.io/3HQ098MTCPU#/354436052_Divider_
What's been done:

1) Menu screen: "Settings" renamed to "Safe settings," "Support renamed to "About the app," added new menu item "Contact us." Selected Safe icon and address replaced with menu item "Switch Safes." https://invis.io/3HQ098MTCPU#/363172446_01_Menu_Multiple_Safes

2) List item in the list of Safes goes to Assets view of active Safe. If we tap on another Safe, Safes are switched, the list item goes directly to Assets view. When we return to Switch Safes, the check mark displays over currently active Safe.
https://invis.io/3HQ098MTCPU#/363172447_02_Switch_Safes


3) On Assets view "Add token" renamed to "Manage tokens" https://invis.io/3HQ098MTCPU#/363172448_03_Overview_With_Safe_Name

4) Removal. To remove we still need to enter editing mode or swipe left: https://invis.io/3HQ098MTCPU#/363172450_05_Editing_Mode
Before removing I propose we show this reminder to backup recovery phrase and address: https://invis.io/3HQ098MTCPU#/363172452_07_Backup_Reminder
You can backup address right on this screen: https://invis.io/3HQ098MTCPU#/363172453_08_Backup_Reminder_Address_Copied

5) If this is not the first Safe, we should explain what happened to already existing Safe. Since the onboarding will change I propose we add the explanation to one of these slides:
https://invis.io/38RUAG7NKUD#/361408157_-LUKAS-CHANGE-TITLE--_HW2FA_START
For example, we can add another slide saying: "You can access previously created Safes through the Menu."

**Comment by tschubotz** [comment]
UX sync outcome:
Let's
- Add more details to the text "This removes the Safe from this device" or sth. similar.
- Remove the QR code
- Ask for the recovery phrase to confirm.

**Comment by posthnikova** [comment]
Changes are up for review: https://invis.io/3HQ098MTCPU#/354436052_Divider_

1) Removed qr code and changed wording on backup reminder https://invis.io/3HQ098MTCPU#/363172452_07_Backup_Reminder

2) Added input of recovery phrase to confirm removal https://invis.io/3HQ098MTCPU#/363942435_09_Remove_EnterSeed. Firstly we display screen with backup reminder, the user hits "I have backup" and is asked to enter recovery phrase to proceed. After hitting Remove in the nav bar Safe is removed.

**Comment by posthnikova** [comment]
Can we close this? @tschubotz @lukasschor 

Screens are up on Zeplin: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5cde91cdefa7aa1d3fd06933

Lukas, screen names are needed, I tagged them Unnamed.

**Comment by biocom** [comment]
Some comments:
- Wording needs some work. E.g. 'I have backup' 'Do you have backup'. Provided comments on InVision.
- What happens after tapping on 'I have backup?'

**Comment by lukasschor** [comment]
Some wording change proposals.

https://zpl.io/a31Q1My: "This Safe will be removed from your device. To recover this Safe or to add it to another device you will need the recovery phrase and this Safe's address."

And below: "I have *a* backup"

**Comment by lukasschor** [comment]
@biocom clicking on I have a backup prompts the user to enter the recover phrase. 

One thing I'm not sure about. What happens when the user doesn't have the recovery phrase and wants to delete a "ghost Safe"? Would he need to add ETH to the Safe to perform the Replace recovery phrase action and then delete it? Propably an edge case we don't need to optimize for, but still something we should be aware of.

**Comment by biocom** [comment]
@lukasschor Valid concern indeed.

It's a bit of the chicken and the egg problem. Assuming the user hasn't setup a recovery phrase, deleting the Safe would mean that it becomes irrecoverable/lost (right?).

**The scenarios I see:**
A) User has a recovery phrase for their Safe -> Remove Safe -> Enters their recovery phrase to confirm. User confirmed they are able to recover their Safe anytime.

B) User has no recovery phrase for their Safe -> Remove Safe -> We inform the user that removing this Safe will make it irrecoverable, given they don't have a recovery phrase: 
"Would you like to setup a recovery phrase so you can recover this Safe later?" 
[Yes] -> Brings you to the recovery phrase setup flow. 
[No, just delete] --> Will permanently remove the Safe.

C) User has no recovery phrase for their Safe -> Remove Safe -> Double confirm (fingerprint/password) -> Safe removed permanently.

As you can see scenario C poses a real risk for users who, in theory might understand what they're doing, but in practice are deleting a Safe they perhaps would want to recover later for some reason. 

Scenario B tries to catch that to some extend, but still leaves it up to the user (can be good or bad).

Scenario A takes a more explicit proactive stand in terms of user security where user is forced to have a recovery mechanism for their Safe, otherwise we'd prevent them to remove a Safe they'd permanently have no access for anymore.

**Comment by posthnikova** [comment]
> One thing I'm not sure about. What happens when the user doesn't have the recovery phrase 
> and wants to delete a "ghost Safe"? 

I think we should remind to backup before removal but if the user does not want to backup we should let them remove Safe. 

> The scenarios I see:

Exactly what Michel suggests here in scenario B. So the removal in case of not having backup will look like this: 

![Removal.gif](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/0bcdd1b6-0f5e-4108-8cea-0a3bea5afbba)

**Comment by biocom** [comment]
@posthnikova Thank you for the screens overview, as it provides a good insight in the flow.

In general it looks good to me. two notes:
- After the screen `RemoveSafe (backup reminder confirmation)` we could also ask to provide the user's authentication (fingerprint or password) to double confirm.
- Given this model is based on the scenario B, I'd make sure we all agree that that's the way we want to handle the flow this way.

All in all I think this provides the best balance between convenience and security, with the possibilities we have.

**Comment by lukasschor** [comment]
I like scenario B and @posthnikova 's proposal. I feel this is something we should discuss in the UX sync on Wednesday.

**Comment by posthnikova** [comment]
> we could also ask to provide the user's authentication (fingerprint or password) to double 
> confirm.

Nice, I updated the flow.

![Removal.gif](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/d759b812-aba0-42a4-938c-f5402ba7129d)

Wording changes are on invision https://invis.io/3HQ098MTCPU#/354436052_Divider_

**Comment by posthnikova** [comment]
Changes after UX sync. What's been done:

Skipping recovery phrase is no longer applicable. 

For cases when the user forgot their recovery phrase I added "Lost your recovery phrase?" link on "Enter your recovery phrase" screen https://invis.io/3HQ098MTCPU#/363942435_08_RemoveSafe_-enter_seed- 

This link directs to Replace recovery phrase flow https://invis.io/3HQ098MTCPU#/364764002_09_-Token_Payment-_ReplaceSeed 

When the recovery phrase was entered correctly it disappears https://invis.io/3HQ098MTCPU#/363942566_11_RemoveSafe_-enter_seed_correct-

**Comment by lukasschor** [comment]
@posthnikova Looks great 👍

I also checked the Zeplin screens and the names you have chosen all look good to me (I removed "unnamed" tag as there weren't any changes).

I will upload the screens to Lokalise and then close the ticket. ✅

**Comment by posthnikova** [comment]
👍
