### ISSUE TITLE
Review & align button/text labels for supporting unification of localisation keys

### ISSUE THREAD

**Issue by biocom** [gnosis/safe#141]
@lukasschor is working on the localization keys and has to decide whether to have two separate keys for iOS/android or to align them.

**Comment by biocom** [comment]
@lukasschor I reviewed all the action button/text labels, between Android <-> iOS:

- On some occasions we use slightly different toast descriptions. Do you see the necessity to unify this? Maybe out of scope for this ticket given it's not a button/action.
  - iOS toast example https://zpl.io/2GyAJqd
  - Android example https://zpl.io/aByP18A
- When sending funds on iOS (https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/screen/5c76b39e0e8c876239916206) the main actions is 'Review' whereas on Android (https://zpl.io/bAZR888) it's 'Continue'. Should we unify this by changing 'Continue' to 'Review' for Android?
- On iOS we use 'Delete Entry' (https://zpl.io/2GyG1jY) on Android 'Delete entry' (https://zpl.io/a8ZDyyx). I wonder for these scenarios: The text string is contextually the same. But visually capitalization is used. In other scenarios uppercase (could) be used. Assuming that for the localization key we'd use 'Delete entry' we then could independently decide on iOS/Android to apply capitalisation/uppercase to render. Of course differences should be avoided, but it can happen. @lukasschor What are your thoughts?

**Comment by lukasschor** [comment]
> On some occasions we use slightly different toast descriptions. Do you see the necessity to unify this? Maybe out of scope for this ticket given it's not a button/action.
iOS toast example https://zpl.io/2GyAJqd
Android example https://zpl.io/aByP18A

Yes, toasts should also be aligned as they will be given localisation keys as well 

> When sending funds on iOS (https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/screen/5c76b39e0e8c876239916206) the main actions is 'Review' whereas on Android (https://zpl.io/bAZR888) it's 'Continue'. Should we unify this by changing 'Continue' to 'Review' for Android?

I would vote for aligning both to say "Review".


> On iOS we use 'Delete Entry' (https://zpl.io/2GyG1jY) on Android 'Delete entry' (https://zpl.io/a8ZDyyx). I wonder for these scenarios: The text string is contextually the same. But visually capitalization is used. In other scenarios uppercase (could) be used. Assuming that for the localization key we'd use 'Delete entry' we then could independently decide on iOS/Android to apply capitalisation/uppercase to render. Of course differences should be avoided, but it can happen. @lukasschor What are your thoughts?

Yes of course, if there is platform specific capitalisation conventions, these should be followed over the goal to align. In this case I would vote to use "Delete entry" for both if there is no important reason to have it differ. 
@posthnikova What do you think?

**Comment by posthnikova** [comment]
> @posthnikova What do you think?

Apple has guidelines for titles, buttons and alerts: 
"If the title is a complete sentence, use sentence-style capitalization and appropriate ending punctuation. If the title is a sentence fragment, use title-style capitalization and don’t add ending punctuation." 
So I would follow these.

**Comment by biocom** [comment]
- As for the 'Copied to clipboard' toast, I aligned with iOS given it needs a shorter string there. Updated on Zeplin.
- Updated the text string for the SEND FUNDS views to 'Review'. Example -> https://zpl.io/bAZR888
- As for the 'Delete entry' I updated Android (https://zpl.io/a8ZDyyx) to to align with iOS. Couldn't find any specific guidelines on it for Android, but noticed that some apps use the same defaults.

@lukasschor Are we able to close this ticket, given that moving forward we're working on standardizing our workflow to catch these differences proactively?

**Comment by lukasschor** [comment]
@posthnikova @biocom 

The Zeplin screens are not all according to above specs title-style capitalization for non-sentence titles and buttons.

Some examples:
- zpl.io/bljyX7k ("Setup password" instead of "Setups Password")
- zpl.io/aNPkzKD ("Confirm recovery phrase" instead of "Confirm Recovery Phrase")
- zpl.io/VkG599v ("CONTINUE" instead of "Continue")

I will close this ticket anyways as I will take the changes into account on Lokalise (source of truth for wording) and you can just update the design screens accordingly when you retouch them anyways or if you have some time. :)

**Comment by biocom** [comment]
@lukasschor Just did a quick check on those screens. They are all aligned but perhaps not yet uploaded on Zeplin yet. Will make sure I do an update on all screen currently present on Zeplin.
