### ISSUE TITLE
Remind to turn on push notifications when making a transaction

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe#149]
As a user with connected browser extension but disabled push notifications, 
I want to be reminded to enable required push notifications for the app,
So that I can make transactions with the safe.

## Problem
If user disabled push notifications for the app (either on first start, or any time later) then the app cannot receive incoming push notifications from the browser extension. The incoming notifications are required now so that app receives transaction signatures.

iOS disallows showing system push notification permission dialog more than once if user has already disabled the notifications. Nevertheless, we can detect that state of disabled notifications in the app.

## Alternative solutions considered
1. Remind user with alert on the app start to enable push notifications if they are disabled
2. Remind user with alert on the Review screen when waiting / resending confirmation requests
3. Display a red banner somewhere in the interface saying that the notifications are disabled, and the app has reduced functionality
4. Create a separate communication channel (through our backend service API),  independent of push notifications, and use it to transfer messages between chrome extension and apps.

## Recommendation
I would recommend implementing the #4 in the long term, because it will be more reliable than delivery of push notifications, but for the meantime, I would implement #2 because it is simple.

**Comment by DmitryBespalov** [comment]
Created from gnosis/safe-ios#585

**Comment by tschubotz** [comment]
I agree with Dima. Long term #4 would be nice, but it that won't happen for a while, so #2 seems like the most pragmatic fix: Showing an alert when (1) opening that screen and (2) everytime the user resent the confirmation request. 

I would only trigger that alert, if there is a 2FA device connected. Otherwise we wouldn't need the push permission, right?

**Comment by DmitryBespalov** [comment]
> I would only trigger that alert, if there is a 2FA device connected. Otherwise we wouldn't need the push permission, right?
Yes, that is right.

**Comment by tschubotz** [comment]
Screen can be found at https://zpl.io/agQ0qz9
