### ISSUE TITLE
Remind to turn on push notifications when making a transaction

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#150]
This is iOS only, since we don't need to ask for push permission on Android.

Please refer to the EPIC for more details: #149

**Comment by posthnikova** [comment]
@DmitryBespalov Alert on Review screen:

![Send_Review2FARequired (enable push).png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/caa12423-f4b6-42d5-892e-84bd6b940b2c)

"OK" directs to settings: https://prnt.sc/nd4hki

**Comment by lukasschor** [comment]
"... from *the* browser extension."

**Comment by posthnikova** [comment]
Corrected

![Send_Review2FARequired (enable push).png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/acffeb33-1ce9-4b4e-8b2d-c7b474fb7a0a)

**Comment by lukasschor** [comment]
"OK" will lead the user directly to the Settings app using a deep-link, right? @posthnikova

**Comment by posthnikova** [comment]
> "OK" will lead the user directly to the Settings app using a deep-link, right?

@lukasschor Yes, this leads to settings https://prnt.sc/nd4hki

**Comment by lukasschor** [comment]
Would expect it to say "Settings" instead of "OK", but fine with this implementation, too.

**Comment by DmitryBespalov** [comment]
ok!

**Comment by sche** [comment]
1) I think we can still get the notifications if the app is opened via firebase notifications. But it should be tested before.
2) Soon enough it will be reworked with 2FA feature and push notifications will not be required

**Comment by DmitryBespalov** [comment]
@sche 1) has to be tested, it would be great if that would work
2) I think still we need this thing before we implement the alternative.

**Comment by lukasschor** [comment]
I still think this makes sense to implement even if 1) holds true as there is the use case that the user closes the app / switches to other app while confirming in the browser extension. In this case notification could not be sent using Firebase notifications.

So if there are no objections (@DmitryBespalov @sche @posthnikova), I would say let's upload the screens to Zeplin/Lokalise and close this ticket.

**Comment by posthnikova** [comment]
@lukasschor the screen is on zeplin: zpl.io/agQ0qz9

**Comment by lukasschor** [comment]
@posthnikova Went through the checklist. Looks good and will move this ticket to Dev backlog.

**Comment by tschubotz** [comment]
I'll close this ticket and instead more the epic to the dev backlog. (#149 )
