### ISSUE TITLE
WalletConnect support

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe#151]
# What is this feature about? (1 sentence)
This feature will enable users to use their mobile Safe with desktop dapps by scanning a QR code.

# Why is it needed? What is the value? For whom do we build it?
Currently, most dapps are optimized for desktop whereas mobile wallets become quite popular. The Gnosis safe is also on mobile, primarily. 
[WalletConnect](https://walletconnect.org) solves this by allowing users establish a secure connection between dapp and wallet by scanning a QR code. We think WalletConnect is better than the traditional web3 provider injection since it is wallet-agnostic.
Also, un the future, we would like to support hardware wallets as 2FA devices, i.e. no Chrome extension required. Then we would need a way for the users to still use dapps. 
WalletConnect allows us also to be more independent from Firebase Could messaging.

# High-level overview of the feature
- Users need a way to scan the QR code that the dapp provides.
- This establishes a secure WebSocket connection over which transaction data and signatures are exchanged. Private keys remain on the wallet at all times and are not shared.
- The app receives a push notification when the dapp requests a transaction.
- User is able to see all open connections.
- There can be connections from any Safe to any number of dapps.
- Connections are Safe-specific
- The user needs to be able to close the connection from the Safe.

# Screens
https://docs.google.com/document/d/1LJD7-NuBEKfLbDoiVa0Kcoup5ut7gaX5jmrxfG8I8hw/edit# 

# Other things
- Telegram group for WalletConnect: https://t.me/walletconnect
- Other mobile wallets that have support: TrustWallet, Balance, RainbowWallet (rainbow.me), Tokenary, WallETH
- Also Pedro (Dev for WalletConnect) works out of FullNode right now quite regularly.
- List of wallets and dapps that support WalletConnect: https://docs.google.com/spreadsheets/d/1k63Hfieu88m1DdXHVryElMdcntMMQ1Q4JvJyMEQLADE/edit#gid=0

**Comment by tschubotz** [comment]
I put the remaining task in #257 so we can close this epic and don't have it cluter the dev backlog.
