### ISSUE TITLE
Send device information to notification service

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe#153]
## Story
As a developer of the notification service, I would like to have more information of the devices registered in the service.

## Background
Currently just the **firebase token** and the **ethereum address is** stored for every device
It would be very useful for new functionalities to store information about the device (operating system, version, client), so we can use different logic for every device depending on iOS, Android, Web...
## Acceptance criteria
Device information should be gathered and stored when a device is registered in the service.

The following information are required by the new endpoint:
- Array of signatures (r, s, v) that where generated by the accounts that should be registered
- Firebase push token
- Build number (e.g. 1644)
- Version name (e.g. `1.0.0`)
- Client (e.g. `android`, `ios` or `extension`) 
- Bundle identifier (e.g. `io.gnosis.safe` or `pm.gnosis.heimdall`)

## Technical Details

The new endpoint should be reachable via `/v2/auth/`

To register a new device a POST request needs to be performed.

The payload should be in the following format:
```json
{
  "push_token": "<string>",
  "build_number": "<integer>",
  "version_name": "<string>",
  "client": "[android | ios | extension]",
  "bundle": "<string>",
  "signatures": [
    {
      "v": "<integer>",
      "r": "<stringified int>", 
      "s": "<stringified int>"
    },
  ]
}
```

None of the devices will be update/created if invalid information is provided for one of them.

Each signature is generated by signing the following data:
`sha3("GNO" + <pushToken> + <build_number> + <version_name> + <client> + <bundle>)`

Response would be a list with one element for every owner that signed the tx:
```json
[
{
  "owner": "<checksumed string>", 
  "client": "<string>", 
  "created": "2019-04-23T09:33:55.555388Z",
  "modified": "2019-04-23T09:33:55.607356Z",
  "pushToken": "<string>",
  "buildNumber": "<int>",
  "versionName": "<string>",
  "bundle": "pm.gnosis.heimdall"
}, 
...
]
```

**Comment by DmitryBespalov** [comment]
looks good to me

**Comment by Uxio0** [comment]
Agree

**Comment by Uxio0** [comment]
@DmitryBespalov @rmeissner @sche I have updated the epic with the response of the endpoint
