### ISSUE TITLE
Recovery Phrase Improvements

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe#159]
This includes the following improvements:

1. Numbers associated with the individual words (1 to 12) to better see the order of the words. Add numbers on Onboarding_ShowSeed and Onboarding_EnterSeed

2. Adapt wording of Onboarding_SeedIntro. -> Refer to Usability test results: https://docs.google.com/presentation/d/1RstqD51blqbJFuoUjpqq1PAHHB23KUoXsf9v1_c9czU/edit#slide=id.g4f905da307_0_158

**Comment by posthnikova** [comment]
Project is up for review. What's been done:

1) Changes to onboarding: https://invis.io/FXPSG91SV8B#/361964448_Divider_2

• Onboarding_SeedIntro now has Skip button https://invis.io/FXPSG91SV8B#/361968604_25_Onboarding_SeedIntro. I also put the information on card and changed the water illustration for unification purposes.

• Onboarding_ShowSeed and Onboarding_EnterSeed now have numbers associated with words. I also changed style of word containers to better match our card style.  https://invis.io/FXPSG91SV8B#/361968649_26_Onboarding_ShowSeed
https://invis.io/FXPSG91SV8B#/361968685_27_Onboarding_EnterSeed

2) New menu item "Backup recovery phrase". When it hasn't been visited it features red exclamation icon: https://invis.io/FXPSG91SV8B#/362202660_37_Menu_Multiple_Safes
This leads to backup screen: https://invis.io/FXPSG91SV8B#/362202690_38_BackupSeed. There's short info to remind the user what it's for and the actual recovery phrase. Copying is not allowed. We don't show this menu item when the user has completed backup during onboarding.

3) Reminders if the user has skipped recovery phrase during onboarding.

• Reminder on Assets screen is shown after some funds have been deposited. It's clickable and leads to backup screen, all other content shifts down. There's also cross to close.
https://invis.io/FXPSG91SV8B#/362202908_40_AssetView_BackupSeedReminder

• In the Menu there's more expanded reminder, all other content also shifts down. It has the link to backup screen and cross to close. After you close it doesn't show anymore.
https://invis.io/FXPSG91SV8B#/362202936_41_Menu_BackupSeedReminder

**Comment by posthnikova** [comment]
Changes are up for review: https://invis.io/FXPSG91SV8B#/361964448_Divider_2

What's been done:

1) Backup from the Menu also has "I have a copy" button https://invis.io/FXPSG91SV8B#/362202690_38_BackupSeed

2) Cross on small card with reminder is now centered https://invis.io/FXPSG91SV8B#/362202908_45_AssetView_BackupSeedReminder

3) Circles on error screens are now red https://invis.io/FXPSG91SV8B#/361972953_33_Onboarding_EnterSeed_-filled_Error-

4) Lock icon adjusted https://invis.io/FXPSG91SV8B#/361968604_25_Onboarding_SeedIntro

5) Circles are the same color as border and containers, digits are a little bigger https://invis.io/FXPSG91SV8B#/361968685_27_Onboarding_EnterSeed

6) "Replace recovery phrase" is removed from the Menu when there is backup option

**Comment by lukasschor** [comment]
Looks good to me.

**Comment by lukasschor** [comment]
Open questions about how to safe keys. Will be discussed with Stefan.

**Comment by posthnikova** [comment]
Changes after UX sync:

Skipping is not allowed. 

I shortened the text a bit: https://invis.io/FXPSG91SV8B#/361968604_25_Onboarding_SeedIntro 

Old text: "In the next step you will be shown a 12-word recovery phrase. Use this phrase, together with your Gnosis Safe wallet address, to recover your wallet in case you loose access to it. We recommend using a password manager or writing the phrase down and store the paper-copy in a safe place that only you have access to." New: "Use the phrase on the next screen,  together with your Safe address, to recover your wallet in case you lose access to it.
We recommend using a password manager or writing the phrase down and store the paper-copy in a safe place that only you have access to."

We need android for this.

**Comment by biocom** [comment]
Android proposal:
https://invis.io/XZSDXA5Y48T

**Comment by tschubotz** [comment]
Thanks for the prototype!

Quite some UI things look different now:
- The numbers don't have a grey background
- When a word is wrong, it's not just outlined red.
- When confirming, the words don't have that grey background.

I'll leave you both figure out what's is better, case by case. @biocom @posthnikova 

Only point where I have a strong opinion: When 2 words were wrong, you just ask the user to enter those 2 words again (https://projects.invisionapp.com/d/main#/console/17719742/367391605/preview). I'm against doing that, but instead have the user start from scratch again after tapping "Try again", i.e. leads them to [this screen](https://projects.invisionapp.com/d/main#/console/17719742/367391609/preview) with a new selection of 4 words.

**Comment by biocom** [comment]
@tschubotz Could you elaborate why you think it's better to confirm the 4 words again. Technically if only 2 are wrong, the other 2 are correct? Is there value for the user to confirm those 2 (correct) words again?

**Comment by biocom** [comment]
@tschubotz Also please elaborate on this one:

> When confirming, the words don't have that grey background.


If you can, in the inVision project.

**Comment by tschubotz** [comment]
Re color: scheme: I think the iOS screen should not have the new color scheme, since we will implement this feature there in the old scheme first. iOS currently still has the simple "2 word confirmation flow", which is why that is more urgent.

**Comment by biocom** [comment]
@tschubotz Updated to reflect your feedback:
https://invis.io/XZSDXA5Y48T

Also discussed/verified with @posthnikova - I guess some small adjustments needed for the iOS based on it?

**Comment by posthnikova** [comment]
Looks good to me. iOS needs to change the appearance of tapped rectangles.

**Comment by posthnikova** [comment]
Changes to iOS are up on zeplin https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c767b99c36416627a138d67

**Comment by tschubotz** [comment]
👍

**Comment by tschubotz** [comment]
Can be moved to Design - Done once Android is on Zeplin.

**Comment by biocom** [comment]
Android screens on Zeplin:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5d025ee268714a15d2b693e8

Moved it to a separate section on Zeplin so we can preserve the flow with the old colors meanwhile.
