### ISSUE TITLE
New Color Scheme

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe#162]
Adapt all screens according to the new colour scheme. Maybe a separate Zeplin project is needed in parallel to the existing screens. See below for details.

![Colors_1.png](https://images.zenhubusercontent.com/5c2f27248332e72a247d8f53/be86d3f9-9ab3-430d-8ab3-99567f583990)
![Colors_2.png](https://images.zenhubusercontent.com/5c2f27248332e72a247d8f53/2e934520-8a0c-4561-93d5-2cb02bdc9193)
![Colors_3.png](https://images.zenhubusercontent.com/5c2f27248332e72a247d8f53/e2d5ddaf-0026-4a58-9137-06cef64b7676)
![Colors_4.png](https://images.zenhubusercontent.com/5c2f27248332e72a247d8f53/e26d6e6a-fae8-4294-ba66-999f1d692d80)
![Colors_5.png](https://images.zenhubusercontent.com/5c2f27248332e72a247d8f53/75b99f9a-04fb-4333-822c-ad9a52b7cb11)
![Colors_6.png](https://images.zenhubusercontent.com/5c2f27248332e72a247d8f53/37171013-dff6-4a8a-a6c9-19b09b5c9579)
![Colors_7.png](https://images.zenhubusercontent.com/5c2f27248332e72a247d8f53/95699580-1f68-4812-8059-06f3dd380e54)
![Colors_8.png](https://images.zenhubusercontent.com/5c2f27248332e72a247d8f53/a688ce01-2a68-4e64-ae9a-b5d473f5f023)
![Colors_9.png](https://images.zenhubusercontent.com/5c2f27248332e72a247d8f53/edeec14f-c742-41d0-9c2b-58565cda09f2)

**Comment by lukasschor** [comment]
New Slogan: "The most secure way to manage your crypto funds"

**Comment by posthnikova** [comment]
Android screens are on zeplin: https://zpl.io/be4JLXN
