### ISSUE TITLE
Display fiat balances

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#177]
- Users should be able to see the fiat value of their assets.
- Users should be able to select their reference currency.

Please see the Epic for further details.

**Comment by posthnikova** [comment]
https://invis.io/PEPL75H7ZV6 
The simplest way is to display fiat values on overview screen (with our without total). Currency can be set in the menu. 

We can also display fiat in transactions list and transaction details, on Send and Review tx screens.

**Comment by tschubotz** [comment]
Thanks for the proposal.

The total value seems a bit lost to be honest. But I don't have a good idea for improvement. So it should work I think. I think we should display the total. :)

Why do you display the `$` in front of the value? I checked Trust and Coinbase. They both do it after the value. Also for USD I prefer `US$` since `$` is used in quite some other currencies as well. e.g. Canadian Dollar.

The decimal separator is a dot for the token balances but a comma for the fiat value. That should be in sync ;)

As for displaying the value in other places, I would only display it on the asset screen for now. This saves us to worry about other screens and we can see if users want to have it on other screens at all.

**Comment by posthnikova** [comment]
> Why do you display the $ in front of the value?

@tschubotz How come Coinbase and Trust do it after the value? http://joxi.net/n2YdWz7tbKWXEm http://joxi.net/8AnzM0DHzvMboA Maybe it depends on your region?

> The decimal separator is a dot for the token balances but a comma for the fiat value.

It's not supposed to be a decimal separator

**Comment by tschubotz** [comment]
> @tschubotz How come Coinbase and Trust do it after the value? http://joxi.net/n2YdWz7tbKWXEm http://joxi.net/8AnzM0DHzvMboA Maybe it depends on your region?

I think you are right, that depends on the locale! :) https://developer.apple.com/documentation/foundation/numberformatter/style/currency 
Then I would use that when implementing it.

> It's not supposed to be a decimal separator

I saw this wrong, my bad.

I'm fine with the design.

**Comment by posthnikova** [comment]
> The total value seems a bit lost to be honest. But I don't have a good idea for improvement

@tschubotz I don't really like it when they are displayed one below another. There are multiple ways we could change the header, just some examples:
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/ac301b68-7b62-4543-a7d3-2618a4847329)

**Comment by tschubotz** [comment]
I don't like the first one where you would have to swipe since Then I wouldn't see the value right away.

I actually like option 2 a lot since all values would be on the right side then.
![image](https://user-images.githubusercontent.com/1380529/65976213-161d4d80-e470-11e9-95ce-617aa8480fe4.png)

What's you favorite?

**Comment by posthnikova** [comment]
> What's you favorite?

2 and 4

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/0759fe78-3a08-49e3-bb9c-76463902f357)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/6b8472a7-6546-42a4-bcd9-eb414f9840f4)

**Comment by posthnikova** [comment]
Final designs: 
Android: https://invis.io/5JQJD5ZX7MF

iOS: https://invis.io/PEPL75H7ZV6

**Comment by DmitryBespalov** [comment]
:thumbsup:

**Comment by KristinaMayman** [comment]
Looks good to me.

**Comment by tschubotz** [comment]
Does this have Zeplin links @posthnikova ?

**Comment by posthnikova** [comment]
@tschubotz This is affected by WalletConnect issue, therefore in progress

**Comment by tschubotz** [comment]
Closing this for now since we de-prioritized the feature.
