### ISSUE TITLE
Improve recovery phrase recovery

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#180]
# What is this feature about? (1 sentence)
This feature will make the recovery process easier and more streamlined.

# Why is it needed? What is the value? For whom do we build it?
- It looks like we won't have any advance recovery options soon. 
- Even if, we will continue to have recovery phrases as an option
:point_right: we should improve the existing flow a bit.

# High-level overview of the feature
(1)
- When entering a recovery phrase, we could give the user options for words based on their entered letters. Words are unique by their first 4 letters. 
- We could let the user know in case they entered a word that does not occur in the word list.
- We should let the user know if they have entered more or less than exactly 12 words.
- The user input of the recovery phrase should be lowercased, automatically.

(2)
- We let the user enter their recovery phrase first and then give them a list of Safes connected to that, so they can select which one to recover. -> So they don't have to enter the address anymore. This requires backend work, but should be doable.

**Comment by tschubotz** [comment]
We should also auto lower case the input.

**Comment by tschubotz** [comment]
Also, would be great if the user doesn't need to remember the Safe address.

**Comment by DmitryBespalov** [comment]
I like these improvements! 👍
