### ISSUE TITLE
Menu "Get in Touch" Section

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe#181]
## Status Quo
Currently, we have a section in the Menu called "Give Feedback" which opens an Email in the default mobile email client.

#### New Section title
This section should be renamed to "Get In Touch"

#### New Screen
Taping on the section "Get In Touch" should open a new screenview that contains three options and might be able to get extended in the future. The options include:
1. Telegram
Taping would deep-link to the t.me/GnosisSafe Telegram Group or to the Telegram App Store page, depending on whether the user has Telegram installed or not
2. Email
Taping would perform the same action as the current "Give Feedback" option in the Menu -> Open a new e-Mail in the default mobile e-Mail client
3. Gitter
Taping would open the website https://gitter.im/gnosis

**Comment by posthnikova** [comment]
Menu item "Get In Touch" directs to this screen https://invis.io/3HQ098MTCPU#/365910686_GetInTouch

**Comment by biocom** [comment]
Android version up for review on inVision: https://invis.io/NBSAPPJ37K4

**Comment by tschubotz** [comment]
Looks good to me 👍 
Once @lukasschor gives thumbs-up, we can also upload to zeplin move the ticket to done :)

**Comment by lukasschor** [comment]
Looks good to me 👍

**Comment by posthnikova** [comment]
Menu (token payment, no multiple Safes): https://zpl.io/2G939L3
Menu (with token payment and multiple Safes): https://zpl.io/bzqeBwG
Get In Touch: https://zpl.io/2ERmX6x

**Comment by biocom** [comment]
Android Zeplin (production) screens:
Settings: https://zpl.io/VYAlyZe
Get in touch: https://zpl.io/2pM083o
