### ISSUE TITLE
Send Max

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe#184]
# What is this feature about? (1 sentence)
This feature will enable users to automatically input the maximum available balance when sending funds by taping a designated button.

# Why is it needed? What is the value? For whom do we build it?
If a user wants to send all remaining funds of ETH or a certain token he/she would have to manually type in the remaining balance, which could potentially have multiple decimal places. Furthermore the user would have to take the gas fee into account. To make this process easier, we want to have an easy way to automatically fill out the sending amount to the maximum available amount. This will likely be a button that, when taped, will automatically pre-fill the amount field in the Send_Input screen.

# High-level overview of the feature

Taping the "Send Max" button would automatically input the maximum balance available for the token/ETH.

# Screens 

https://docs.google.com/document/d/1Vf9F7NYjQRwATjsNUurP9EaV5_PolteVvd0NqmZQMQk/edit#heading=h.5k9764wfcbkh

**Comment by tschubotz** [comment]
@lukasschor in our Safe sync on Monday, June 3 we discussed with Stefan that it is the easiest to go with a simple solution without any approximation, i.e. upon tapping "Send Max", the max amount is put into the field.
- If the payment token is another one 👉  no problem.
- If the payment token is the same 👉 Then the user sees that they have to lower the amount since the fees would be too much.

This way we load off the problem of approximation to the user while it's still clear for the user what is happening. 
We keep the implementation overhead low on our end.

**Comment by lukasschor** [comment]
Sounds good to me.

**Comment by sche** [comment]
Related to this issue:
One thing I don't like about how our estimations work now is that it is always a different number. One example of funds transfer:
1) We estimate when we change address or amount value.
2) We re-estimate when we enter confirm transaction screen.

I think this is not good from UX perspective that a user can always see a different number in some fraction of digits.
If we could make just one estimate with some TTL, it would simplify UX behavior and would allow implementing send max feature in a good way.

What we could do is to always estimate for max token balance transfer once, and then to use this estimation without re-estimating.
The similar approach could be used for other use cases when we need to estimate.

**Comment by lukasschor** [comment]
@rmeissner what do you think of @sche 's suggestion? Wouldn't this mean that the user would essentially over-pay for all non-max amounts?

**Comment by rmeissner** [comment]
hmm not really (we would maybe show a too high of a fee, but that one is not really accurate anyways)

concerning the TTL, you can only estimate once and submit this to service at a later point, currently it is pretty unlikely that it will change soo much, that the service doesn't accept the tx.

**Comment by sche** [comment]
I think we had an issue before, with low estimations. But if it not an issue anymore, I would offer to estimate only once everywhere.
In this case, Send Max will not trigger re-estimation and everything will feel smooth.
