### ISSUE TITLE
Send Max

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe#185]
### Why
If a user wants to send all remaining funds of ETH or a certain token he/she would have to manually type in the remaining balance, which could potentially have multiple decimal places. Furthermore the user would have to take the gas fee into account.

### What
To make this process easier, we want to have an easy way to automatically fill out the sending amount to the maximum available amount. This will likely be a button that, when taped, will automatically pre-fill the amount field in the Send_Input screen.

**Comment by posthnikova** [comment]
Here are the versions I have

https://invis.io/FBPH0OFQ57P#/365931563_Send_Input_Copy
https://invis.io/FBPH0OFQ57P#/365931659_Send_Input_Copy_2
https://invis.io/FBPH0OFQ57P#/365931685_Send_Input_Copy_3
https://invis.io/FBPH0OFQ57P#/365931748_Send_Input_Copy_4

**Comment by tschubotz** [comment]
I like version one because of the following reasons:
- On version 2 "Eth" is not tappable, "MAX" is which I don't find ideal.
- I think we have enough vertical real estate on that screen, so we could put the button outside. That's why I don't favor version 2-4.

**Comment by posthnikova** [comment]
It depends on the device, on small screens there would be scroll

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/78114632-3870-4ba1-b37f-4a6e9d9fa820)

**Comment by posthnikova** [comment]
Small wording change: https://invis.io/FBPH0OFQ57P#/365931563_Send_Input_Copy

Also I've shown error state: https://invis.io/FBPH0OFQ57P#/366377693_Send_Input_-max_Amount_Error-

**Comment by biocom** [comment]
Android version up on inVision for review:
https://invis.io/Q8SAOROWT9Y

**Comment by tschubotz** [comment]
I like the wording change.

Screens are good to go from my side :)

**Comment by lukasschor** [comment]
Looks good to me 👍
Moving this to Design Done column for the checklist to be completed.

**Comment by lukasschor** [comment]
Looks good to me 👍
Moving this to Design Done column for the checklist to be completed.

**Comment by lukasschor** [comment]
Looks good to me 👍
Moving this to Design Done column for the checklist to be completed.

**Comment by posthnikova** [comment]
Screens on zeplin:

https://zpl.io/2y6kNey
https://zpl.io/aMpdr0z (errors)

**Comment by biocom** [comment]
Screens on Zeplin for Android:
https://zpl.io/VqY1y7Z
https://zpl.io/aRzmMnz
