### ISSUE TITLE
Fix scrolling behavior on mobile website for iOS devices

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe#187]
**Problem:**
On iOS in Chrome/Safari/Firefox scrolling behavior is weird. It stops right after you release the finger, makes it a little bit difficult to scroll (instead of 1 scroll with default behavior you have to do 3-4)
I also tested it on Android (Chrome) and it works fine.

[vid.zip](https://github.com/gnosis/safe/files/3231592/vid.zip)

**Comment by tschubotz** [comment]
This was fixed with the website update :)
