### ISSUE TITLE
Offer users to personalise safe address

### ISSUE THREAD

**Issue by sche** [gnosis/safe#19]
When creating a Safe user can have an option to personalise the safe address.
Like I want my safe address to start with 0x777555...
This is a good candidate for A/B test.
We could make it as a freemium option (N chars for free, and then you can buy it with an in-app purchase depending on the desired length up to M)

**Comment by tschubotz** [comment]
I'm not sure if that's the right way to go. We should try to get rid of wallet address as much as possible actually. Identicons and more importantly ENS integration are in my opinion better options.

**Comment by fmrsabino** [comment]
Technically how would you do that? The address is based on the random signatures negotiated between the client and service + nonce. Seems unfeasible technically.

**Comment by sche** [comment]
Technically server would need to make random computations while generating second part of the signature (like miners do).

**Comment by sche** [comment]
@tschubotz I agree that ENS integration is more important for personalization. Generating an identicon that is similar to some image could be also an option.
In general, from my past game dev experience, I can tell that personalization is very important for many  users and they are ready to pay for that (win/win imo.) So I would A/B test personalization ideas.
