### ISSUE TITLE
Improve camera screens

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#190]
See #189 for details

**Comment by posthnikova** [comment]
My proposal is to use darker overlay with hints and close button so they are visible on any background: https://invis.io/Y2Q7D0T6KNG#/370583817_Scan_1. 

Alternatively, we could use Cancel button: https://invis.io/Y2Q7D0T6KNG#/370583847_Scan_2. 

For inline errors I tried something like this http://joxi.net/GrqYEe6f465y3r but there are problems with readability. So I propose we stick with our existing errors. Although I would change error message. "Error pairing device" isn't fit for cases when we want to send funds. This is an existing error message for pairing with 2FA: https://invis.io/Y2Q7D0T6KNG#/370591962_Scan_Error_Pairing. I propose to show another error message for scanning recipients QR code: https://invis.io/Y2Q7D0T6KNG#/370592064_Scan_Error_Send

**Comment by lukasschor** [comment]
I would go with the X rather than the "cancel" button.

The indicator where the QR code should go and the pop-up error look good to me.

**Comment by biocom** [comment]
@posthnikova Thank you for the screens.

I was curious if we also should explore something around showing instructions. Right now in your proposal we have hints. But I meant something like:
<img width="342" alt="Screenshot 2019-06-25 at 16 22 25" src="https://user-images.githubusercontent.com/31534717/60106664-e5899180-9765-11e9-8b58-f12abf060d54.png">


Judging from the screenshot above, it looks like the step before you actually go scan something. On Android I've seen a similar screen, with instructions:
<img width="342" alt="Screenshot 2019-06-25 at 16 24 39" src="https://user-images.githubusercontent.com/31534717/60106682-e91d1880-9765-11e9-83bc-c0d18fe56bc9.png">


Specifically the top banner. The inline 'GOT IT' I find less relevant.

Let me know your thoughts.

**Comment by rmeissner** [comment]
I would add an inline message that tells the user what he is supposed to scan (e.g. WalletConnect QR code or Ethereum address QR code). This provides more information what kind of QR code is expected, especially in error case where we stay on the camera screen (e.g invalid or broken QR code).

**Comment by tschubotz** [comment]
- I like that there is an indication on the camera screen, where the QR code should go, even when we check the entire camera view for codes. Somehow feels nicer that way.
- I would prefer some inline info message as well, that tells the user (again) what to scan.
- I'm a fan of the x as well. I guess everyone knows the meaning.
- I would prefer the error messages for invalid QR codes on the camera screen as well (like Sasha proposed). That would mean that we need to change a bit the implementation though, I think.

**Comment by posthnikova** [comment]
New version is up for review. I added instructions and errors are on camera screen now. You have to tap "Retry" to scan again. 

Scan 2FA: https://invis.io/Y2Q7D0T6KNG#/370856807_Scan_2FA
Scan WalletConnect: https://invis.io/Y2Q7D0T6KNG#/370856856_Scan_WalletConnect
Scan Send: https://invis.io/Y2Q7D0T6KNG#/370857007_Scan_Send 
On android close button is not needed since there is < system button. Android will look something like this: http://joxi.net/p27RGLeiK5lZJm

Scan 2FA Error: https://invis.io/Y2Q7D0T6KNG#/370857028_Scan_2FA_Error
Scan WalletConnect Error: https://invis.io/Y2Q7D0T6KNG#/370857116_Scan_WalletConnect_Error
Scan Send Error: https://invis.io/Y2Q7D0T6KNG#/370857149_Scan_Send_Error

> I would go with the X rather than the "cancel" button.

> I'm a fan of the x as well. I guess everyone knows the meaning.

@lukasschor @tschubotz Cool, I prefer cross too because it's hard not to notice. 

> I was curious if we also should explore something around showing instructions

> I would add an inline message that tells the user what he is supposed to scan

@biocom @rmeissner I'm fine with instructions as long as there would be no "Got it" button.

**Comment by rmeissner** [comment]
@posthnikova I like the inline message, can we show the error inline too? For me the retry button is not really required.

**Comment by posthnikova** [comment]
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/34bb1724-94be-41f4-9517-19490a2a6e58)

@rmeissner I thought about it. That means the error would persist while the user makes another attempt. Let's imagine the user scanned an invalid code, got this error and attempts to scan the same code again. For them the screen would just look frozen. I don't feel like it's the behaviour we need. I think we should give feedback after each attempt.

**Comment by lukasschor** [comment]
I agree with Sasha about the error state. Having an overlay error and requiring a user action to retry feels (to me at least) like reseting the camera. While with an inline error we would need to balance the time the error is displayed to be long enough so the user can read it but short enough so the user is not confused when doing a second attempt. Having the error just stick there until a successful scan is made is even more confusing.

**Comment by rmeissner** [comment]
yeah I know what you mean, and we can implement it with a dialog, I just don't understand the argument "you need less steps then when you would show the error on the previous screen" 😛 

For android the snackbar could provide this temporary display of an error (we use this kind of error display all over the place and it works)

**Comment by tschubotz** [comment]
- I like the new instructions, added 2 wording comments on invision
- http://joxi.net/p27RGLeiK5lZJm doesn't seem to load for me right now, the site appears to be down 🤔 

> That means the error would persist while the user makes another attempt

I agree with Sasha, inline error might not be the best. Only if they would disappear after some time. So basically similar to a snack bar on Android. I like the error alerts, too though.

**Comment by posthnikova** [comment]
Snack bar which disappears after some time works for android. On iOS we don't have such UI pattern so we would have to create some new UI element. The closest to this is Rinkeby warning and "No internet connection" banner but there's only one line of text. Alternatively, we stick to existing error alerts. 

> the site appears to be down

It was this image:
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/95e29fca-969e-4afd-a804-84de8ce99801)

**Comment by posthnikova** [comment]
@rmeissner @tschubotz @lukasschor After discussing on UX sync we decided to show alerts on camera screen both on iOS and Android. I know Richard has objections but there is a risk that the user doesn't have time to read the error text on snackbar properly. We should let the user read the error text carefully. 

Scan 2FA: https://invis.io/Y2Q7D0T6KNG#/370856807_Scan_2FA
Scan WalletConnect: https://invis.io/Y2Q7D0T6KNG#/370856856_Scan_WalletConnect
Scan Send: https://invis.io/Y2Q7D0T6KNG#/370857007_Scan_Send

Scan 2FA Error: https://invis.io/Y2Q7D0T6KNG#/370857028_Scan_2FA_Error
Scan WalletConnect Error: https://invis.io/Y2Q7D0T6KNG#/370857116_Scan_WalletConnect_Error
Scan Send Error: https://invis.io/Y2Q7D0T6KNG#/370857149_Scan_Send_Error

Android will look something like this: 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/fcff2088-d46c-4230-a0ee-0d5812ebf4d4)
