### ISSUE TITLE
Info screen & block brave users

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#192]
See epic

**Comment by posthnikova** [comment]
Here is the info screen.

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/59557535-f59f-40f1-8ef0-beb69548a612)

**Comment by tschubotz** [comment]
I like it. It's easy and simple. You thoughts @lukasschor @biocom?

**Comment by biocom** [comment]
Looks good. Couple of comments:
- Change title to "Oops! **Brave** is not supported" to make it specific from the start.
- Also we could emphasise in the description: "....Please get the latest version of Chrome and download and install the extension again."

**Comment by posthnikova** [comment]
> Change title to "Oops! Brave is not supported"

@biocom Corrected

> "....Please get the latest version of Chrome and download and install the extension again."

You don't normally download extensions so I just changed description to "Gnosis Safe browser extension doesn’t work with Brave. Please get the latest version of Google Chrome and install the extension again."

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/0be94cf2-5173-4e8a-8cd9-d1bdd29b674a)

**Comment by lukasschor** [comment]
Looks good.

**Comment by posthnikova** [comment]
Screen is up on zeplin: https://zpl.io/bL5PEmD

**Comment by tschubotz** [comment]
Merci. Closing the ticket cc @lukasschor
