### ISSUE TITLE
Improve browser extension

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#197]
# What is this feature about? (1 sentence)
This will resolve some UX issues that users have encountered using the current version of the Chrome extension

# Why is it needed? What is the value? For whom do we build it?
There are some (hopefully!) easy to fix UX issues with the current Chrome extension that we regularly notice as support requests. The main one is the scanning of wrong QR codes.

# High-level overview of the feature
- Remove the QR codes to download from the stores since it's confusing some users. Let's keep the links to the stores though.
  - We cannot show the pairing qr code right away since it has an expiry time encoded in it. So it has to stay behind a button. But perhaps we can still show that there will be a QR code? Perhaps it's blurry and becomes sharp on clicking "show QR code"?
- Remove the QR code on the main screen after having set up a Safe it's confusing and why would anyone scan that.
  - Let's keep the identicon, the address and the link to etherscan though.
- Make it more obvious how to add a second Safe.
- When the extension is locked, a user has to (1) confirm a tx (2) unlock (3) confirm again. Step 3 could be kicked out.
- **Trigger a reload of the page whenever the user whitelists/blacklists a page.** <- not yet implemented
- Remove the slow.trade ad.
- Hide "Extension setup succesfully!" message when the pairing qr-code is displayed and there are Safes that were created previously. Only show that message when the user configures the extension for the first time.
  - Add a back button to that screen when a Safe exists already.
- Add a "back" button to the unlock screen

**Comment by posthnikova** [comment]
@tschubotz Remove double confirmation here? https://zpl.io/aR1A8Wv

**Comment by germartinez** [comment]
Hide "Extension setup succesfully" message when the pairing qr-code is displayed and there are Safes that were created previously. Only show that message if the user is going to connect the first Safe.

**Comment by germartinez** [comment]
Add a "back" button to the screen where the qr-code for doing the pairing is displayed.

**Comment by DmitryBespalov** [comment]
When I confirm the transaction in the extension, but the extension is locked, I have to press "confirm" again after unlocking -> I expect it to confirm automatically after I unlock, because I already pressed confirm button.

**Comment by DmitryBespalov** [comment]
Develop a more robust communication channel between app and extension so that (sometimes) unreliable push notifications are only a 2nd preferred channel.

**Comment by DmitryBespalov** [comment]
Add extension name or extension label to both app and extension - so that the user can distinguish between extension instances. Problem is that it is confusing / hard to know if your extension was reinstalled but whether it is an owner of the safe it is showing. The same with app - we should add a check on startup, for example, that the device is still the owner of the safe. If not - display the error message and optional explanation what to do next to fix it for the user

Alternative: sync extension store between all extension instances within a Chrome user account.

**Comment by sche** [comment]
Don't allow to confirm transactions initiated by browser extension with payment token when the balance is not enough.

**Comment by sche** [comment]
Decrease Resend confirmation request timer time

**Comment by germartinez** [comment]
Show a message in the transaction screen when a 422 error is received from the service instead of just showing the retry button
