### ISSUE TITLE
Allow users to configure transaction speed / gas prices

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#199]
# What is this feature about? (1 sentence)
This will allow users to select the desired transaction speed or to manually set the gas price for a transaction.

# Why is it needed? What is the value? For whom do we build it?
Transactions on Ethereum require network fees to be paid in gas. There are transactions that should go through fast. For others it doesn't matter if they go through in 30s or 3h as long as they go through eventually. We currently don't allow the users to select the used gas price. There are use cases where we should allow users to do so.

# High-level overview of the feature
- tbd

This feature sounds easier than it is, backend wise. The relay service has a limited number of accounts that submit transactions. These transactions have nonces which define the order. A "fast" transaction with nonce `x+1` will always have to wait for a "slow" transaction with nonce `x`. 
We would have to spend some time on how to make this work. It's quite complex.

**Comment by sche** [comment]
We could offer some price tiers (like <1 min, 5 min, >3 min) and to use different payment accounts per tier.

**Comment by tschubotz** [comment]
Relevant article: https://medium.com/authereum/gas-spectrum-transactions-bd34b65107b
