### ISSUE TITLE
Auto display tokens with balance on assets view

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#201]
# What is this feature about? (1 sentence)
This feature will automatically show tokens if they have a balance great than 0 without the need for the user to enable them.

# Why is it needed? What is the value? For whom do we build it?
Currently, users have to go to settings in order to show specific tokens. Some users where expecting them to show up automatically.

# High-level overview of the feature
- Tokens who's balance goes from 0 to some balance >0, are automatically enabled.
- Users can manually hide them. Then the app would remember that choice for this specific token. That choice should be remembered until either the user enables the token or the balance goes back to 0.
  - i.e. if it afterwards increases to >0 again, the token is auto-enabled again. 
- Users can still manually show / hide all tokens.

**Comment by Georgi87** [comment]
> That choice should be remembered until either the user enables the token or the balance goes back to 0.

I would just keep this setting until the user is enabling the token OR receiving funds for this token again.
