### ISSUE TITLE
Non-zero balances are displayed as zero

### ISSUE THREAD

**Issue by sche** [gnosis/safe#202]
I think it's worth to improve balancer formatting when displaying close to zero values.

![IMG_2334](https://user-images.githubusercontent.com/2284385/59599594-3a426200-90ff-11e9-821e-ac6f3887d31b.jpg)

**Comment by tschubotz** [comment]
How would you improve it?
`< 0.0001 ETH` ?

**Comment by sche** [comment]
`~ 0 ETH` e.g.
