### ISSUE TITLE
Fee Payment Method in Safe Settings

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe#209]
In the current Android/Chrome Extension implementations, the fee payment method can be changed in the global Settings. On the Chrome Extension, we probably should not change this, but on Android we should consider moving it the Safe Specific Menu and have the settings also be individually set for each Safe.

Find the current designs here: https://github.com/gnosis/safe/blob/master/specs/token_payment/03_settings.rst

**Comment by posthnikova** [comment]
Fee payment method is now in Safe-specific settings.

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/6981d1ea-66c5-48da-ab28-1aa063d81b15)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/66a50ac6-7eea-4294-8e70-478ae7bfb808)

**Comment by posthnikova** [comment]
Settings are on zeplin: https://zpl.io/VYAlyZe, https://zpl.io/VYrQNjd
