### ISSUE TITLE
Add / remove custom tokens

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#21]
## Story 
As an advanced user I am able to add and remove custom tokens in order to be flexible integrating the Safe with new token projects.

## Background / details
* Currently, a user can only enable/disable tokens from our predefined list.
* We don't have the option to manually add / remove custom tokens.
* Quite some users were asking for that feature.
* We should let users know that this is an advanced feature and they should know what they are doing.

**Comment by tschubotz** [comment]
We decided to not put that feature into the clients right now. Instead, projects should reach out to us and we can add them to our list so their token is available for all users.

**Comment by superern** [comment]
> We decided to not put that feature into the clients right now. Instead, projects should reach out to us and we can add them to our list so their token is available for all users.

Hi @tschubotz where do we send a request to add our custom verified token?

**Comment by tschubotz** [comment]
This ticket is a good place. 

Alternatively, you can always reach out via Telegram: https://t.me/gnosisSafe

We would need the token address as well as a high-res image of the icon, ideally as vector graphic.

**Comment by Zeerocode** [comment]
okay i will send a message to you to add the custom token of our project

**Comment by iulianivg** [comment]
> We decided to not put that feature into the clients right now. Instead, projects should reach out to us and we can add them to our list so their token is available for all users.

literally can't see USDC on Polygon and few other assets (DAI, WMATIC, USDT) because of this **very poor** design choice in your app. Make it so users can choose their token lists.
