### ISSUE TITLE
Decode transaction details for ERC20 functions

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#211]
# What is this feature about? (1 sentence)
This feature will show more details for transactions beyond just cryptic bytes, for ERC20 actions.

# Why is it needed? What is the value? For whom do we build it?
Any transactions doing contract interaction contains a data payload. We currently don't show the user what is happening. We should start with ERC20 token transfers, approves etc.

# High-level overview of the feature
- Decode ERC20 `approve`
- Decode ERC20 `transfer`

**Comment by rmeissner** [comment]
Some data collected by @tschubotz https://docs.google.com/spreadsheets/d/1DZcLwr36n7zNf5-dOi-XDjSDWvZzv4XR89AMOo0kS7Q/edit#gid=479764049
