### ISSUE TITLE
Allow to recover safes created not via our relay service

### ISSUE THREAD

**Issue by sche** [gnosis/safe#212]
# What is this feature about? (1 sentence)
Allow users to recover Safes created without the help of our relay service.

# Why is it needed? What is the value? For whom do we build it?
If some users create their safe with the help of some cli, or some alternative client not using our relay service, we can not recover it in our apps.
It would be good to allow everyone to migrate to gnosis safe easily.

# High-level overview of the feature
- 

# Screens
-

# Other things
-

**Comment by tschubotz** [comment]
- This feature could be quite complex in case the owner/threshold set up of the Safe is not 4/2 with a recovery phrase, i.e. it might be necessary to ask for more than 1 confirmation.
- If a Safe has the exact same properties like we expect, then this wouldn't be an issue.
- I wonder how many users create their Safe manually though.
👉 moving this to `not now`
