### ISSUE TITLE
OWL for onboarding users to the Safe

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#219]
# What is this feature about? (1 sentence)
This feature will grant users an amount of OWL if they successfully onboard new users to the Gnosis Safe.

# Why is it needed? What is the value? For whom do we build it?
This is a growth hacking feature. Users can send invite links to the Gnosis Safe. Once the new user successfully deployed their new Safe, the inviter gets an amount of OWL sent to their Safe. OWL can be spent on tx fees.

# High-level overview of the feature
- tbd

**Comment by Uxio0** [comment]
I like this idea. It will be an evolution of this issue https://github.com/gnosis/safe-relay-service/issues/64
