### ISSUE TITLE
Add support of iOS universal links and Android App Links

### ISSUE THREAD

**Issue by sche** [gnosis/safe#223]
# What is this feature about? (1 sentence)
This allows opening links like https://safe.gnosis.io/<smth> directly in Gnosis Safe app.

# Why is it needed? What is the value? For whom do we build it?
This feature may simplify some flows for users. One of the use cases is better integration with WalletConnect. See the related discussion here https://github.com/gnosis/safe-ios/issues/904

# High-level overview of the feature
-

# Screens
-

# Other things
-

**Comment by rmeissner** [comment]
should we also implement deeplinks for normal transactions while we are on it? (currently we only have deeplinks for wallet connect)

**Comment by sche** [comment]
We could make it as part of this epic or as a new epic. Is there a known standard for such deep links @rmeissner?

**Comment by rmeissner** [comment]
Yes, see https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md

**Comment by tschubotz** [comment]
Linking #233
