### ISSUE TITLE
"Approved by Gnosis" Smart Contracts

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe#224]
# What is this feature about? (1 sentence)
As a user I want to see whether a smart contract I'm interacting with is legitimate so that I don't have to worry about fraud.

# Why is it needed? What is the value? For whom do we build it?
There is a lack of transparency when interacting with smart contracts, while signing messages, etc. Especially, less technical users might be put off by the risks involved.

# High-level overview of the feature
- Have a whitelist of approved smart contracts
- Show the user if he is interacting with an approved contract

# Screens
-

# Other things
-

**Comment by tschubotz** [comment]
This feature could potentially be combined with #211
