### ISSUE TITLE
New App Store / Play Store Preview Images

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe#229]
As part of the rebranding,​ we also need to have new app store preview images. 

#### Align the content with the new Gnosis Safe Landing Page:
Primary Message: The most secure way to manage your crypto funds
Secondary Message 1: Secure by Design
Secondary Message 2: Crypto without the hassle
Secondary Message 3: You are in control

**Comment by posthnikova** [comment]
Sketches of how the app will look in stores. App store desktop:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/a7e0734b-bdc0-4995-b29e-e507af0ab30a)

App store mobile:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/0bf0482f-22f6-46fb-af10-82a1216ffa19)

App store mobile - search results:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/03b30107-537f-4ef2-8192-73cc17485def)

Google play desktop:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/3eb9e722-f76b-4a03-84bc-28debd95f9b6)

Google play mobile:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/f62dd1e9-d884-4d55-b7f3-efc1ed3f9e06)

Search results on google play mobile only display app icons.

**Comment by tschubotz** [comment]
Really shiny screens. I think they'll become my new desktop background :)

Here are my thoughts:
- I like that you just used the basic screens.
- I would swap the screenshots use for "Crypto without the hassle" and "You are in control". I think to "without the hassle" fits the payment method selection better. And to "You are in control" the screen where you send funds.
- Please update the list of payment tokens to reflect the real state, i.e. ETH, DAI, GEN, KNC, MKR, OWL and WETH can be used. If that list is too long, just mentioning ETH, OWL and DAI would be fine too. It specifically important that GNO doesn't show up, from a legal perspective we cannot do that ;)
- I wonder if we should mention on the screens somewhere that it's for Ethereum. On the other hand side we mention it in the app description. What do you think?
- I would replace OMG for DAI sind that's what actually right now a lot of users use with the Safe.
- I would use bigger numbers for the assets stored, we are aiming for big portfolios. What do you think about the following:
  - 1320.23641 ETH
  - 3000 GNO
  - 1753.54 OWL
  - 14,155.46 DAI
  - (numbers are absolutely random, but those are the size I would work with.)

**Comment by lukasschor** [comment]
I like it a lot.

How about using the WalletConnect Sessionlist screen for the "Crypto without the hassle"?

For "You are in contol" I would then use
- Either the Feepayment list (used right now)
- Or the Send screen with tooltip "Change fee payment method"

**Comment by posthnikova** [comment]
> I think to "without the hassle" fits the payment method selection better

@tschubotz Agreed

> Please update the list of payment tokens to reflect the real state

Ok

> I wonder if we should mention on the screens somewhere that it's for Ethereum

It won't hurt if someone installs our app by mistake, hoping it to support bitcoin. At least we'll have an install. And on screenshots it's visible that there is no bitcoin there. 

> use bigger numbers for the assets stored

Ok

> How about using the WalletConnect Sessionlist screen

@lukasschor Wouldn't using other apps logos here cause problems with copyright? If not, we can add individual screenshot for WalletConnect (we can have up to 10 on iOS and up to 8 on Android). 

I propose: 
1 - "The most secure way to store your crypto funds" - Assets view
2 - "Secure by design" - Connect Authenticator screen
3 - "Crypto without the hassle" - Select payment method screen
4 - "You are in control" - Send screen with tooltip "Tap here to change fee payment method"
5 - "Connect to Dapps" - WalletConnect sessions screen

**Comment by lukasschor** [comment]
I don't think it's a copyright issue acutally. As it is screens that are actually possible in the app. I would just make sure it has  sessions that are possible. Here's a list of supported Dapps: https://walletconnect.org/apps

**Comment by tschubotz** [comment]
I just realised, there is the Chrome webstore as well: https://chrome.google.com/webstore/detail/gnosis-safe-smart-wallet/iecodoenhaghdlpodmhooppdhjhmibde?hl=en

So far we just used a handful of screenshots here. I would simply do the same again with the rebranding. What do you think?

**Comment by posthnikova** [comment]
@tschubotz I have it on my task list but didn't get to it yet. On the actual extension page screenshots are fine. It would be ideal to put them over the new Safe website. 

This thumbnail in search results could be better http://joxi.net/DmBJaEeHJQN0km.

**Comment by posthnikova** [comment]
Google play images are ready. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/5ff31bf4-245f-42d9-8abb-367569b749e2)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/2c6b3160-d3c2-4cb0-a8c5-ea7fb6e2b475)

Full size images are here: https://drive.google.com/drive/u/1/folders/1ORBz7PGisrqBYa5GhpIAgBjmYYr_1wyN

**Comment by lukasschor** [comment]
Sorry for not clarifying when sending you the link to https://walletconnect.org/apps. Only the apps listed under the "Dapps" section should be displayed in the WalletConnect session list. Apps that are under "Wallets" are just other wallets besides the Gnosis Safe that support WalletConnect, but it is not possible to set up sessions with these.

So the ones I would display are:
- Balance
- Zerion
- LocalEthereum
- DDEX
- Bamboo Relay
- 1inch Exchange

(As discussed, Heroes of Ether is not really our target group and should not be displayed)

**Comment by posthnikova** [comment]
@lukasschor Corrected

Android: https://drive.google.com/drive/u/1/folders/1ORBz7PGisrqBYa5GhpIAgBjmYYr_1wyN

iOS: https://drive.google.com/drive/u/1/folders/1z4PYghhrI84oHxxvjihb2bMDRjH-ykS8

Chrome web store will be later

**Comment by tschubotz** [comment]
I like the images, specifically, the use of the tool tip ("Tap to change payment token) is a cool idea.

**Comment by posthnikova** [comment]
Sketches for Chrome webstore are up for review: https://drive.google.com/drive/u/1/folders/1a-x9oAtX2s1Mui731TqnLu3nsWbwO2DF. As I put them on a website background they will be ready when website is finished. 

Search results:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/325f0b0a-7cb3-4758-8159-f9b011ff4ed3)

Extension page: 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/303faa6c-bb38-42b1-bcac-562286a8e832)

**Comment by lukasschor** [comment]
I like the Authenticator Webstore images a lot 👍

**Comment by tschubotz** [comment]
Same, I'm so looking forward to releasing it soon :)

> And I need Rinkeby logo to update Rinkeby version.

@posthnikova Is that something that Lea needs to provide and you are waiting for her?

**Comment by posthnikova** [comment]
> Is that something that Lea needs to provide and you are waiting for her?

@tschubotz Yes, I asked her to provide it. Is there already an approved Rinkeby logo?

**Comment by posthnikova** [comment]
All assets for stores are done, new logos are on zeplin. 

App store (mainnet & rinkeby): https://drive.google.com/drive/u/1/folders/1z4PYghhrI84oHxxvjihb2bMDRjH-ykS8

Google play (mainnet & rinkeby): https://drive.google.com/drive/u/1/folders/1ORBz7PGisrqBYa5GhpIAgBjmYYr_1wyN

Chrome webstore (mainnet & rinkeby): https://drive.google.com/drive/u/1/folders/1a-x9oAtX2s1Mui731TqnLu3nsWbwO2DF

Logos for https://sites.google.com/gnosis.pm/safe/developer?pli=1&authuser=1: https://drive.google.com/drive/u/1/folders/1NZB2pi4GO0tCLw1A5sGmuu6bVNoUwHdJ
