### ISSUE TITLE
Display human-readable text for data transactions on safe contracts

### ISSUE THREAD

**Issue by sche** [gnosis/safe#235]
# What is this feature about? (1 sentence)
When personal safe executes some other data transactions that are sent to other safe contracts, it would be good to have a human-readable text what does the transactions do.

# Why is it needed? What is the value? For whom do we build it?
E.g. when interacting with team safe and confirming transactions with personal safe, the transactions that are displayed in personal safe are not informative.

# High-level overview of the feature
It would be good to create a library that could be used both on iOS and Android (GECO grants could be a nice option for this) that provides a human-readable text output for safe contracts operations and other popular ERCs like ERC-1155.

# Screens
- Link to Google docs with screens. Template can be found on [Google drive](https://drive.google.com/drive/u/0/folders/1d7LH762wUBCSf2Shmb-f2O5OdAaQcOAW)

# Other things
-

**Comment by tschubotz** [comment]
linking #211

**Comment by tschubotz** [comment]
closing this due to #211
