### ISSUE TITLE
Rate app prompt after first token payment

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#236]
Please see Epic for details

**Comment by posthnikova** [comment]
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/8ba880dd-c042-4656-bdb5-4f76e24009b4)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/131664d2-56c4-4257-9486-dfd0f48b7e85)

The link directs to App store/Google play

**Comment by tschubotz** [comment]
👍 looks good from my end

**Comment by posthnikova** [comment]
Android: https://zpl.io/VK6XGz8

iOS: https://zpl.io/b6BXNLd
