### ISSUE TITLE
Tell users how to add custom tokens

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#237]
Please see Epic for details.

**Comment by posthnikova** [comment]
###iOS
End of list:
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/551a3b9c-495a-4aa2-bbf6-7342c04094bf)
Short list:
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/f32dee19-f6ab-430c-b73b-78dba2ec5840)
No results:
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/637693a8-d05c-4754-9318-d1130b7630bd)

###Android
End of list:
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/b21366f5-d686-4b57-bf2b-0c1cc827f423)
Short list:
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/d3f56728-e4be-473d-8b02-cd513245516d)
Nothing found:
![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/6a6ba2b0-62bd-4d5c-9bd2-9c28b3db5f24)

**Comment by tschubotz** [comment]
I like it! That tooltip, would it go away also when the user starts to scroll? Or do they have to click the "x"?

**Comment by posthnikova** [comment]
> I like it! That tooltip, would it go away also when the user starts to scroll? Or do they have 
> to click the "x"?

@tschubotz I'm not sure if you can scroll with just one token. You have to tap to close.

**Comment by tschubotz** [comment]
> You have to tap to close.

Where? Tap anywhere on the screen?

**Comment by posthnikova** [comment]
@tschubotz Anywhere outside the tooltip or on the cross

**Comment by posthnikova** [comment]
Screens are on zeplin. 

iOS: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c518a759c3e07307bfee601 

Android: https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c7678b1d391d651e702a727
