### ISSUE TITLE
Recovery flow improvements

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#238]
Please see Epic for details.

**Comment by posthnikova** [comment]
Prototype is here: https://invis.io/RGQEV7F8KDJ
Input field has prompts which update as you type. You can only choose words from the list. We don't let type more than 12 words but you can delete and start over. When recovery phrase is correct we show "address found" and Next button becomes active. In case of multiple Safes found (very unlikely case) we show a list on the next screen. 

Do we start suggesting words after you type the first letter? My concern is that it shows all the words which begin with this letter. And this is too much because there are 2000 words in total. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/cdc965ad-dd77-4c07-8d9b-0ac42a813aa3)

**Comment by posthnikova** [comment]
UX sync:
-try horisontal scroll
-keep Next button
-add loading state

**Comment by posthnikova** [comment]
Some changes after UX sync: https://invis.io/RGQEV7F8KDJ

What's been done:

- there's horizontal scroll in the input field. When the field is full, the cursor is always aligned to the right and entered words are hiding on the left. This solves space issues on small screens. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/1ea8ee39-757f-488d-855a-5c4a3e65981f)

- Start to search for words after typing 1 letter

- added Loading state when typing: https://invis.io/RGQEV7F8KDJ#/386380454_Recover_EnterSeed_-loading-_

- Keyboard is fully functional so we let users type words that are not in list and any symbols. When a word is not in list the error is "Incorrect word". Added error when typing symbols other than a-z: https://invis.io/RGQEV7F8KDJ#/386369718_Recover_EnterSeed_-invalid_Symbols-_

- When the user attempts to type after 12 words were entered don't input new symbols and show error: https://invis.io/RGQEV7F8KDJ#/385435704_Recover_EnterSeed_-error-_

**Comment by tschubotz** [comment]
I like it.

Regarding the error messages: Currently, we have "Invalid symbols" and "Invalid word". How about instead telling the user what exactly is the problem, i.e. why they see an error. So instead say "Only letters a-z allowed" and "Word not part of the word list"?
I like "Recovery phrase cannot be more than 12 words" (There we also don't write "Invalid number of words ;) )

What do you think?

**Comment by tschubotz** [comment]
> People might not know that the words we suggest are from some predefined list. What they are entering essentially is an incorrect word

Hm. Also true. I guess the only way to resolve that would be to link to an article/FAQ explaining the concept of word lists. That's overkill though. Okay, then let's leave "Invalid word" 👍

**Comment by posthnikova** [comment]
Android: https://invis.io/4BRKCD773FS

**Comment by tschubotz** [comment]
I think this looks good.
Is there a screen for when 12 words have been entered but no address could be found?

**Comment by posthnikova** [comment]
UX sync: add error state

**Comment by posthnikova** [comment]
Some changes after comments on Invision. Android: https://invis.io/4BRKCD773FS

iOS: https://invis.io/RGQEV7F8KDJ

**Comment by posthnikova** [comment]
Screens are on zeplin. 

iOS: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5dc57e0572759958823b94b5

Android: https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5dc58456d96acd836f8bbf31

**Comment by tschubotz** [comment]
added to lokalise
