### ISSUE TITLE
Reveal password option in passwords field

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#242]
# What is this feature about? (1 sentence)
This feature will allow users to show the password in passwords fields.

# Why is it needed? What is the value? For whom do we build it?
Especially when there are long passwords, it can get annoying when users do a typo as they have to start from scratch and are not sure where the error is.
Other apps allow users to toggle the clear text on password fields.

# High-level overview of the feature
- There is a toggle next to the pw input that shows/hides the password on tap.

# Screens
- iOS: https://projects.invisionapp.com/share/PYPF44ESJ6X#/screens
- Android: https://projects.invisionapp.com/share/UDQF6KQB54V#/screens

**Comment by DmitryBespalov** [comment]
@posthnikova please provide the following assets (as pdf, both should fit in the rectangle with same dimensions, for example, 22x19):
![Screenshot 2019-11-23 at 12.54.42.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/ae1b8866-71b4-47dc-8eb7-7f0ddb931e22)
![Screenshot 2019-11-23 at 12.54.47.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/65a6ba98-3acb-447e-a18f-81f98c8db3b1)
