### ISSUE TITLE
Improve onboarding: Reduce friction setting app password

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#245]
# What is this feature about? (1 sentence)
This feature will allow users to complete the onboarding faster by reducing the friction during the step to set up an app password.

# Why is it needed? What is the value? For whom do we build it?
Setting up you Gnosis Safe is hard and takes a while. Users need to 
- Choose a password.
- have Crypto 
  - The payment disrupts the flow since other app is required
- Backup their recovery phrase backup

Some of the steps could be made optional but are still required later on for security reasons.

- We would like to increase the percentage of users completing onboarding.
- We would like to make onboarding faster for users.

That's important so more users actually can give us feedback on the actual app. Onboarding prevents most users to do so right now.

It seems like there are 3 steps where most users drop off: (1) setting a password (44% of users lost at that stage), (2) crypto payment (additionally 21% of users lost), (3) recovery phrase and payment selection (9% of users lost)

![Screenshot 2019-12-05 at 17 30 00](https://user-images.githubusercontent.com/284056/70254136-e0088c80-1784-11ea-9f06-045eaefddc87.png)

- Improving the set password step is a lower hanging fruit and an earlier step in the funnel.
- In order for users to pass the crypto payment step, we could pay them Safes, however they would still need to do something with their crypto. We need to explore what that and/or create that use cases (e.g. via dappcon tickets or s.th. similar. So we'll evaluate this for the next milestone afterwards.

# High-level overview of the feature
- tbd
- Have less restrictions in how password is set.

# Misc
Originally, this epic was called "Improve onboarding (Make it faster 🏎)". There are several things we could improve. Some considerations:
![image.png](https://images.zenhubusercontent.com/57add4fee40e5714b16d4969/126c8527-e692-4eb3-97d5-d95f6b8366f2)

**Comment by sche** [comment]
@tschubotz we have #243 issue. Do you think it solves "Reduce friction setting app password"? Or should we find a completely new way like using 4 to 6 digits e.g.?

**Comment by DmitryBespalov** [comment]
**Password**
- I think integration with a password manager is a must, we had been asked for this several times 😄 
- I'm in for a PIN 📌 - it will simplify the setup (only digits, simple digit keyboard, and 6 pins)
  - technical note: for enhanced security, we still can generate a strong password from a PIN using PBKDF2.
- Still, I'd add PW manager integration, even for a pin. 🔒 

This is iOS's PIN screen:

![IMG_2767](https://user-images.githubusercontent.com/284056/70255356-f0216b80-1786-11ea-920d-349f972b119c.PNG)

This is Deutsche Bank's PIN screen:

![IMG_2850](https://user-images.githubusercontent.com/284056/70256814-7179fd80-1789-11ea-9204-3a6e20308757.PNG)

This is Tinkoff Bank's (Russian bank) PIN screen:

![IMG_7932FAFA8182-1](https://user-images.githubusercontent.com/284056/70256128-36c39580-1788-11ea-9b30-13bd14fc5cd9.jpeg)

**Comment by DmitryBespalov** [comment]
Thoughts on removing password setup completely on iOS - it is possible:
- If the device passcode is set then we can use it instead of the in-app password. 
  - This eliminates set-up password and built-in unlock screen, as well as 'unlock' to sign
  - The downside is that if the passcode will be switched off, then we'll have to set up the password on the next app start because it becomes unprotected.
- If the passcode is not set then fall back to the password set up.
- If the biometry is enrolled (touch id or face id), then the lock/unlock becomes trivial.

**Comment by DmitryBespalov** [comment]
Plus, deferring setting a password to later point in time - after installing the safe - make sense imo.
