### ISSUE TITLE
Easier confirmation of transactions

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe#25]
## Problem
Currently the user always has to type his password (if he doesn't have fingerprint) to confirm a transaction. This is quite cumbersome if you have multiple transactions in a row (e.g. slow.trade).

## Solution
The user should be able to define an "safe" time during which it is not required to type the password again. 

Another solution would be that the user can specify a PIN that can be used to confirm transactions while the app is unlocked (e.g. on Android, not in background for more than 5 minutes).

**Comment by sche** [comment]
Note: on iOS we have a session time when a user doesn't require to authenticate.

**Comment by rmeissner** [comment]
Please check this with @tschubotz again, as our current specification state that the user always has to enter his password (or use biometric features)
