### ISSUE TITLE
Tangem ETH card as 2FA device

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#252]
# What is this feature about? (1 sentence)
This feature will enable users to use a Tangem ETH card as 2FA device

# Why is it needed? What is the value? For whom do we build it?
We support the Status keycard already. Tangem does this cheaper and is a bit easier to use. Also it's their main business and not just a side business.

# High-level overview of the feature
- Users can choose Tagem ETH cards as 2FA device

**Comment by DmitryBespalov** [comment]
[22.11.2019] Update: currently, the Tangem iOS SDK is still in the early alpha stage. It is raw.

The supported functionality is sufficient for making the card work with the Safe app: we can get the card Ethereum address, and we can also sign a transaction with the card.  The caveat is that it requires to wait for 10-15 seconds to actually sign it. 

To reduce the waiting period to ~1 second, the card needs to be configured or used with a PIN, but the SDK does not implement this functionality yet. 

The NFC seems to work better than with the Keycard.

**Comment by DmitryBespalov** [comment]
The flows are much simpler than with the Keycard - you only need to scan the Tangem card, activation and PIN are not needed. 

For activation, it'd take holding card for 1-2 seconds, and signing would take holding card for 10-12 seconds.

## Pairing Flow
Setup2FADeviceList ➡️ 🆕 **Tangem_Intro** ➡️ Tap Start ➡️ Scan NFC card (hold card for ~2 seconds) ➡️ 🆕 **Tangem_Success**

If an error occurs, we show it in the pop-up and user can tap Start again.

## Signing Flow
Send_Review2FARequired ➡️ Tap Start ➡️ Scan NFC card (hold card for 10-12 seconds) ➡️ Tap Submit

If an error occurs, we show it in the pup-up and allow to retry (same as Keycard)

## New Screens
- Tangem_Intro
  - Pair your Tangem card
  - Hold the card to the phone for 3 seconds to pair the card.
- NFC scanning can be done on the Tangem_Intro screen
- Tangem_Success
  - Tangem card successfully paired
  - After finishing the Safe setup, you will need to hold the Tangem card to your phone to confirm each transaction. You can replace or remove your 2FA device in the Safe menu at any time.
