### ISSUE TITLE
Prevent Authenticator as 2FA option for new Safes

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#253]
# What is this feature about? (1 sentence)
This feature will prevent users to connect the Authenticator as 2FA device. 

# Why is it needed? What is the value? For whom do we build it?
- Users complain regularly about the reliability of the Authenticator
- We are focussing on WalletConnect for dapps interaction
- Hence we should not allow new users to connect the Authenticator.
- Existing 2FA connections shouldn't be touched.

# High-level overview of the feature
- Don't allow to connect Authenticator during Safe creation
   - So if the phone doesn't have NFC, then no 2FA is possible. Open question: Do we skip this step then or let the user know?
- Don't allow to replace 2FA to the Authenticator (Same open question as above)
- Still allow selecting Authenticator during recovery.
  - Needed since some users use the Authenticator for dapps and if they switch devices, they wouldn't have a way to get their funds out if the dapp doesn't support WalletConnect.
- Remove Authenticator support completely once there is an interface (MyCrypt/MEW?) that allows arbitrary contract interactions and WalletConnect #258

**Comment by tschubotz** [comment]
How do we approach this?
- Don't allow to connect during Safe creation
   - So if the phone doesn't have NFC, then no 2FA is possible.
- Don't allow to replace
- Still allow during recovery.
- See after MyCrypto (or another interface) has WalletConnect support.

**Comment by tschubotz** [comment]
Should we put in an info in the extension that it'll be deprecated soon?

**Comment by germartinez** [comment]
> Should we put in an info in the extension that it'll be deprecated soon?

That looks good to me

**Comment by rmeissner** [comment]
I would still display the user that he could use the Status KeyCard (or other 2fa in the future) if he would use a different phone (or turn on his NFC). Also this avoids some complexity (on android at least)

**Comment by tschubotz** [comment]
Kick off meeting notes: https://docs.google.com/document/d/1mhXG9EY_Gi_E_v8AV5fg_WPfTxi8fWGWQq4v2Dx3Tkg/edit#

**Comment by sche** [comment]
@tschubotz 
> Needed since some users use the Authenticator for dapps and if they switch devices, they wouldn't have a way to get their funds out if the dapp doesn't support WalletConnect

We have a support channel for that and we could ask them to download prev. versions of the app from TestFlight or an apk file from github.
I would be for the complete removal of Authenticator. What do you think?

**Comment by rmeissner** [comment]
Just to clearify ´Remove Authenticator support completely` means that you cannot add the chrome extension to the Safe, but the existing Safes that have been setup with a chrome extension will still work.

**Comment by rmeissner** [comment]
@sche could you provide some details why you are for a complete removal of the Authenticator? 

Another note on that topic, Ben immediately complained that he cannot interact with some dapps after he switched to the KeyCard and switched back. While I know this is just a single case, I just wanted to point out that we have this example already in our company so it might not be an edge case.

**Comment by sche** [comment]
Yes, old users will be able to use it.
I think UX wise to show everyone Authenticator during recovery, but not to show during new Safe flow is inconsistent. For edge cases like with Ben there is a workaround with older apps versions.

**Comment by tschubotz** [comment]
I'm still a bit hesitant. Just consider what happens after updating their Safe to 1.1.1. The old builds don't support this master copy. So then they are in trouble.
