### ISSUE TITLE
Universal scan button: Step 1 - Make WalletConnect more prominent

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#254]
# What is this feature about? (1 sentence)
This feature will make it more obvious how to use WalletConnect.

# Why is it needed? What is the value? For whom do we build it?
- WalletConnect is currently in the settings.
- Apparently, some users don't find it.

# High-level overview of the feature
- Add a scan button as FAB to the main screen as a first step.

# Screens
See Zeplin or links in https://github.com/gnosis/safe/issues/255#issuecomment-561128367

# Misc
- Metamask or Trustwallet can be looked at for an example of this.
- In a next step, users should be able to scan recipient addresses with the scan button as well.

**Comment by tschubotz** [comment]
Kick off meeting notes: https://docs.google.com/document/d/1WM09JrD417_6RinmDh0SYMtw1f_GGhHaLbca8buV2c8/edit#heading=h.il5khvo9jrqc

**Comment by rmeissner** [comment]
What happens to the WalletConnect explainer screens when clicking the scan button (assuming the user did not see them yet)?

**Comment by DmitryBespalov** [comment]
> What happens to the WalletConnect explainer screens when clicking the scan button (assuming the user did not see them yet)?

We show them, as it is with the wallet connect opened from the menu.
