### ISSUE TITLE
Improve Status Keycard integration

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#259]
# What is this feature about? (1 sentence)
This will improve the UX of the existing Status keycard integration.

# Why is it needed? What is the value? For whom do we build it?
Some things are hard to use.

# High-level overview of the feature
- Allow choosing the PIN of the card.
- Let people know when NFC is turned off.
- Prevent NFC card from opening status website/app when in Safe app or pairing flow.
- TODO: UX test to see if those are the problems.

**Comment by DmitryBespalov** [comment]
On iOS, iPhone X can open Safe app for NDEF - I'd like to add this

**Comment by DmitryBespalov** [comment]
Proposed new screen: "Choose PIN" (Similar to "Change Password" or even "PIN and Pairing Password")
- "Enter PIN" field
- "Confirm new PIN" field
- Next / Back button

## Flow
Enter PIN & Password Screen ➡️ 
Tap "I don't have Password" ➡️ 
🆕 **Choose Pin screen** ➡️ 
Backup card credentials screen ➡️
Tap "I have a copy" ➡️
Scan to activate

**Comment by DmitryBespalov** [comment]
Next steps from the UX workshop:
- RE-evaluate if we're going to put more effort in the Keycard support.
- Adjust the wording of the Keycard instructions to match the instructions in the Keycard package
- Add more information about the card - more clear instructions.
- When setting up the card, first is the "initialization" flow, the "I already have the PIN and password" should be a secondary flow
- Record the instructional video for setting up the card
  - Write a scenario and storyboards
  - Record the video
  - Process the video and optimize for mobile viewing
  - Add the video instructions in the app
- Do we want to try branded Gnosis Keycards?
- Allow the user to set their own PIN; Add confirmation screen for the entered credentials.
- Use only digits for the pairing password. Can break digits into 4-digit groups separated with spaces: `1234 5678 9101` - then ignore spaces in the pairing password input field.

**Comment by DmitryBespalov** [comment]
* experiment with PIN-less path

**Comment by DmitryBespalov** [comment]
I propose the following changes based on the comments above:

* New "Save Pairing Password" and "Confirm Pairing Password" screens to make sure the user wrote down the password correctly.
* New "Enter PIN" and "Confirm PIN" screens to make sure the user sets the pin correctly. 
* Add the switch to "Remember the PIN for future use" to the "Enter PIN" screen. Add the "Remember Keycard PIN" switch to the menu - when off, the PIN will be requested on card usage.
* Change the "Activation" screen to show the pairing password and pin that was set. 

![StatusKeycard_Mockup 001](https://user-images.githubusercontent.com/284056/71814510-e7b99a80-307c-11ea-93bf-cdd595b6c5d1.png)
