### ISSUE TITLE
Contract upgrade to 1.1.0 & enable fallback manager

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#262]
# What is this feature about? (1 sentence)
This feature will allow users to upgrade their Safe to 1.1.0.

# Why is it needed? What is the value? For whom do we build it?
This contract upgrade allows ERC1155 and NFT support.

# High-level overview of the feature
- It should be possible to upgrade from any previously supported Gnosis Safe version.
- The upgrade + enabling of the fallback manager should happen in 1 tx for the user.

**Comment by rmeissner** [comment]
This should include that we use the new creation process (new proxy factory with new master copy)

**Comment by tschubotz** [comment]
Kick off meetings notes: https://docs.google.com/document/d/1DmEMzP5IXT4GjQ-5moTuMaPyTMY_gdIffiFZPHUtko8/edit#
