### ISSUE TITLE
Contract update intro screen update

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#263]
There will be another contract update (see epic)

The main user-facing feature added will be the support for NFTs (ERC721) and ERC1155 (Those can be fungible or non-fungible).

I think it's best to update/replace the 1 screen where we say something about formal verification since that was only done for the 1.0.0 contracts.

**Comment by posthnikova** [comment]
iOS: https://invis.io/F7SG8PLDU9P

What's been done:

1) The text "Security update required" changed

2) New Assets screen with fiat and WalletConnect button

3) Card in the Menu changed: new text

4) Onboarding1 changed: new illustration and text

**Comment by posthnikova** [comment]
Changes after meeting (https://docs.google.com/document/d/1DmEMzP5IXT4GjQ-5moTuMaPyTMY_gdIffiFZPHUtko8/edit#). What's been done: small text changes and removed fiat values. 

iOS: https://invis.io/F7SG8PLDU9P

Android: https://invis.io/DVT3SYCZK4A

**Comment by DmitryBespalov** [comment]
good

**Comment by tschubotz** [comment]
Thanks for the update. Looks good from my end as well.

**Comment by elgatovital** [comment]
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/d06b7ea8-a8f3-4995-9704-c6628a7c2993)

**Comment by posthnikova** [comment]
@elgatovital The whole banner is clickable. The banner persists until the user upgrades contract so I think the text is fine.

**Comment by DmitryBespalov** [comment]
@posthnikova I will need the info icon ℹ️ asset, and "diamonds" icon asset exported as pdf

**Comment by tschubotz** [comment]
@posthnikova are these screens already in Zeplin?

**Comment by posthnikova** [comment]
@tschubotz Yes

@DmitryBespalov iOS: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5d42b8a374c7212be17e0826

Android: https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5d42b7d3959bdc2bdbec1565
