### ISSUE TITLE
Users expect to have Safe access after changing the phone.

### ISSUE THREAD

**Issue by sche** [gnosis/safe#267]
He got several support requests when users don't understand why they can't use Safe on their new phone. This is because we do not sync Safe phone's private key with iCloud. Taking into account that we are having these requests on a small number of users, there will be many more requests on a larger amount. That's why I think we should revisit our "Private key never leaves the device" principle.
I am for
- better communicating this principle to our users
- giving them a choice

How about showing our users a screen where they can choose if they want to synchronize their key with iCloud/Google Cloud Storage, or if they want to follow the "Private key never leaves the device" principle? If a user does not want to sync, we can explain, that when restoring from iCloud/Google Cloud Storage backup, they would need to use the Safe recovery option.

**Comment by Uxio0** [comment]
If they have another device as 2FA I don't see like a big issue to give the users the choice to have the private key in the cloud
