### ISSUE TITLE
Use same lib between planforms for generating identicons

### ISSUE THREAD

**Issue by sche** [gnosis/safe#27]
Identicons should look the same between platforms.

**Comment by rmeissner** [comment]
@DmitryBespalov Do we have different indeticons on iOS? If so could we fix this.

**Comment by rmeissner** [comment]
I would close this issue since this should already be the case

**Comment by DmitryBespalov** [comment]
@rmeissner no, it wasn't fixed.

**Comment by fmrsabino** [comment]
It's not about using the same lib in my opinion but implementing it in the same way. I'd say this is an iOS issue no? @DmitryBespalov 

Kotlin implementation: https://github.com/gnosis/svalinn-kotlin/blob/master/blockies/src/main/java/pm/gnosis/blockies/Blockies.kt

**Comment by DmitryBespalov** [comment]
@fmrsabino this is an issue of different blockies implementation, in this case, it's iOS only.

**Comment by rmeissner** [comment]
Android and chrome extension generate the same blockies as metamask and etherscan. Therefore I would say we should fix this rather soon, to avoid uaer confusion. I would ooen a bug issue in the ios repo for that.

**Comment by DmitryBespalov** [comment]
I'll handle that
