### ISSUE TITLE
Support batch transactions

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#271]
Please see epic for details.

We need to think about:
- How do we let the user know that a transaction contains mulitple ones?
- Can they examine the single transcations in detail?

**Comment by posthnikova** [comment]
Designs for iOS: https://invis.io/3ER8F3INR48

What's been done:
- Review screen with 2FA required https://invis.io/3ER8F3INR48#/396680655_Send_Review2FARequired_-Batch-_
- List of individual transactions https://invis.io/3ER8F3INR48#/396680648_Batched_Transactions_List_
- Review screen when there are 0 transactions https://invis.io/3ER8F3INR48#/396680652_Send_Review2FARequired_-Batch_-_0_Transactions-_
- Insufficient funds https://invis.io/3ER8F3INR48#/396680654_Send_Review2FARequired_-Batch_-_Insufficient_Funds-_
- 2FA confirmed
- Review screen without 2FA
- Overview transactions
- Transaction details (success, pending, failed)

**Comment by elgatovital** [comment]
batched transaction with 0 transactions inside looks confusing

**Comment by posthnikova** [comment]
Small text changes and Android. 

iOS: https://invis.io/3ER8F3INR48

Android: https://invis.io/TWS723THG6N 

> batched transaction with 0 transactions inside looks confusing

@elgatovital Could you please elaborate on what is confusing? The phrase "0 transactions inside"?

**Comment by posthnikova** [comment]
UX sync:
This performs 3 transactions.

**Comment by posthnikova** [comment]
Zeplin:

iOS: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5df266d345b55fa54d3a400c

https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5df265e8eb30dcaf81561282
