### ISSUE TITLE
Universal scan button: Step 2 - Allow scanning of recipient addresses

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#272]
# What is this feature about? (1 sentence)
This feature will allow users to scan ethereum address QR codes with the universal scan button.

# Why is it needed? What is the value? For whom do we build it?
- With #254 we added a universal scan button.
- It currently only support scanning on WalletConnect addresses.
- We should also allow scanning of recipient addresses

# High-level overview of the feature
- User can scan ethereum QR codes.
- The user ends up on the screen where their enter amount and select the asset.
- This changes the send flow a bit since the user can switch the asset after selecting the recipient

# Misc 
Designs for this are worked on in #255

**Comment by DmitryBespalov** [comment]
The QR-code formats that we want to recognize:
- [ERC-67](https://github.com/ethereum/EIPs/issues/67): Standard URI scheme
- [ERC-681](https://eips.ethereum.org/EIPS/eip-831): URL format for Transaction Requests (supersedes ERC-67 with backward compatibility)
  - [ERC-831](https://eips.ethereum.org/EIPS/eip-831): URI Format for Ethereum (needed by ERC-681)
- just a hex value: `0xabcdef...fedcba`
