### ISSUE TITLE
UX bug in Send ETH/Token page

### ISSUE THREAD

**Issue by zhangzhongnan928** [gnosis/safe#277]
![IMG_8867](https://user-images.githubusercontent.com/33795543/69767191-3e56cd80-11cf-11ea-925f-8612b0a8ea90.PNG)
![IMG_8868](https://user-images.githubusercontent.com/33795543/69767196-43b41800-11cf-11ea-8e3e-a1db645d70ae.PNG)
![IMG_8869](https://user-images.githubusercontent.com/33795543/69767201-46167200-11cf-11ea-905b-797484e2b62a.PNG)

If anything "interrupts" the inputting amount process (like a notification, or even just tap other parts of the screen), the balance checking will stop working

**Comment by rmeissner** [comment]
Thanks for the report. This is tracked on the safe-ios repo (https://github.com/gnosis/safe-ios/issues/1311) and should be fixed with the update released today.
