### ISSUE TITLE
Remove Fabric from Privacy Policy

### ISSUE THREAD

**Issue by sche** [gnosis/safe#283]
I assume we should update our privacy policy.
Fabric is going to be closed by Google. On iOS, we already migrated to Firebase for crash reporting. I assume Android did it as well.

**Comment by tschubotz** [comment]
Android is still using the Fabric SDK. The team says under the hood Fabric is forwarding to Firebase. Also they say crash reporting won't be impacted even after Fabric closes down. In that case, let's not touch the legacy app and leave Fabric in there. And rather focus on the new app :)

cf. [Slack conversation](https://gnosisinc.slack.com/archives/C63LQTGNB/p1588084801446000)
