### ISSUE TITLE
Add kotlin example for Safe interaction

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe#284]
# What is this feature about? (1 sentence)
Developers want to interact with the Safe contract from within their own apps and need some easy way to get started.

# Why is it needed? What is the value? For whom do we build it?
We want that more users own and interact with Safes, therefore we should enable more developers to make use of the Safe contracts.

# High-level overview of the feature
- Create new repository with example
  - Show how to trigger the proxy factory
  - Show how to trigger the relay service
  - Show how to sign a transaction
  - Add support for svalinn and web3j

**Comment by d10r** [comment]
@rmeissner this may be helpful: https://github.com/lab10-coop/safe-contracts/tree/dh-helpers/lab10/kotlin-web3j/src/main/kotlin
