### ISSUE TITLE
View ETH and ERC20 token balance

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#286]
# What is this feature about? (1 sentence)
As a user, I am able to view my ETH and ERC20 token balances.

# Why is it needed? What is the value? For whom do we build it?
Users should know what is going on with their Safe. A key info for this is the current balance.

# High-level overview of the feature
- User can see their ETH balance, ETH is always on top
- User can see the balance of all ERC20 tokens with balance > 0, tokens are ordered by their names, ascending
- User sees fiat value in USD per asset
- ~User can select the reference fiat currency from a list somewhere in the app~
  - Selecting the fiat currency will be part of a separate epic. (#304)
- Please format numbers according to https://github.com/gnosis/safe/wiki/How-to-format-amounts
- (Edit June 19) Fiat currencies are formatted with the system formatter of the respective operating system.

# Updates

#### 19.06.2020
Fiat currencies are formatted with the system formatter of the respective operating system.

**Comment by posthnikova** [comment]
> User can select the reference fiat currency from a list somewhere in the app

Is this setting Safe-specific or app-specific?

**Comment by tschubotz** [comment]
> > User can select the reference fiat currency from a list somewhere in the app
> 
> Is this setting Safe-specific or app-specific?

This should be app specific. I don't see why users would use different reference currencies within 1 app.
Added this to the description ✅

**Comment by liliya-soroka** [comment]
Verified
app version
android 1.12.1 -98  with note: Formatting will be implemented after the public release - the issue is created and prioritized as not a show stopper for public release
ios 2.0.0 (10)
