### ISSUE TITLE
View collectibles

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#287]
# What is this feature about? (1 sentence)
Users can view their NFTs

# Why is it needed? What is the value? For whom do we build it?
Users own NFTs, e.g. ENS domains. In order to build up trust, they need to know which ones are stored in their Safe.

# High-level overview of the feature

- We support ERC721 tokens only for now.
- User can switch between coins and collectibles.
- User sees overview of their list of collectibles, grouped by type, similar to https://gnosis-safe.io/app/#/
- Meta data (image and name) is displayed
- NFT info is pulled from our backend (cf. gnosis/safe-transaction-service#90)

# Data Source
Please use the collectibles endpoint.

Request:

```shell
curl -X GET "https://safe-transaction.staging.gnosisdev.com/api/v1/safes/0xaE3c91c89153DEaC332Ab7BBd167164978638c30/collectibles/"
```

Response:
```
[
  {
   // NFT token contract address
    "address": "0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85",
  // NFT token name (label of the section in the list)
    "tokenName": "Ethereum Name Service",
// not used
    "tokenSymbol": "ENS",
  // collectible id
    "id": "58937894113821098059473516979904382739138110039311364528640314046933456594245",
// not used
    "uri": null,
// name of the collectible
    "name": "tttk.eth",
// description of the collectible
    "description": ".eth ENS Domain",
// image of the collectible
    "imageUri": "https://gnosis-safe-token-logos.s3.amazonaws.com/ENS.png",
// not used
    "metadata": {
      "name": "tttk.eth",
      "description": ".eth ENS Domain",
      "image": "https://gnosis-safe-token-logos.s3.amazonaws.com/ENS.png"
    }
  }
]

token contract logo is taken from the /tokens endpoint
```

HTTP Code | Description
-|-
200 | OK
404	| Safe not found
422	| Safe address checksum not valid

# Screens

- [Android](https://app.zeplin.io/project/5e9efc30726e106958cc43de/dashboard?seid=5ea968a34ac83325cfa42af5)
- [iOS](https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/dashboard?seid=5eb9786c64739378603379e3)

# Tracking 
_(Added June 29)_
- Add screen tracking for (cf. [wiki](https://github.com/gnosis/safe/wiki/Tracking))
  - `assets_collectibles`
  - `assets_collectibles_details`

# Updates
- June 29: Add screen tracking info (taken out of #299) 
- July 6: Changed the "Misc" to "Data Source" where added example request and response data
- September 11, Tobi: Don't display link to open NFT url (cf. [Slack](https://gnosisinc.slack.com/archives/C63LQTGNB/p1599809940338200))

**Comment by sche** [comment]
I am not sure how is it implemented on the web now. Is the collectibles mechanic similar to ERC20 tokens? Will we have a "whitelisted" list of trusted contracts, or will we need any spam-protection mechanics?

**Comment by tschubotz** [comment]
@sche 
I just checked, the web interface pulls the ERC721 tokens for an address from OpenSea. I suggest doing the same if there are no concerns.

**Comment by MouazAlzahabi** [comment]
Is it possible to make our backend pulls token from OpenSea instead of the app, then the app will only needs to communicate with our backend?

**Comment by tschubotz** [comment]
> Is it possible to make our backend pulls token from OpenSea instead of the app, then the app will only needs to communicate with our backend?

I see your point. Could be nicer to have the app only interact with our backend for this. 
Product wise i currently don't see any preference for either option.
So I'd leave that tech decision regarding which way is better to you guys. 
cc @Uxio0 @rmeissner

**Comment by rmeissner** [comment]
I prefer to have them in our backend too.
For 2 reasons:
- we also have the transfers there (as @MouazAlzahabi said we only need to handle 1 api)
- and (more personal point) everything related to ERC-721 depends on OpenSea which in a decentralized world is very questionable .... I would love if we could get around that ... but maybe that is too much for now

**Comment by elgatovital** [comment]
do we have an endpoint in our backend already or an issue so that we could keep track of the progress? @rmeissner @Uxio0

**Comment by Uxio0** [comment]
> do we have an endpoint in our backend already or an issue so that we could keep track of the progress? @rmeissner @Uxio0

We don't have either yet, I will create later an issue for that :)

**Comment by Uxio0** [comment]
https://github.com/gnosis/safe-transaction-service/issues/90

**Comment by DmitryBespalov** [comment]
exmaple request on rinkeby:

https://rinkeby-api.opensea.io/api/v1/assets/?owner=0x71b328e43C63404E33911E926925A692Db8b93d6

**Comment by liliya-soroka** [comment]
The test-cases are ready https://gno.testrail.io/index.php?/suites/view/17

**Comment by liliya-soroka** [comment]
Verified
 app version:
android 2.0.0(17)
ios 2.1.0 (2)

**Comment by statzky** [comment]
How often does gnosis-safe refresh token's metadata? I changed description of my token an hour ago, but I still cant see refreshed description in the gnosis assets UI.

**Comment by Uxio0** [comment]
We never refresh token information

**Comment by statzky** [comment]
So can I somehow request an update of token's metadata?

**Comment by Uxio0** [comment]
We would need to understand what are you changing. ERC20 name/decimals/info? ERC721? ERC721 uri or metadata?

**Comment by statzky** [comment]
> We would need to understand what are you changing. ERC20 name/decimals/info? ERC721? ERC721 uri or metadata?

Oh, sorry. I've ERC721 token in Polygon, I changed description and image of its token in JSON, but JSON is still reachable by the same URI. So can I request updated data in order to see new content of token in Gnosis-safe's UI?

**Comment by Uxio0** [comment]
Then it will refreshed, as we only keep information for ERC721 for 2 days 😉 . I thought you were talking about an ERC20

**Comment by statzky** [comment]
> Then it will refreshed, as we only keep information for ERC721 for 2 days 😉 . I thought you were talking about an ERC20

Ah, my bad. Thank you for the answer!
