### ISSUE TITLE
View Safe details and settings

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#288]
# What is this feature about? (1 sentence)
This will allow users to view their Safe details such as owners, threshold or configured mastercopy.

# Why is it needed? What is the value? For whom do we build it?
In order for users to know what is going on, they need to know the configuration details of their Safe.

# High-level overview of the feature
User can view the following (sorted by priority):
- Safe address
- Contract version (0.1.0, 0.2.0, 1.0.0, 1.1.0, unknown if not known) and master copyaddress
  - Check mark if it's a known one.
- Required confirmations ("n our of m")
- Owner addresses
- ENS name, if there is a reverse record set
  - "Reverse record not set" if not
- Advanced settings/details:
  - Nonce
  - Fallback handler
    - "Known" if known, "Unknown" otherwise
  - addresses of enabled modules
    - "Unknown" or module name
  - ~Deployment parameters (If available)~

**All addresses should have identicons and should link to Etherscan.**

# Tracking 
_(Added June 29)_
- Add screen tracking for (cf. [wiki](https://github.com/gnosis/safe/wiki/Tracking))
  - `settings_safe_no_safe`
  - `settings_safe`
  - `settings_safe_edit_name`
  - `settings_safe_advanced`

# Updates
- June 29: Add screen tracking info (taken out of #299)

**Comment by jpalvarezl** [comment]
All of these fields should be somehow copiable to the clipboard if the user wants to take that information to a different app or context.

**Comment by DmitryBespalov** [comment]
@tschubotz Because we have the creation transaction, should the "Deployment parameters (If available)" be in this screen?

**Comment by tschubotz** [comment]
Good question. Originally I thought yes, however we don't have it in the designs. And also not in the web interface. I just crossed out that line in the epic description. Let's add it later if needed :)

**Comment by liliya-soroka** [comment]
@tschubotz the test cases are ready for review https://gno.testrail.io/index.php?/suites/view/10

**Comment by liliya-soroka** [comment]
@tschubotz , the feature is fully tested on both platforms. All issues are attached to the Epic.
Please , check if there are any critical or major for the release issues

**Comment by tschubotz** [comment]
Thanks, I would leave this open until gnosis/safe-android#750 is implemented. Then we can close.

**Comment by liliya-soroka** [comment]
The epic is closed as all related issues have minor and trivial priorities
