### ISSUE TITLE
View transaction list

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#289]
# What is this feature about? (1 sentence)
This allows users to see a list of incoming and outgoing transactions.

# Why is it needed? What is the value? For whom do we build it?
In order to know what is happening with their Safe, a user needs to be able to inspect all transaction details

# High-level overview of the feature

- (Added July 1) All Dates and times should be displayed in the local device time that is set.

### Transaction list:
- User sees 2 sections:
  - A section for txs waiting for confirmations or waiting for execution
  - Another section for txs that have been executed or cancelled
- User sees all txs sorted in both sections:
  - Waiting for confirmations
    - Sorted by nonce, **ascending**
    - If 2 txs with same nonce, then put the one with the later creation date higher
  - Executed and cancelled
    - Executed txs sorted by execution date, **descending** (Both incoming and outgoing)
    - Add cancelled txs in that list with their created timestamp
  - Find more on the sorting [in the wiki](https://github.com/gnosis/safe/wiki/How-should-transactions-be-sorted).
- User sees all incoming and outgoing transactions.
- User can explore transaction details further by tapping on a transaction.
- Transactions should be identifed by their nonce. There should **not** be another identifier.
- (Edit June 22) The [designs](https://zpl.io/VOGMB4Q) use "human-readable" names for settings changes (e.g. "Add owner"). We decided to not yet introduce another mapping and rather use the names of the functions directly (cf. https://github.com/gnosis/safe-ios/issues/281#issuecomment-647479817)
- (Edit June 29) For NFT (ERC721) transfers, please display the following on the list (Example here is for 1 incoming/outgoing token):
  - When the contract name is set then `1 <contract_name>` 
  - When it's ENS, then `1 ENS` (since the contract name is not set for ENS.
  - Otherwise `1 NFT`

### Transaction details:
Split out in to separate ticket: #311 

### Transaction decoding:
- Decode the following transactions by showing details:
  - ERC20 token transfers
  - Safe settings changes (addOwner, removeOwner, swapOwner, changeMastercopy)
  - **NOTE**: display all "multiSend" transactions as "custom" transactions - including transactions resulting from the "contract update" from the web interface.

#### Transaction status
https://github.com/gnosis/safe/wiki/Safe-transaction-states

### Additional information
- New backend transaction endpoint: gnosis/safe-transaction-service#81
- The endpoint returns module txs also already. Let's ignore them for now and don't display them.

# Tracking 
_(Added June 29)_
- Add screen tracking for (cf. [wiki](https://github.com/gnosis/safe/wiki/Tracking))
  - `transactions`
  - `transactions_no_safe`

## Updates
- June 23 (Dima): MultiSend transactions are displayed as custom transactions in the Phase 1. Contract upgrade action from the web UI will result in multi send transaction, so it will be displayed as a "custom" transaction. The issue will be resolved in the future iterations. gnosis/safe-ios#280
- June 29, Tobi: Add screen tracking info (taken out of #299) 
- June 29, Tobi: Add info on how to display ERC721 transfers
- July 1, Tobi: Clarified timezones

**Comment by rmeissner** [comment]
Some detail questions:
- `chronologically` what timestamp is here used? does this make sense for pending transactions? Shouldn't they be sorted by nonce? Or do we not display pending transactions for now?
- `Status (Pending, failed, etc)` - Pending here means "Awaiting confirmation" or that the ethereum transaction has been submitted?
- `Network fee` - is this the fee paid by the contract or of the ethereum transaction that executed the safe tx? Should we display both?
- `Type of operation (call, delegatecall etc)` - there is no `etc` :P 
- `If a transaction was triggered by the Safe itself` - is this a complicated description for "outgoing transaction"?

**Comment by tschubotz** [comment]
@rmeissner 
> Some detail questions:
> 
>     * `chronologically` what timestamp is here used? does this make sense for pending transactions? Shouldn't they be sorted by nonce? Or do we not display pending transactions for now?

I think by nonce is the way to go - changed this.

>     * `Status (Pending, failed, etc)` - Pending here means "Awaiting confirmation" or that the ethereum transaction has been submitted?

I would reuse what the web interface does. Add the list to the ticket for clarification.

>     * `Network fee` - is this the fee paid by the contract or of the ethereum transaction that executed the safe tx? Should we display both?

- Good question. Need to think about this.

>     * `Type of operation (call, delegatecall etc)` - there is no `etc` 

ok 🙄 

>     * `If a transaction was triggered by the Safe itself` - is this a complicated description for "outgoing transaction"?

yes, rephrased it.

**Comment by lukasschor** [comment]
> cancelled - When the current Safe nonce is greater or equal to the nonce of the this tx.

Is this correct? Because that would also be true for all successfully executed transactions. You might want to specify that this is specifically for transactions that were not executed yet but meet the above criteria.

**Comment by tschubotz** [comment]
> > cancelled - When the current Safe nonce is greater or equal to the nonce of the this tx.
> 
> Is this correct? Because that would also be true for all successfully executed transactions. You might want to specify that this is specifically for transactions that were not executed yet but meet the above criteria.

Add this missing piece. Thanks!

**Comment by koeppelmann** [comment]
sorry, have not followed the whole thread - just wanted to say that IMO we should use the nonce as a clear ID/identifier for outgoing transactions.
The current solution to just count all incoming and outgoing transactions and give them an ID is not a good solution as "incoming transaction" is nothing well defined. An incoming transaction can be an event in a random (spam) token. It is a subjective decision what tokens you monitor - so this should not be used to define an ID which might be critical for teams to communicate/identify a transaction.

**Comment by tschubotz** [comment]
> just wanted to say that IMO we should use the nonce as a clear ID/identifier for outgoing transactions.

Agree. I added this to the description.

**Comment by jpalvarezl** [comment]
> ### Transaction details:
> 
>     * User sees the following details:
>       
>       * Sender (address & identicon, tapping opens etherscan)
>       * Recipient (address & identicon, tapping opens etherscan)

Are we sure tapping should take the user outside the app? It's a pretty common action and that could affect retention, IMO. Maybe we could copy to clipboard instead on tap and on long tap we open a contextual menu that offers going to etherscan directly?

**Comment by lukasschor** [comment]
> > ### Transaction details:
> > ```
> > * User sees the following details:
> >   
> >   * Sender (address & identicon, tapping opens etherscan)
> >   * Recipient (address & identicon, tapping opens etherscan)
> > ```
> 
> Are we sure tapping should take the user outside the app? It's a pretty common action and that could affect retention, IMO. Maybe we could copy to clipboard instead on tap and on long tap we open a contextual menu that offers going to etherscan directly?

I like this idea. Also, I think the app should provide all the information needed to understand what's going on. So going to Etherscan should become more and more an "advanced" feature.

**Comment by tschubotz** [comment]
> Are we sure tapping should take the user outside the app? It's a pretty common action and that could affect retention, IMO. Maybe we could copy to clipboard instead on tap and on long tap we open a contextual menu that offers going to etherscan directly?

I think you're right. In the old app we showed the full address on top. Will discuss this with @posthnikova what makes most sense there.

**Comment by posthnikova** [comment]
Transaction history and details wireframes: 

![image](https://user-images.githubusercontent.com/45787536/78773648-d80b6400-7993-11ea-926d-5ec718960a3b.png)

Also in Invision (interactive): https://invis.io/6UWPBEPYZAP#/412827542_Transactions_

**Comment by lukasschor** [comment]
I think we should call the two sections in the tx list „Queue“ and „History“. Or something similar.

**Comment by elgatovital** [comment]
do we have pagination/sorting for the transaction list endpoint?

**Comment by rmeissner** [comment]
Yes see in the swagger file of the current endpoints

**Comment by jpalvarezl** [comment]
Is there going to be a new endpoint that delivers the data aggregated or de we collect and aggregate in the app?

**Comment by tschubotz** [comment]
> Is there going to be a new endpoint that delivers the data aggregated or de we collect and aggregate in the app?

afaik @Uxio0 is working on a combined endpoint in the ticket you linked then no aggregation on device should be necessary anymore. Does this make sense and does it answer your question? @jpalvarezl

**Comment by tschubotz** [comment]
Maybe for planning purposes on mobile: @Uxio0 when do you think you'll have https://github.com/gnosis/safe-transaction-service/issues/81 ready/testable? :)

**Comment by Uxio0** [comment]
> Maybe for planning purposes on mobile: @Uxio0 when do you think you'll have [gnosis/safe-transaction-service#81](https://github.com/gnosis/safe-transaction-service/issues/81) ready/testable? :)

I'm currently working on it and it's very tricky, but I think at the end of next week I should have something at least for testing

**Comment by rmeissner** [comment]
How should we handle transactions triggered by modules? 
Proposal:
- For now we should ignore them (so the apps should not crash if the backend returns them)
- We should create a follow up issue to define how to handle these

@tschubotz wdyt?

**Comment by tschubotz** [comment]
> For now we should ignore them (so the apps should not crash if the backend returns them)

yes, added to epic

> We should create a follow up issue to define how to handle these

Yes, the web interface has similar questions I think. I'll sync with lukas.

**Comment by jpalvarezl** [comment]
Do these transaction look the same as the rest in terms of data? If we have certain transaction that we should ignore and therefore not render in the UI, would that somehow affect the pagination? I understand that there is a "next" and "previous" URL but they still contain "limit"  and  "offset".

**Comment by liliya-soroka** [comment]
Verified
app version 
android - 1.12.1 - 98
ios - 2.0.0 (10)
