### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#290]
# What is this feature about? (1 sentence)
This will notify the user about Safe activity via push notifications.

# Why is it needed? What is the value? For whom do we build it?
As part of building up trust for the Safe, a user would want to know whenever there is a transaction happening that affects their Safe.

# High-level overview of the feature
- User gets notified when:
  - A Safe transaction failed or succeeded.
  - ETH, ERC20 or ERC721 tokens were received.
- **iOS only:** User should be asked to enable push notifications after successfully adding their first Safe
  - For now, only ask the user after adding their **first** Safe to keep it simple.
  - If users denied push permission, they can still enable it via the iOS settings.
  - In case users update from the existing beta app and they already have a Safe loaded, please ask at the first app start right away.
- When a user removes a Safe from their device, it should not receive pushes for this Safe anymore.
- If 2 interacting Safes are the same device - notifications for both Safes are received
- Multiple devices can be registered for the same Safe -> All devices should receive the pushes
- All open notifications should be cleared upon app start.
- Notifications that are received while the app is in foreground should appear just like regular notifications. 
  - If they are tapped the respective screen is opened.
  - If they are not tapped, they remain unread until they get tapped or until the next app start (where all notifications get cleared)
- **iOS only:** For every notification, the badge count on the app icon is incremented by 1. The badge count is also cleared upon app start

# Texts & types

- `safe_name` should be the name that the user set for their Safe.

### A Safe tx was successful / failed

- Can be contract interaction, transfer, doesn’t matter.
- Client should display the Safe name.
- Client should display failed/successful.
- Tx details are opened upon opening notification
- Texts:
```
<safe_name>: Transaction successful
```

```
<safe_name>: Transaction failed
```

- No push notification for cancelled transactions.

### ETH was received

- Client should display the Safe name.
- Client just displays that ETH was received incl. amount
- Tx list is opened upon opening notification
- For amount: Please use regular [amount formatting rules](https://github.com/gnosis/safe/wiki/How-to-format-amounts)
- Texts:
```
<safe_name: <amount> ETH received
```

### ERC20 was received

- Client should display the Safe name.
- Client just displays that ERC20 tokens were received, not how much
- Tx list is opened upon opening notification
- Texts:

```
<safe_name>: ERC20 tokens received
```

### ERC 721
_This is not a priority but seems like it's easy to do_

- Client should display the Safe name.
- Client just displays that ERC721 token was received, not which one
- Tx list is opened upon opening notification
- Texts:

```
<safe_name>: ERC721 token received
```

# Related issues
- https://github.com/gnosis/safe-notification-service/issues/70

# Update
- Jul 30 Tobi: Update epic after backlog refinement
- Aug 5 Tobi: Make push notification dialog iOS only.
- Aug 5 Tobi: Add more details after [Slack discussion](https://gnosisinc.slack.com/archives/C63LQTGNB/p1596622918275500)
- (Aug Tobi: Add more details on app badges and pushes while app is open (cf. [Slack](https://gnosisinc.slack.com/archives/C63LQTGNB/p1596640506286000))

**Comment by jpalvarezl** [comment]
Should the user be notified that some parameters of their safe require updates? Every week or so? Not sure if this interval would be too intentse for a user, but somehow let them know they should update or set a higher threshold.

**Comment by tschubotz** [comment]
> Should the user be notified that some parameters of their safe require updates? Every week or so? Not sure if this interval would be too intentse for a user, but somehow let them know they should update or set a higher threshold.

@jpalvarezl 
I like the idea. First I would display that they need to e.g. update their contract before sending a notification.
I wouldn't implement this right now since we cannot propose txs from mobile yet. It would be quite bad ux in my opinion if there is a notitication "hey, do something" then I open the app and I cannot fix it.
Let's pick this up later when we can propose transactions from mobile :)

**Comment by posthnikova** [comment]
> Clicking a notification would open the transaction details of that tx

I wonder if we should show notifications for the Safe that is currently not active in the app. In this case we should switch Safes automatically.

**Comment by posthnikova** [comment]
Just to make sure - are we talking about push notifications or in-app notifications?

> users can specify which notification types to receive and which ones not.

Again, the question is this setting app-specific or Safe-specific

**Comment by tschubotz** [comment]
> > Clicking a notification would open the transaction details of that tx
> 
> I wonder if we should show notifications for the Safe that is currently not active in the app. In this case we should switch Safes automatically.

Yes, the app should switch automatically. - changed this in the description.

> Just to make sure - are we talking about push notifications or in-app notifications?

Push notifications - made it clear in the description and title.

> > users can specify which notification types to receive and which ones not.
> 
> Again, the question is this setting app-specific or Safe-specific

Good question. I would make this app specific.

**Comment by sche** [comment]
> From the above list, users can specify which notification types to receive and which ones not.

Is there a design for this? @posthnikova 

> For token transfer info: Cut of decimals at maximal 6 digits after decimal separator.

Should we use our token formatting rules for this? @tschubotz

**Comment by tschubotz** [comment]
> From the above list, users can specify which notification types to receive and which ones not.

Let's not do this in the first iteration. I removed it from the epic.



> For token transfer info: Cut of decimals at maximal 6 digits after decimal separator.
> Should we use our token formatting rules for this? @tschubotz

Yes! Good point. Thanks. Specified it in epic.

**Comment by DmitryBespalov** [comment]
@tschubotz Question: do we need UI for enabling/disabling notifications per safe, (and per app)?

**Comment by tschubotz** [comment]
> @tschubotz Question: do we need UI for enabling/disabling notifications per safe, (and per app)?

Long term I think yes, however for a first version I would say that's not required. Let's add this later.

**Comment by Uxio0** [comment]
> An outgoing transaction was submitted to Ethereum
An outgoing transaction failed or succeeded.

**Comment by Uxio0** [comment]
> An outgoing transaction was submitted to Ethereum

There's no way for us to detect this. Transactions are only detected when mined, and that will overlap with `An outgoing transaction failed or succeeded.`

**Comment by tschubotz** [comment]
> There's no way for us to detect this. Transactions are only detected when mined, and that will overlap with An outgoing transaction failed or succeeded.

Just removed this from the requirement. Also see https://github.com/gnosis/safe-notification-service/issues/70

**Comment by liliya-soroka** [comment]
Test cases for the Push Notifications are ready and can be checked - https://gno.testrail.io/index.php?/suites/view/41

**Comment by liliya-soroka** [comment]
Verified
ios app version 2.0.0 (12)
android app version 1.12.1 -114
