### ISSUE TITLE
App settings

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#291]
# What is this feature about? (1 sentence)
This will add some basic settings things to the app.

# Why is it needed? What is the value? For whom do we build it?
There are some things that every app needs.

# High-level overview of the feature
- User can see the app version.
- ~User can see and select reference fiat currency for the entire app~
  - This will be part of a separate epic
  - Please leave out the fiat row for now.
- ~User can select the appearance~
  - This will be part of a separate epic
  - Please leave out the this row for now.
- User can see the network version (Mainnet, Rinkeby)
- User can view Terms (Link to https://gnosis-safe.io/terms/)
- User can view Privacy Policy (Link to https://gnosis-safe.io/privacy/)
- User can view used licenses (Link to https://gnosis-safe.io/licenses/)
- Terms, PP and licenses are not hardcoded, but links that open a browser window (exactly how we do it in the current app)
- User can get in touch with us (Email, Discord, Twitter)
  - As a company we decided to moved to Discord, so let's take this opportunity.
  - Help center: https://help.gnosis-safe.io
  - Email: safe@gnosis.io
  - Discord: https://discord.gg/FPMRAwK
  - Twitter: https://twitter.com/gnosisSafe
  - Feature suggestion: https://safe.cnflx.io/
- User can see other app settings:
  - ENS resolver address
  - RPC endpoint url (e.g. `https://rinkeby.infura.io`)
  - Backend services urls (safe-relay, safe-tranasction) (e.g. `https://safe-transaction.rinkeby.gnosis.io`)
  - Tapping the urls will copy them to clipboard

### Email template
To: `safe@gnosis.io`
Subject: `Feedback`
Body:
```
<App name>
Safe address: <Safe address>
Feedback:
```

<App name> e.g. Safe Multisig v0.2.0 (1)
<Safe address> e.g. 0x8E77c8D47372Be160b3DC613436927FCc34E1ec0 (currently active Safe, `None` if no Safe added yet)

# Tracking 
_(Added June 29)_
- Add screen tracking for (cf. [wiki](https://github.com/gnosis/safe/wiki/Tracking))
  - `settings_app`
  - `settings_app_advanced`
  - `settings_app_support`

# Updates
- June 29: Add screen tracking info (taken out of #299)

**Comment by Georgi87** [comment]
Do we plan a different app for rinkeby?

**Comment by tschubotz** [comment]
> Do we plan a different app for rinkeby?

Yes, I think that is the way to go. If it would be one app, then we have to add additional logic for letting the user know that their Safes don't work on the other environment. Also this make pushes harder etc.

@gnosis/mobile-devs do you agree with this or do you think we should build 1 app with a network switch?

**Comment by rmeissner** [comment]
I prefer multiple apps

**Comment by jpalvarezl** [comment]
Multiple apps +1 network switch could lead to catastrophic confussions for the user. Which network the app operates should be as conspicuous as we can make it

**Comment by DmitryBespalov** [comment]
I prefer multiiple apps and network switch

**Comment by tschubotz** [comment]
> I prefer a network switch as it is a standard component in metamask and dapps

Which dapps do you have in mind that have this network switch? 

Generally, I like the idea of having a network switch in a wallet since, yes, that's what Metamask (The standard wallet atm) yes.
However I think there's then too much happening under the hood:

- A Safe on Mainnet isn't automatically avaiable on Rinkeby. (In Metamask all accounts can live on both chains since there's nothing to deploy)
- When there's an incoming notification, and the user opens it, that would mean the app needs to first switch networks since there would be notifications coming in for Rinkeby and and mainnet Safes.

That's why I feel like having 2 separate apps would be simpler.

Could you guys please elaborate a bit more?

**Comment by jpalvarezl** [comment]
My understanding is limited at the moment, but as I see it metamask represents an EOA on every network, whereas in the case of a safe there is a few layers in between that make it a bit more complex and network dependant as it ties in a few contracts (I am guessing that each deployment parameter points to a different contract?). 

We'd essentially have to keep as many sessions as the user has safes in different networks? While at the same time allowing selection of different safes in those few networks? I feel like "flat mapping" the app structure into several apps would greatly simplify this UI-wise.

And just like you mention @tschubotz notifications would become an issue eventually as we'd have to perform the network check on every incoming transaction and potentially having to switch contexts at that point would incur on an extra step for the user (password input in case of switch) we'd otherwise wouldn't have on multi app scenario.

I feel like we can always suggest and point the users to the alternative app for a different network. I agree on the point, that multiple apps would essentially take N times the space in the device it would, being N the number of networks a user is currently active in.

**Comment by lukasschor** [comment]
Please use this link for the privacy policy: gnosis-safe.io/privacy/

**Comment by rmeissner** [comment]
I would propose to split this issue at least into two maybe even 3.

1.) Static app settings/ information -> only show information that doesn't require to perform a network request. This makes it easier UI wise as no error states need to be considered in this screen
2.) Add on-chain info -> owners, modules, etc. For this we also need to consider error states (as it should probably still be possible to delete/ rename the Safe locally without internet)
3.) Fiat currency selection -> this is an additional external service and I would have this as a completely separate feature.

1. and 2. could be one epic ticket, but I would still separate them when implementing.

**Comment by tschubotz** [comment]
>  3.) Fiat currency selection -> this is an additional external service and I would have this as a completely separate feature.

yes cf https://gnosisinc.slack.com/archives/C63LQTGNB/p1586349216060400

Regarding you other proposal, I believe that's already the case. This epic only contains app settings, which should be static.
All Safe settings such as owners or modules are part of #288 :)

**Comment by rmeissner** [comment]
> believe that's already the case.

ahhh yeah sorry ... I only looked at the designs 🤦‍♂

**Comment by elgatovital** [comment]
Should we also show item for Telegram in the Get in Touch section? Or discord is enough? @tschubotz

**Comment by tschubotz** [comment]
No Telegram please, only Discord since there was a company decision to move everything from Telegram to Discord :)

**Comment by liliya-soroka** [comment]
@tschubotz  
What should be displayed in the App Settings if there is no added safe?
Now we have a difference between app settings in the android and ios apps.
Should the next to be displayed in the app settings if no added Safe:
-Fiat currency
- Appearance

**Comment by tschubotz** [comment]
> What should be displayed in the App Settings if there is no added safe?

I think the app settings should look the same, no matter if there is a Safe added or not. Is there a case where this doesn't make sense?

> Now we have a difference between app settings in the android and ios apps.

Yes, the designs had this, the ticket says that this should not be included yet though. 

> Should the next to be displayed in the app settings if no added Safe:
> -Fiat currency
>     * Appearance

Once we actually have implemented #308  and #304 I don't see an issue with displaying both even when there is not Safe added, yet.

**Comment by liliya-soroka** [comment]
@tschubotz 
The feature is fully tested on both platforms.
There is only one issue with email template on android ( not a critical)
In my opinion, the Epic can be closed as done

**Comment by tschubotz** [comment]
agree, closing then :)
