### ISSUE TITLE
Accept terms and privacy policy

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#292]
# What is this feature about? (1 sentence)
Every app needs terms and a privacy policy. 

# Why is it needed? What is the value? For whom do we build it?
Laws ..

# High-level overview of the feature
-  User has to accept Terms of Use and Privacy policy before using the app.
- Upon opening the app, the "[Get started screen](https://zpl.io/VqjqKgm)" is displayed.
- Upon hitting "Get Started", the user gets asked whether they accept ([screen](https://zpl.io/adver0K)
- User can view Terms and Privacy policy (https://gnosis-safe.io/privacy/ and https://gnosis-safe.io/terms)
  - Both are not hardcoded text, but links that open a browser window (exactly how we do it in the current app)
- If user agrees, they end up on the empty assets screen (since there is no Safe yet)
- User user disagrees, they are back on the "Get Started screen".

**Comment by Georgi87** [comment]
I wonder if this is required in the app and not the web interface?

**Comment by jpalvarezl** [comment]
Should be a technical requirement that we are able to swap these from some form of backend. Then we don't need to deploy a new APK (in the case of Android) each time and we can react quickly with updates if necessary.

**Comment by tschubotz** [comment]
@Georgi87 

> I wonder if this is required in the app and not the web interface?

In the web interface, there is a link to terms and privacy policy in the footer at all times. And also when adding a Safe, there is text that says "you accept xxx". 

> I think the privacy policy doen't have to be accepted, just linked?

Yes, "by continuing you accept" or something like this

@jpalvarezl 


> Should be a technical requirement that we are able to swap these from some form of backend. Then we don't need to deploy a new APK (in the case of Android) each time and we can react quickly with updates if necessary.

Yes, that's a requirement. Those should just be links to the web pages. That's how we do it in the legacy app. I would like to keep that. I made it more explicit in the description. Thanks for bringing it up.

**Comment by lukasschor** [comment]
> I wonder if this is required in the app and not the web interface?
> 
> I think the privacy policy doen't have to be accepted, just linked?

In the web interface the user confirms to consent to the Terms and PP every time a Safe is created or loaded.

![image](https://user-images.githubusercontent.com/17196842/78148974-c414af00-7435-11ea-8a8c-92d4dd9f5a7d.png)

**Comment by MouazAlzahabi** [comment]
I just wonder, it's still needed to be done from within the app, as it's also required to provide the link in app's metadata on both GooglePlay and Appstore?

**Comment by tschubotz** [comment]
> I just wonder, it's still needed to be done from within the app, as it's also required to provide the link in app's metadata on both GooglePlay and Appstore?

I don't understand this. Could you pls rephrase your question?

**Comment by MouazAlzahabi** [comment]
On iTunes Connect there when you submit app for review you must provide "Privacy Policy URL" in the app metadata, and there is similar thing on GooglePlay. Knowing that fact, do we have also to present privacy policy upon opening the app?

**Comment by lukasschor** [comment]
We have actually seen in the funnel analytics from the old app, that the step of accepting the terms lead to almost no drop-offs. Considering this, I do not see any big drawbacks speaking against adding it. No matter if it is technically required or not.

**Comment by tschubotz** [comment]
> We have actually seen in the funnel analytics from the old app, that the step of accepting the terms lead to almost no drop-offs. Considering this, I do not see any big drawbacks speaking against adding it. No matter if it is technically required or not.

Agree.

> On iTunes Connect there when you submit app for review you must provide "Privacy Policy URL" in the app metadata, and there is similar thing on GooglePlay. Knowing that fact, do we have also to present privacy policy upon opening the app?

@MouazAlzahabi 

Ah that's what you mean. As to my understanding having it just linked there is not enough. A user needs to explicity accept it. Otherwise it's too implicit :)

**Comment by lukasschor** [comment]
Please use this link for the privacy policy: gnosis-safe.io/privacy/

**Comment by jpalvarezl** [comment]
Are we right to assume that clicking "No thanks" closes the app? 
https://github.com/gnosis/safe-android/issues/551

**Comment by tschubotz** [comment]
- The [first app screen](https://projects.invisionapp.com/share/Y4WYRGGQVNR#/screens/414924699) is this one, right?
- After tapping "Get started", the user ends up [here]https://projects.invisionapp.com/share/Y4WYRGGQVNR#/screens/414924729).
- Tapping "No thanks" should just close the bottom sheet and the user ends up again on the [first app screen](https://projects.invisionapp.com/share/Y4WYRGGQVNR#/screens/414924699)

**Comment by jpalvarezl** [comment]
Yes that's the one I meant. Thanks for clarifying!

**Comment by sche** [comment]
@tschubotz 
> Ah that's what you mean. As to my understanding having it just linked there is not enough. A user needs to explicity accept it. Otherwise it's too implicit :)

I think having for new users "By continuing you agree with our terms" is enough. I didn't hear about legal obligations, so that we require to do it another way around.
What we should do is whenever we update our privacy policy, we should show an updated policy on the app launch and to ask to agree before continuing.

**Comment by tschubotz** [comment]
> I think having for new users "By continuing you agree with our terms" is enough. I didn't hear about legal obligations, so that we require to do it another way around.

I think Mouaz wanted to just link to the privacy policy on the app store page. That's not enough in my opinion. It has to be linked in the app.

> What we should do is whenever we update our privacy policy, we should show an updated policy on the app launch and to ask to agree before continuing.

You're probably right. I didn't yet hear complains from the data protection team about this yet. Also, what if they don't agree, then we need some logic that they can still extract e.g. a keys from their app. 
I'll clarify with the data protection team for a potential future ticket though.

**Comment by biafra23** [comment]
> > I think having for new users "By continuing you agree with our terms" is enough. I didn't hear about legal obligations, so that we require to do it another way around.
> 
> I think Mouaz wanted to just link to the privacy policy on the app store page. That's not enough in my opinion. It has to be linked in the app.
> 
> > What we should do is whenever we update our privacy policy, we should show an updated policy on the app launch and to ask to agree before continuing.
> 
> You're probably right. I didn't yet hear complains from the data protection team about this yet. Also, what if they don't agree, then we need some logic that they can still extract e.g. a keys from their app.
> I'll clarify with the data protection team for a potential future ticket though.

To be able in the future to show a changed policy we need probably some backend logic and changes to the app. 

For example: 
- We need to store in the apps preferences **when** the policy was accepted 
- How would the app know the policy has changed? Via http headers? But then the app has to fetch the pages itself. **Or** we need an additional backend endpoint

**Comment by biafra23** [comment]
@tschubotz I am not 100% certain what should happen if the user does not agree.
- We dismiss the dialog
- What should happen if the user hits the button `add safe` after that?
- Should we show the bottom sheet dialog again?

**Comment by tschubotz** [comment]
> To be able in the future to show a changed policy we need probably some backend logic and changes to the app.
> 
> For example:
> 
>     * We need to store in the apps preferences **when** the policy was accepted
> 
>     * How would the app know the policy has changed? Via http headers? But then the app has to fetch the pages itself. **Or** we need an additional backend endpoint

You are probably right. We did not have all this logic in the legacy app though and I'm not aware of any complaints from the data protection team. 
Currently, we don't intend to change the policy, so I think there is no need for advanced logic. 

I'll clarify if users have to explicitly agree again after we change or if it's legit to have something like "by continueing to use the app you implicitly agree".

> @tschubotz I am not 100% certain what should happen if the user does not agree.

If the user does not agree, then they are back on the [screen with the "get started" button](https://projects.invisionapp.com/share/Y4WYRGGQVNR#/screens/414924699) :)

cf. https://github.com/gnosis/safe/issues/292#issuecomment-620671372

**Comment by liliya-soroka** [comment]
@tschubotz , the test cases are ready for Review - https://gno.testrail.io/index.php?/suites/view/8

**Comment by liliya-soroka** [comment]
Verified
The Epic is implemented without issues for both apps
