### ISSUE TITLE
Dapp interaction via WalletConnect

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#294]
# What is this feature about? (1 sentence)
This would allow users to connect their Safe to a dapp via WalletConnect and to interact with the dapp.

# Why is it needed? What is the value? For whom do we build it?
The Safe is only really valuable when you can interact with dapps. WalletConnect is supported by lots of dapps, so that would be an easy win. Direct dapp integration via Safe apps would perhaps be nicer, but would require an integration one by one.

# High-level overview of the feature
- Wireframes: https://miro.com/app/board/o9J_kqwCrFY=/
- This feature is only available if the device is authorized to initiate txs for a Safe (#310)
- A WalletConnect connection is per Safe.
- Users can connect their Safe to a dapp by scanning a QR code.
- The process to connect a Safe via WalletConnect starts in the Safe settings
- Whenever there is a transaction to sign, a user would get a notification. Now they can reject it or propose it to the Safe.
  - After all confirmations have been made, the tx hash is returned to the dapp via WalletConnect
- When there is a WalletConnection open, the user cannot do anything else with the app (similar to how TrustWallet implements WalletConnect) until that session closed.
  - The mobile app is the connecting piece for the dapp interaction. That way the user is made aware that the mobile app has to be open in order to successfully make a WalletConnect dapp transaction.

# Tracking
todo
- Track when WalletConnect session established (incl dapp name/url?)
- Track when WalletConnect tx is triggered and submitted.
- screen tracking

**Comment by DmitryBespalov** [comment]
> The process to connect a Safe via WalletConnect starts in the Safe settings

In the legacy app we learned that it is more convenient to have the wallet connect open using a floating button to scan something, maybe that will be helpful

**Comment by tschubotz** [comment]
As first step this will be done via the web interface (gnosis/safe-react#1224) -> Closing this for now
