### ISSUE TITLE
Internal release

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#300]
# What is this feature about? (1 sentence)
This epic makes sure there is an (Gnosis) internal release that can be downloaded.

# Why is it needed? What is the value? For whom do we build it?
There is the need for Rinkeby and mainnet versions as well as production and staging versions.

# High-level overview of the feature

This epic is about Testflight/app tester releases. Not the public store releases

### iOS
- Production mainnet
  - Via Testflight, updated manually 
- Production Rinkeby
  - Via Testflight, updated manually 
- Staging Rinkeby
  - Via Testflight, updated with every commit to master
- Staging Mainnet
  - Via Testflight, updated with every commit to master
### Android
- Production mainnet
  - Via Firebase app distribution, updated manually
- Product Rinkeby
  - Via Firebase app distribution, updated manually
- Staging Rinkeby
  - Via Firebase app distribution, updated with every commit to master
- Staging Mainnet
  - Via Firebase app distribution, updated with every commit to master

**Comment by liliya-soroka** [comment]
Returned in progress for Android as we have the issues with prod apps ( rinkeby and mainnet)

**Comment by liliya-soroka** [comment]
Verified
app version 0.7.0 (100)
app version 1.12.1-72 (576)
