### ISSUE TITLE
Public Store releases

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#301]
# What is this feature about? (1 sentence)
This is the public release of the mobile apps on the stores

# Why is it needed? What is the value? For whom do we build it?
So external users can use it.

# High-level overview of the feature
- Mainnet production App is release on AppStore/ Play Store
- The apps are updated manually

See #300 for other app versions

# Store description and assets

- https://docs.google.com/spreadsheets/d/17p8V-UCyDXfoIoDAzWAzwHfOEkXxnGOzYoFr0SzjA1I/edit#gid=987901067
- https://drive.google.com/drive/folders/1h_lQvTLLqMVdDE7mYQ2eAnQXNMXUpnmS

**Comment by DmitryBespalov** [comment]
@tschubotz will we have the "beta" app in the Play Store (for Android)

**Comment by tschubotz** [comment]
Yes, would make sense I thnk

**Comment by tschubotz** [comment]
which tag/category should the apps have in the stores
which rating.
@tschubotz

**Comment by elgatovital** [comment]
Android release dependencies:

- application in play console (needs to be created)
- Title (max 50 characters)
- Short description (max 80 characters)
- Full description (max 4000 characters)
- 8 screenshots
- Content rating
- Release notes (max 500 characters)
@tschubotz

**Comment by tschubotz** [comment]
@elgatovital I think everything in that list should be covered with the 2 docs I linked in the epic. Is anything missing?

I also just created the application on the playStore and will start filling in info.

**Comment by elgatovital** [comment]
awesome! That should be it

**Comment by liliya-soroka** [comment]
Verified
the both apps are released
ios - 2.0.0 (12)
android - 1.12.1 -115
