### ISSUE TITLE
Select reference fiat currency

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#304]
# What is this feature about? (1 sentence)
This allows a user to select their preferred fiat reference currency.

# Why is it needed? What is the value? For whom do we build it?
Currently we only display USD, however we expect that there are users that prefer their local currency

# High-level overview of the feature
- The reference fiat currency is set app wide for all Safes.
- The user can select their preferred fiat currency via the app settings.
- At least the top 10 fiat currencies according to their [trade volume](https://www.countries-ofthe-world.com/most-traded-currencies.html) are supported. (I assume there is a service that does almost all - let's talk about this.)
- Fiat amounts should be formatted using the system formatter of the respective operating system (cf. https://github.com/gnosis/safe/wiki/How-to-format-amounts)
- The URL of the used service for getting the price info should be dispalyed in the advanced app settings.

_(This ticket was split out of #286 and #291)_

**Updates (30/12/2020 by @jpalvarezl )**
- User should have a clickable setting under `App Settings` in the `Settings` tab
- If there is already a currency selected, the currency code should be displayed in the settings item as shown in the mocks
- The default currency code is `USD`
- The selection screen for currencies, only allows a single currency to be selected at a time.
- The currency codes and currency names are listed separated by a hyphen
- Navigating back to `App Settings` from the currency selection screen, reflects the changes in the user settings
- `Balances` should be updated displaying the information after the change
- For balances, display the currency **symbol** when possible, otherwise default to the ISO 4217 code.
- `Total` follows the same principle as above ☝️ 

## Endpoints

Supported currency codes: https://safe-client-rinkeby.staging.gnosisdev.com/v1/balances/supported-fiat-codes
**Note:** this endpoint is only available on staging as of the writing of this update to the epic.

## UI screens

App settings: https://zpl.io/2jn91AW
Fiat selection:  https://zpl.io/VKZzjwq

## Tracking

Currency selection screen ID : `screen_settings_app_edit_fiat`

## Error description

Please refer to the `Safe Multisig Error` document and see in the screen tables the entry for `App Fiat Setting`
**End of updates (30/12/2020 by @jpalvarezl )**

# Open questions
- Which service do we use as price feed?
- **Relating update (30/12/2020 by @jpalvarezl )**: Do we use the default formatter of the system that is locale aware? An item in the refinement meeting of 07/01/2021 has been added to kick-off the discussion.

**Comment by DmitryBespalov** [comment]
We should aim to reuse the service that the web interface is using since it is solved there already.

**Comment by tschubotz** [comment]
> We should aim to reuse the service that the web interface is using since it is solved there already.

yea, probably makes sense. your call if you want to integrate that service from mobile or via our backend cc @rmeissner @Uxio0

**Comment by Uxio0** [comment]
> > We should aim to reuse the service that the web interface is using since it is solved there already.
> 
> yea, probably makes sense. your call if you want to integrate that service from mobile or via our backend cc @rmeissner @Uxio0

I think it's cleaner to do from the backend with a query param to select the currency. Currently the backend is supporting usd only

**Comment by jpalvarezl** [comment]
The gateway used this service for implementation: https://api.exchangeratesapi.io/

**Comment by tschubotz** [comment]
I think this has been implemented on both platforms by now, right? -> Moving to ready for QA cc @liliya-soroka

**Comment by liliya-soroka** [comment]
Verified
implemented on both platforms
