### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#308]
# What is this feature about? (1 sentence)
This will add dark mode support to our mobile apps

# Why is it needed? What is the value? For whom do we build it?
Basically all major operating systems on mobile and desktop support dark mode by now. This seems to be something that users appreciate.

# High-level overview of the feature
- In the app settings (#291 ), the user can select
  - Auto <- That's the default. It just uses what the operating systems is set to
  - Light 
  - Dark
- Token images should be clipped to a circle.
- Light mode: Please use transparent background for token images.
- Dark mode: Please use a white (#fffff) background for token images (Since some token images, e.g. the Gnosis images would be hard to see due to transparent parts.)

# Screens
- [Android](https://app.zeplin.io/project/5e9efc30726e106958cc43de/dashboard?seid=5ec28df08989ee476e7d1446)
- [iOS](https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/dashboard?seid=5ec28d1a05ea0849fb6793b1)

**Comment by tschubotz** [comment]
https://gnosisinc.slack.com/archives/C63LQTGNB/p1586956264104000

**Comment by elgatovital** [comment]
do we have color definitions & styles for dark mode? If not when can we expect them? @posthnikova

**Comment by posthnikova** [comment]
@elgatovital Dark mode is not an immediate priority, it's not in the phase 1 issues.

**Comment by posthnikova** [comment]
Open question is how we display token logos, some of them look bad on dark background.
![image](https://user-images.githubusercontent.com/45787536/81941136-b3408700-95f8-11ea-98ab-325c9a11ab8d.png)
