### ISSUE TITLE
View transaction details

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#311]
# What is this feature about? (1 sentence)
This allows users to see details of incoming and outgoing transactions.

# Why is it needed? What is the value? For whom do we build it?
In order to know what is happening with their Safe, a user needs to be able to inspect all transaction details

# High-level overview of the feature

### Transaction list:
Part of #289 

### Transaction details:
- User sees the following details:
  - Sender (address & identicon, tapping copies the address to clipboard)
  - Recipient (address & identicon, tapping copies the address to clipboard)
  - ETH value
  - Data (Show only number of bytes by default, user can view full data if desired)
  - Submission date
  - Execution date
  - Type of operation (call or delegatecall)
  - Transaction hash (User can copy it)
  - Status (See section below)
  - ~Network fee~ (Leave this one out since there could be different types and we don't need this complexity right now, cf. [Slack thread](https://gnosisinc.slack.com/archives/G9GEEHY79/p1585744219049200))
- User can open the tx on etherscan.
- If a transaction is an outgoing tx show:
  - Which of the owners confirmed/rejected
- (Edit June 15) User can pull to refresh the data on the screen. (cf. https://github.com/gnosis/safe/wiki/Network-requests-and-no-internet-connection)

### Transaction decoding:
- Decode the following transactions by showing details:
  - ERC20 token transfers
  - Safe settings changes (addOwner, removeOwner, swapOwner, changeMastercopy)

#### Transaction status
- See https://github.com/gnosis/safe/wiki/Safe-transaction-states

### Confirmations, rejections & executions
- Sorted by time, ascending.
- [iOS](https://zpl.io/ag4pqNZ), [Android](https://zpl.io/VKZvYdA)
- Figuring out rejections and cancel transactions is quite tedious. Rejections of 1 transaction are technically confirmations of a "cancel" transaction 🤯. Hence we decided to not show rejections, yet, just confirmations. On the transaction list we show all transactions, i.e. including the "0 ETH, no data" txs (which are "cancel" transactions). We take the following simplifications:

##### Tx executed (successful or failed)

- Confirmations list includes the following:
  - Created
  - Confirmed (once for every owner that confirmed)
  - Executed/failed (Incl. executor address)

##### Tx not executed, but there is another executed transaction with the same or higher nonce.

- That means this txs was implicitly cancelled since its nonce has been "consumed" by the executed tx.
- Confirmations list includes the following:
  - Created
  - Confirmed (once for every owner that confirmed)
  - Cancelled (No address connected here)

##### Tx not executed, but there is **no** other executed transaction with the same or higher nonce.

- That means the tx is `Waiting for confirmations`, `Waiting for execution` or `Pending`.
- Confirmations list includes the following for `Waiting for confirmations`:
  - Created
  - Confirmed (once for every owner that confirmed)
  - Greyed out empty `execute` row
- Confirmations list includes the following for `Waiting for execution`:
  - Created
  - Confirmed (once for every owner that confirmed)
  - Green empty `execute` row
- Confirmations list includes the following for `Pending`:
  - `Pending` is local to a device, i.e. only displayed when a txs was submitted (executed) from a device. Since we don't have this on mobile yet, **we don't need that state**.

# Tracking 
_(Added June 29)_
- Add screen tracking for (cf. [wiki](https://github.com/gnosis/safe/wiki/Tracking))
  - `transactions_details`
  - `transactions_details_advanced`

# Updates
- June 18: The "creator" address is not supplied/implemented by the backend, so it won't be displayed in the confirmations list. Removed the (Incl. creator address) from the text above. (Dima)
- June 18: The "executor" is taken from the backend response's "executor" field.
- June 29: Add screen tracking info (taken out of #299) 
- August 20: Remove "copy data"

**Comment by biafra23** [comment]
@tschubotz What are the rules regarding the data section? Should it always be there when data is not empty or does it depend on the txtype?

Do we show the data for modify settings?

**Comment by biafra23** [comment]
@tschubotz Regarding collapsing and expanding the data section:
What should be the area that collapses/expands the data section? 

IMHO it should be the biggest area possible. i.e. the whole section.

**Comment by tschubotz** [comment]
> @tschubotz Regarding collapsing and expanding the data section:
> What should be the area that collapses/expands the data section?
> 
> IMHO it should be the biggest area possible. i.e. the whole section.

You mean which area should be tapable? I agree, the biggest area possible, i.e. the whole section. (Any objections @posthnikova ?)



> @tschubotz What are the rules regarding the data section? Should it always be there when data is not empty or does it depend on the txtype?
> 
> Do we show the data for modify settings?
> 
> Regarding transfers: Every token transfer has a non-null data section.
> Regarding settings changes: Every settings change has a non-null data section.

I guess there are arguments for either way. Let's not show the data section for pure transfers and settings changes since that's what iOS has implemented already according to the Zeplin screens (e.g. https://zpl.io/2jnMKAr or https://zpl.io/aXAJd6E) (@posthnikova that was the intention so far, right?)

**Comment by biafra23** [comment]
> I guess there are arguments for either way. Let's not show the data section for pure transfers and settings changes since that's what iOS has implemented already according to the Zeplin screens (e.g. https://zpl.io/2jnMKAr or https://zpl.io/aXAJd6E) (@posthnikova that was the intention so far, right?)

What about https://zpl.io/bJmODxx (incoming custom transfer)

**Comment by tschubotz** [comment]
> What about https://zpl.io/bJmODxx (incoming custom transfer)?

Do we even get `data` from our backend for incoming ETH transfers?

Is that what you are asking? If not, could you please elaborate on your question?

**Comment by biafra23** [comment]
This design seems to be a custom transaction that also has a ETH (probably should not be Zero) value sent with it. Not sure how the client gateway would classify it.

**Comment by posthnikova** [comment]
> You mean which area should be tapable? I agree, the biggest area possible, i.e. the whole section. (Any objections @posthnikova ?)

@tschubotz @biafra23 Yes, the whole horizontal area https://prnt.sc/tytyby.

> Let's not show the data section for pure transfers and settings changes since that's what iOS has implemented already according to the Zeplin screens (e.g. https://zpl.io/2jnMKAr or https://zpl.io/aXAJd6E) (@posthnikova that was the intention so far, right?)

Web interface doesn't show data for settings changes and pure transfers, let's not change this.

**Comment by biafra23** [comment]
What is a pure Transfer? Even more important: What is a non pure Transfer? The client gateway returns Transfers, Custom transactions and Settings Changes.

You probably refer to a custom transaction with a value not zero. This would probably just  be a custom transaction.

**Comment by tschubotz** [comment]
> What is a pure Transfer? 

An ETH transfer without any data. (value>0, data=0x)
or an ERC 20 token transfer without any other side effects

> Even more important: What is a non pure Transfer? 

A smart contract interaction. 

> You probably refer to a custom transaction with a value not zero. This would probably just be a custom transaction.

yes but value can also be zero.

The problem is that ERC20 token transfers also technically also contract interactions. In order to differentiate txs which just transfer tokens, nothing else from txs which as a side effect also transfer tokens, we used the phrase "pure transfers". 
Let me know if there's any better terminology, happy to adapt.

**Comment by liliya-soroka** [comment]
Verified
app version 
android 1.12.1 - 98
ios - 2.0.0 ( 10)
Note
client gateway is used in the android app only
