### ISSUE TITLE
Intercom messenger

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#312]
_wip, tbd if we really want that._

# What is this feature about? (1 sentence)
This would allow users to get support via Intercom directly via their Safe app.

# Why is it needed? What is the value? For whom do we build it?
- Intercom works quite good in the web interface.
- We have our help center and idea board on Intercom.
- User wouldn't need to create a Discord/Telegram account
- We can streamline support

# High-level overview of the feature
- In settings, users can start a conversation with us via Intercom

# Things to consider
- Do we really want the Intercom SDK inside our app?
-

**Comment by biafra23** [comment]
Research needed:
- Is the Intercom SDK open source on Android and IOS?
-> yes: https://github.com/intercom/intercom-ios
- Is it possible to use an external intercom app and launch it via intent?

**Comment by sche** [comment]
I am closing this one in favour of #500
