### ISSUE TITLE
Display creation transaction

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#315]
# What is this feature about? (1 sentence)
This will display the creation transactions in the list of transactions of a Safe.

# Why is it needed? What is the value? For whom do we build it?
There is a transaction list (#289), however the creation transaction is not part of that list yet. But it is something that users expect to see.

Also the web interface shows that info (gnosis/safe-react#554)

# High-level overview of the feature

## Transaction List
- There is an entry for this transaction on the transaction list.
- The creation transaction is shown as the last transaction in the transaction list. In case of pagination, that would be after all transactions of the last page of the list.
- Pull to refresh should not affect the display of the creation transaction, i.e. it should be displayed as all other transactions in the list
- **(New)** If the safe creation transaction is not available (not found), then do not show it. The user should not see any error in that case.

## Transaction Details
- The details page shows the following details:
  - Tx hash (Link to Etherscan)
  - ~Owner addresses (Link to Etherscan, can be null if setupData is not available)~
  - ~Required confirmations (n out of m, can be null if setupData is not available)~
  - Creator address (Link to Etherscan)
  - Mastercopy used (If available, can be null for some Safes). If available, then contract version should be displayed similar to the Safes settings
  - Factory used (If available, can be null for some Safes)
  - ~Setup data (If available, can be null for some Safes)~
  - **(New)** Created date
  - **NOTE: not updated as of 03.08.2020 ** Screen: [iOS](https://zpl.io/br5pPJ5), [Android](https://zpl.io/br5pPJ5)
- Pull to refresh on the transaction details is not needed, as we assume that the transaction information is not going to change once we have it.

# Data Source
There is an endpoint for this info: https://safe-transaction.gnosis.io/api/v1/safes/0xA063Cb7CFd8E57c30c788A0572CBbf2129ae56B6/creation/

Request:
```shell
curl -X GET "https://safe-transaction.staging.gnosisdev.com/api/v1/safes/0xA063Cb7CFd8E57c30c788A0572CBbf2129ae56B6/creation/"
```

Response:
```json
{
  "created": "2020-03-23T15:23:53Z",
  "creator": "0x740a98F8f4fAe0986FB3264Fe4aaCf94ac1EE96f",
  "transactionHash": "0x8aa700d5e7bad86ddcb6f3b0491954d36dfad7957be573cf7ec8b0173cb89cd3",
  "factoryAddress": "0x76E2cFc1F5Fa8F6a5b3fC4c8F4788F0116861F9B",
  "masterCopy": "0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F",
  "setupData": "0xb63e800d000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000ec9279204c734e335f8b7f7f660de19968f15b990000000000000000000000000000000000000000000000000000000000000000",
  "dataDecoded": {
    "method": "setup",
    "parameters": [
      {
        "name": "_owners",
        "type": "address[]",
        "value": [
          "0xEc9279204C734E335f8b7f7F660dE19968F15b99"
        ]
      },
      {
        "name": "_threshold",
        "type": "uint256",
        "value": "1"
      },
      {
        "name": "to",
        "type": "address",
        "value": "0x0000000000000000000000000000000000000000"
      },
      {
        "name": "data",
        "type": "bytes",
        "value": "0x"
      },
      {
        "name": "fallbackHandler",
        "type": "address",
        "value": "0x0000000000000000000000000000000000000000"
      },
      {
        "name": "paymentToken",
        "type": "address",
        "value": "0x0000000000000000000000000000000000000000"
      },
      {
        "name": "payment",
        "type": "uint256",
        "value": "0"
      },
      {
        "name": "paymentReceiver",
        "type": "address",
        "value": "0x0000000000000000000000000000000000000000"
      }
    ]
  }
}
```

**TODO:** check the response for different safe contract versions, i.e. what will be the parameters for versions 1.0.0, 1.1.0, and 1.1.1?

# Rough changes to the UI design
![Creation Transaction Designs.001.jpeg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/cdbc35a8-3abc-4def-9715-7c72585fa9e7)

# Updates
- Jul 6 Dima: added the example request and response
- Jul 30 Tobi: In order to stay in sync with the web, **Please leave out owner, threshold and setup data**. We have not received user feedback indicating that this is info that we need, hence not required currently, imo.
- Jul 30 Tobi: Add links to Zeplin screen
- Jul 30 Tobi: Add link to respective safe-react ticket.
- Aug 3 Dima:  Added "created date" to the list of transaction details information

**Comment by jpalvarezl** [comment]
> * There is an entry for this transaction on the transaction list.

Hi @tschubotz 

We would need more info on how to access this. Is this transaction passed as part of the rest of the list? Does it hold a special position in the list? Maybe it would be good to consider, extracting this from the transaction list and putting it in the `Safe Settings` ?

Considering that the transaction list is paginated, positioning this item in a particular place could be tricky depending on the requirement

**Comment by tschubotz** [comment]
I understood from @rmeissner and @Uxio0 that the creation transaction will not be part of the "regular" transactions endpoint.

In the UI, the transaction history is sorted by execution date (desc), right? So ideally that creation transaction would be at the proper spot in the list according to it's execution date. Would that be possible?

> Maybe it would be good to consider, extracting this from the transaction list and putting it in the `Safe Settings` ?

I'm hesitant about this since the configuration of the safe could have changed since the creation, so to me that fits in more logically into a historic view, i.e the transaction list.

**Comment by rmeissner** [comment]
I am kind of against putting this in the transaction list endpoint, as it is no Safe transaction (and no asset transfer), but I can see how this would make it a little easier on the clients (but it should also be easy to just insert it maually, as we don't support custom sorting right now). Up to @Uxio0 If we want that we should add it as a new type in the new creation endpoint, but it would be interesting to know what information you want to have there.

I will comment on the backend issue.

**Comment by Uxio0** [comment]
> I am kind of against putting this in the transaction list endpoint, as it is no Safe transaction (and no asset transfer), but I can see how this would make it a little easier on the clients (but it should also be easy to just insert it maually, as we don't support custom sorting right now). Up to @Uxio0 If we want that we should add it as a new type in the new creation endpoint, but it would be interesting to know what information you want to have there.

I can understand why we want it on the UX, but it doesn't make sense to add it to the txs endpoint, as it not really a Safe transaction and it's not a big overhead to query the creation endpoint. Also, creation endpoint is cached as it doesn't change.

Also, maybe this tx should have an special position instead of being at the bottom of the transaction list. What happens if the user has +1000 transactions, does he need to navigate to the bottom and query multiple transaction pages until he gets to the transaction?

**Comment by DmitryBespalov** [comment]
@tschubotz @rmeissner @Uxio0 can we add the need for the "dataDecoded" parameter for the "setupData" in the response? (https://safe-transaction.gnosis.io/api/v1/safes/0xA063Cb7CFd8E57c30c788A0572CBbf2129ae56B6/creation/)

**Comment by Uxio0** [comment]
Here you have @DmitryBespalov https://safe-transaction.mainnet.staging.gnosisdev.com/api/v1/safes/0xA063Cb7CFd8E57c30c788A0572CBbf2129ae56B6/creation/

**Comment by DmitryBespalov** [comment]
Hi all, @rmeissner @jpalvarezl  I have a question: will this be implemented by the client gateway service or we need to take it like it is now, i.e. do we need  to enhance the /all-transactions endpoint on the clients with the additional request to the /creation/ endpoint?

**Comment by rmeissner** [comment]
This can be handled by the client gateway. Could you create an issue there?

**Comment by liliya-soroka** [comment]
Verified
ios app version 2.0.0 ( 10)
android app version 2.0.0 (14)
