### ISSUE TITLE
Allow disabling of tracking

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#316]
# What is this feature about? (1 sentence)
This allows users to use the mobile app without user tracking from our side.

# Why is it needed? What is the value? For whom do we build it?
While we don't track any personal info (such as addresses e.g.), we still track anonymized user behavior. Some people would like to turn that off.

# High-level overview of the feature

- Crashlytics is staying
- If Agreed without sharing usage data or disabled in settings, then screen tracking and all other tracking can be disabled.
- For existing users
  - Toggle in settings should be ON after the update
  - The tracking should be enabled
- Note: app restart is not required to disable/enable analytics.

- Zeplin: TBD

# Misc

- Kick off doc: https://docs.google.com/document/d/1TVYoOxJXtllH-0z1t0JZo3QIlxDeoFzgorZAxQhhr-k/edit#
- For reference, this is how web asks for tracking: 
![image](https://user-images.githubusercontent.com/1380529/111275933-04654100-8637-11eb-9104-74e68423d410.png)

**Comment by DmitryBespalov** [comment]
We have a user request for this feature.

**Comment by DmitryBespalov** [comment]
Here're proposed mockups:

#### Terms screen (fresh install)
![tracking-terms.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/cf378068-364c-464b-9906-3daf4385feb6)

#### Advanced App Settings
![tracking-advanced-app-settings.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/edb0b41d-8e9f-419b-920f-788e79c940f2)

- For existing users that will be updating from previous app version we don't change anything - there'll be release notes and they could go to Advanced settings to stop sharing analytics. 
- The link in the settings can lead to privacy policy or to a help article (new article needed).

**Comment by sche** [comment]
lgtm. I would make share analytics description more encouraging :)

**Comment by DmitryBespalov** [comment]
@sche @lukasschor @KristinaMayman 

_By sharing analytics with Gnosis, you are helping us to improve the app with anonymized app usage data. <a>What data is shared?</a>_

**Comment by KristinaMayman** [comment]
I think that's good. No need for "to" though, can be just "helping us improve".

**Comment by tschubotz** [comment]
@DmitryBespalov I like the proposed screens as well! 

Instead of "analytics" , how about "usage data"? That would be a bit more precise, i.e. on the initial screen the main CTA would say "Agree and share usage data". 

Just an idea, I'm fine either way

**Comment by DmitryBespalov** [comment]
@tschubotz so, it would look like:

Terms:
- _Agree and Share Usage Data_
- _Agree without Sharing Usage Data_

Settings:
- _Share Usage Data_
- _By sharing usage data with Gnosis, you are helping us improve the app with anonymized app usage data. <a>What data is shared?</a>_

**Comment by tschubotz** [comment]
@DmitryBespalov yep that's what I was thinking. 

I have one more suggestion to reduce the amount of text:

On the "terms" screen during onboarding, instead of _Agree and Share Usage Data_ I would just write _Agree_ since we explain in the bullet points above what exactly it means. - what do you think?

So the 2 options would be 

- _Agree_
- _Agree without Sharing Usage Data_

What do you think?

**Comment by DmitryBespalov** [comment]
sounds good to me

**Comment by liliya-soroka** [comment]
Opened discussion - https://gnosisinc.slack.com/archives/CQB729LLF/p1620746364082800

**Comment by liliya-soroka** [comment]
Verified
ios app version 2.16.0 (430)
android - app version 2.16.0 -2631rc
