### ISSUE TITLE
Allow screenshots on Android Rinkeby/staging builds

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#317]
# What is this feature about? (1 sentence)
This will allow screenshots on Rinkeby/staging builds. 

# Why is it needed? What is the value? For whom do we build it?
On Android, it's possible that 3rd party apps record the screen. That screen could potentially contain confidential info such as private keys. Hence we block screenshots by default.

# High-level overview of the feature
- By default, screenshots are disabled.
- User can enable/disable screenshots via app settings
  - There is a warning before enabling screenshots
- It is not possible to enable screenshots for production mainnet apps!

**Comment by Uxio0** [comment]
The setting for allowing screenshots will be very useful for debugging. Record will also work with the screenshots permission?

**Comment by tschubotz** [comment]
> The setting for allowing screenshots will be very useful for debugging. 

Yes, I remember that this was feedback we got for the legacy app 😬 

> Record will also work with the screenshots permission?

I think recording and screenshot is the same permission.

**Comment by tschubotz** [comment]
Closing this since the functionality existing on staging builds, already
