### ISSUE TITLE
Data (re)loading states

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#319]
# What is this feature about? (1 sentence)
This will add proper UI and UX when loading and reloading data, including possible error states

# Why is it needed? What is the value? For whom do we build it?
We load data in various places inside the app. Since we are on mobile, it's likely that sometimes the Internet connection is weak, requests time out or our backend returns errors. We should handle this properly.

# High-level overview of the feature
- Please refer to the [wiki](https://github.com/gnosis/safe/wiki/Network-requests-and-no-internet-connection) for when and what data should be reloaded.

#### Automatic loading: 
_(e.g. When the app starts or comes in foreground from background or when the respective screen is opened etc.)_

- Show native OS progress indicators. It disappears after successful request.
- [iOS](https://zpl.io/aMJWQk3): Behaves like [standard iOS progress indicator](https://developer.apple.com/design/human-interface-guidelines/ios/controls/progress-indicators/)
- [Android](https://zpl.io/2pGvzrj): Behaves like Material design [circular progress indicator](https://material.io/components/progress-indicators#usage)

#### Manual reloading

_(Pull to refresh)_ 
- Show native OS progress indicators. It disappears after successful request.
- [iOS](https://zpl.io/VqjWqrN): [standard iOS pull to refresh](https://developer.apple.com/design/human-interface-guidelines/ios/controls/refresh-content-controls/), i.e. content shifts down.
- [Android](https://zpl.io/Vxx0gnR): Like Material design [swipe to refresh](https://material.io/design/platform-guidance/android-swipe-to-refresh.html#usage)

#### Error states
_(No Internet, request timed out, server error)_

- When data was already loaded successfullly before
- When data was not loaded before, show full screen persistent error message: [iOS](https://zpl.io/bLlPkeQ) [Android](https://zpl.io/VDJA5P3)
- In any way, show custom 'snackbar' above the tab bar which disappears after 4 sec. 
  - On screens without the tab bar - show on bottom end of screen (confirmed in gnosis/safe-ios#313).
  - Snackbar hides also when user pulls to refresh
  - When after the new pull to refresh there is still no internet, the snackbar appears again.
- Snackbar shows respective error message ("No Internet connection", "Request timed out after 30s" or "Server error"): See Zeplin
- (June 29) ~According to https://github.com/gnosis/safe/wiki/Network-requests-and-no-internet-connection the clients should subscribe to network connection changes and display "no internet" or reload data accordingly.~
- (24.06.2020): If there are multiple messages to show in the snack bar, only one message is shown at all times, so multiple messages shown consecutively (according to /gnosis/safe-ios#312)
- (June 29) According to [wiki](https://github.com/gnosis/safe/wiki/Errors%2C-Network-requests-and-no-internet-connection): 
  - If there is a text input - then errors are in the error label on/near the text input fields.
  - In lists / in settings:
    - Error during initial loading  -> "No data" screen + timed snackbar message
    - Error during pull to refresh -> same data stays, + timed snackbar message
    - Error during other network request -> keep screen state + timed snackbar message
  - "no internet connection" counts as error - It is show upon the "data reload event" or upon "user action", i.e. not upon "network availability" events

# Screens
- [iOS](https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/dashboard?seid=5ebbb404e1182e7899998902)
- [Android](https://app.zeplin.io/project/5e9efc30726e106958cc43de/dashboard?seid=5ebbb340cea0c078fd9c9e17)

# Updates
- 24.06.2020 (Dima): Added description on how to handle multiple notifications - show them consecutively.
- June 29 (Tobi): Adjustments regarding errors after backlog refinement: No persistent snackbar, no Internet counts as error.

**Comment by jpalvarezl** [comment]
No internet connection is only checked upon a request. Is this assumption correct?

**Comment by tschubotz** [comment]
Moved the discussion to https://gnosisinc.slack.com/archives/C63LQTGNB/p1592296491004400 will update here once it concluded.

**Comment by tschubotz** [comment]
In https://github.com/gnosis/safe/wiki/Network-requests-and-no-internet-connection we discussed to reload data when network becomes available again.

Hence let’s subscribe to the network changes and display the no internet connection info accordingly. :) will update the epic also to reflect this.

**Comment by liliya-soroka** [comment]
Waiting for the refinement meetings results

**Comment by liliya-soroka** [comment]
Verified
the data-reloading will be aligned between the platforms and will be re-implemented in the new epic
This epic can be closed
