### ISSUE TITLE
Public beta release

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#321]
# What is this feature about? (1 sentence)
This will allow external users to download the Safe Multisig webapp beta app.

# Why is it needed? What is the value? For whom do we build it?
Beta apps

# High-level overview of the feature
- iOS (mainnet, production) app is available via Testflight. There is an invite link that we can share
- iOS (rinkeby, production) app is available via Testflight. There is an invite link that we can share
- Android (mainnet, production) app is available via the PlayStore as beta. There is an invite link that we can share
- Android (rinkeby, production)  app is available via Firebase app distribution. There is an invite link that we can share
- I think the 4 beta apps should be same ones from  #300. There is no need to differentiate internal and external production betas.

**Comment by DmitryBespalov** [comment]
@tschubotz for Android, this should mention the Play Store and preparation, right?

**Comment by tschubotz** [comment]
Good question. A PlayStore beta would make it easier to release the proper app later on 🤔 
Maybe that's the better way to go. 

Yes, I'll change it.
