### ISSUE TITLE
Note on Multisig Transactions Parsing for /all-transactions/ endpoint in safe-transactions service

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe#324]
# Overview
The `/safes/{address}/all-transactions` endpoint returns all transactions known to the backend service.

The transactions may originate from the user's safe or from external transaction events (from other users or smart contracts activity).

The endpoint returns a paginated list of transaction (`tx` for a shorthand) objects.

Example request: 
https://safe-transaction.staging.gnosisdev.com/api/v1/safes/0x441E604Ad49602c0B9C0B08D0781eCF96740786a/all-transactions/?limit=100

## Linked issues
- https://github.com/gnosis/safe-transaction-service/issues/102
- https://github.com/gnosis/safe-transaction-service/issues/101
- https://github.com/gnosis/safe-transaction-service/issues/100
- https://github.com/gnosis/safe-transaction-service/issues/99
- https://github.com/gnosis/safe-transaction-service/issues/97
- https://github.com/gnosis/safe-transaction-service/issues/96

# Response meaning
## `tx.type` is `MODULE_TRANSACTION`
For now, we ignore this type of transaction and not show it in the user interface.

## `tx.type` is `ETHEREUM_TRANSACTION`
These are external transactions and they are already executed.

For each such transaction, we look into a `tx.transfers` array.

```
    if transfers is not empty
        each transfer is a new UI cell
    if transfers is empty or null
        if data is not nulll 
            then it is custom transaction
        else data is null, 
            so it is ETH transfer.
            "tx.value" can be null or absent - then treat it as 0.
```
Each transfer represents a separate user interface row in the transaction list. A transfer may be incoming, or outgoing - you need to see at the `transfer.to` and `transfer.from` addresses and see if one of them is a `tx.safe` address. 

`transfer.to` is a recipient address, and `transfer.from` is a sender address of that transfer.

## `tx.type` is `MULTISIG_TRANSACTION`

These are transactions originating from the user's safe. Each such transaction is represented by a single row in a transactions list user interface.

They include transactions that are already executed (`tx.isExecuted` is `true`), transactions that were not executed (`isExecuted` is false) but superseeded by other executed transactions (we call them cancelled transactions), and transactions that are not yet executed.

Due to the technical details of the working with the blockchain data structures, for now, we must not rely on the `transfers` array that we get in the transaction object, but rather classify the transaction to one of the user interface types based on the transaction's properties.

**That is, we ignore the `tx.transfers` for the transactions with tx.type  `MULTISIG_TRANSACTION`**

### `ETH` transfer transactions
All conditions must be  met:
```
    tx.data == null
    tx.operation == 0
    tx.value == any
```

These will be ether transfers. The `tx.to` is recipient, the `tx.safe` is sender.

**In all other cases the `tx.data` is not `null`, it is present.**

The data is a hex-string serialized binary data. If the data is present, we expect backend to also provide the `tx.dataDecoded` object with the details of the method call that this transaction is invoking. 

**if `tx.dataDecoded == null` or empty, then the transaction is Custom transaction**

### Safe Setting Changes
All conditions must be met:
```
    tx.to == safe address
    tx.operation == 0
    tx.dataDecoded.method is one of:
        changeMasterCopy
        setFallbackHandler
        addOwnerWithThreshold
        removeOwner
        swapOwner
        changeThreshold
        enableModule
        disableModule
```
Every interaction with the aforementioned methods of the Safe smart contract requires the smart contract itself to execute it, that is why we check that the `tx.to` is the `tx.safe` itself.

### ERC20 Transfers
All conditions must be met:
```
    tx.operation == 0
    tx.contractInfo.type == "ERC20"
    tx.dataDecoded.method is one of:
        transfer
        transferFrom
```

**If the `tx.contractInfo` is not present, treat the transaction as Custom transaction**

Because this is an etherum transaction directed at the token smart contract, the `tx.to` will be the token contract's address, and not the recipient of tokens.

To get the recipient of tokens, as well as amount transferred, you need to look at the parameters of the methods.

```
    function transfer(address _to, uint256 _value) public returns (bool success)
```
For this method, the `tx.safe` is the sender, the `_to` parameter address is the recipient, and the `_value` is the amount of tokens.

To get the information about the token's `symbol`, `decimals`, `name`, etc. we look at the `tx.contractInfo` object.

```
    function transferFrom(address _from, address _to, uint256 _value) public returns (bool success)
```
For this method, the `_from` parameter address is the sender, the `_to` parameter address is the recipient, and the `value` is the amount in the token's basic units.

To get the information about the token's `symbol`, `decimals`, `name`, etc. we look at the `tx.contractInfo` object.

### ERC721 Transfers
All conditions must be met:
```
    tx.operation == 0
    tx.contractInfo.type == "ERC721"
    tx.dataDecoded.method is one of:
        safeTransferFrom
        transferFrom
```

**If the `tx.contractInfo` is not present, treat the transaction as Custom transaction**

```
    function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) external payable;
    function safeTransferFrom(address _from, address _to, uint256 _tokenId) external payable;
    function transferFrom(address _from, address _to, uint256 _tokenId) external payable;
```
There are 3 possible methods. For each of them, the `_from` parameter is sender, the `_to` is recipient, **the amount is 1, since this transfers only 1 token** with specific `_tokenId`.

### Custom transaction
Everything else is treated as a Custom transaction. 

The `tx.to` is recipient, the `tx.data` is the data sent along with the transaction, the `tx.value` is ETH value transferred with the transaction (can be positive number).

### Getting token info from the Safe Relay Service
`/v1/tokens/?limit=5000` returns all supported tokens

`/v1/tokens/{address}` returns only single token

As of now (June 4, 2020), they are all ERC20 tokens..

Possible change is to return `"decimals": null` to mark token as ERC721 token.

### Getting token info from the contract itself using Infura (Ethereum JSON RPC)

Send an eth_call() JSON RPC to the address of the contract (tx.to)
that executes the following methods and you will get back the result (possibly).

Make sure to check the response for overflows or value type incompatibility because
user can use some sh*tcoins that can break the interface.

- https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call
- https://eips.ethereum.org/EIPS/eip-20
- https://eips.ethereum.org/EIPS/eip-721

```
    to: tx.to
    data: method call
```

Here are the method calls:
`"symbol()"` - return type `string` - will be the symbol

`"name()"` - return type `string` - name of the token

`"decimals()"`  - return type `uint8` (check for overflows 😉) -> decimals for the token.
    
**open question whether to treat the 0 value as the ERC721 indication?** because some ERC20 tokens are using 0 decimals as a legitimate value.

`"tokenURI(uint256)"` - argument is the `_tokenId` of type `uint256` that you get from the `transferFrom` or from the `safeTransferFrom` method arguments of the ERC721 transaction's `dataDecoded`.

## What about transaction status?
This is aligned and defined in the doc here: 
https://github.com/gnosis/safe/wiki/Transaction-app-types-and-mapping-from-json-to-UI-layer

**Comment by jpalvarezl** [comment]
By Uxio:
> Nice!! Some things:
> - The transactions may originate from the user's safe or from external transaction events (from other users or smart contracts activity).. And remember that module transactions are included too, so allowed modules for that Safe are a source of transactions with it's own MODULE_TRANSACTION type.
> - For ERC721, in dataDecoded expect tokenId to be named value, as in ERC20. The reason is that the signatures collide and ERC20 has preference (as there are more ERC20 tokens than ERC721 so I configured it that way)

By Richard:
> Personal comment for the fallback if contractInfo is not present: I would not implement any fallback in the client. If the backend cannot retrieve the information from the relay service or from on-chain, the clients will most likely also not be able to do so ;)

**Comment by DmitryBespalov** [comment]
Question about `dataDecoded`. With the recent changes, the "value" can be an array of values. For one, those values are not stringly typed (they should be, because they can overflow 64-bit integer); and in general, should it be dynamic type, like string, or array of strings, or array of array of strings or rather having an array serialized in string.

Take the following transaction as an example:
```
    {
      "safe": "0x840018fFfbdC9f2Ee8DA5D647f66afDAAebde080",
      "to": "0xE7640763CDecd3dfEA63846AFC0F62a1A3BB6063",
      "value": "0",
      "data": "0x15bd76110000000000000000000000000000000000000000000000000000000000000040fffffffffffffffffffffffffffffffffffffffffffffffffffc72815b397fff0000000000000000000000000000000000000000000000000000000000000002fffffffffffffffffffffffffffffffffffffffffffffffffffa9c29f1027dad0000000000000000000000000000000000000000000000000000000000000000",
      "operation": 0,
      "gasToken": "0x0000000000000000000000000000000000000000",
      "safeTxGas": 279730,
      "baseGas": 58088,
      "gasPrice": "10000000001",
      "refundReceiver": "0x0000000000000000000000000000000000000000",
      "nonce": 5,
      "executionDate": "2020-01-24T15:25:10Z",
      "submissionDate": "2020-01-24T15:25:10Z",
      "modified": "2020-01-24T15:25:10Z",
      "blockNumber": 5849300,
      "transactionHash": "0x82ad243822b5ae174ec3fa976da8ff2d8d12dc620af1c62208168ac3aa92eb72",
      "safeTxHash": "0x26946de8fb28a04d857de7e043e9689c5de0ebbc6e49fc726b2c0921b38c7e82",
      "executor": "0x07fd2865c8DE725B4e1f4E2B72E5c654baA7c4b3",
      "isExecuted": true,
      "isSuccessful": true,
      "ethGasPrice": "10000000001",
      "gasUsed": 238140,
      "fee": "2381400000238140",
      "origin": null,
      "dataDecoded": {
        "method": "trade",
        "parameters": [
          {
            "name": "outcomeTokenAmounts",
            "type": "int256[]",
            "value": [
              -1517145909199443,
              0
            ]
          },
          {
            "name": "collateralLimit",
            "type": "int256",
            "value": "-1000000000000001"
          }
        ]
      },
      "confirmationsRequired": 1,
      "confirmations": [
        {
          "owner": "0xbadD9cb3c928af9ad7052aB0D636D2dE95D419bC",
          "submissionDate": "2020-03-13T18:45:24.107917Z",
          "transactionHash": null,
          "confirmationType": "CONFIRMATION",
          "signature": "0x05da8a3ad57f69ecd67184549439c1a085d289c7d46bcbcb1687077aac3084d96761d0c655ec476c4cfe31f65916c2272e8dbb00a5f18cd70383e7ef35957d1c1b",
          "signatureType": "EOA"
        }
      ],
      "signatures": "0x05da8a3ad57f69ecd67184549439c1a085d289c7d46bcbcb1687077aac3084d96761d0c655ec476c4cfe31f65916c2272e8dbb00a5f18cd70383e7ef35957d1c1b",
      "transfers": [
        {
          "type": "ERC20_TRANSFER",
          "executionDate": "2020-01-24T15:25:10Z",
          "blockNumber": 5849300,
          "transactionHash": "0x82ad243822b5ae174ec3fa976da8ff2d8d12dc620af1c62208168ac3aa92eb72",
          "to": "0x840018fFfbdC9f2Ee8DA5D647f66afDAAebde080",
          "value": "1000000000000001",
          "tokenId": null,
          "tokenAddress": "0xc778417E063141139Fce010982780140Aa0cD5Ab",
          "from": "0xE7640763CDecd3dfEA63846AFC0F62a1A3BB6063"
        },
        {
          "type": "ETHER_TRANSFER",
          "executionDate": "2020-01-24T15:25:10Z",
          "blockNumber": 5849300,
          "transactionHash": "0x82ad243822b5ae174ec3fa976da8ff2d8d12dc620af1c62208168ac3aa92eb72",
          "to": "0x07fd2865c8DE725B4e1f4E2B72E5c654baA7c4b3",
          "value": "2771230000277123",
          "tokenId": null,
          "tokenAddress": null,
          "from": "0x840018fFfbdC9f2Ee8DA5D647f66afDAAebde080"
        }
      ],
      "txType": "MULTISIG_TRANSACTION"
    },
```

The `dataDecoded.parameters[0].value` is of type `int256[]`. What would it look like for a value of type `int256[][]`? Should we support nesting? Should we just serialize everything in a string?

This highly depends on the backend serialization implementation, so let's just put the spec/requirement somewhere.

**Comment by Uxio0** [comment]
> Question about `dataDecoded`. With the recent changes, the "value" can be an array of values. For one, those values are not stringly typed (they should be, because they can overflow 64-bit integer); and in general, should it be dynamic type, like string, or array of strings, or array of array of strings or rather having an array serialized in string.

I didn't realise this could happen. I guess the solution for now will be recursively decoding the parameters, so it would become a `list of strings`, or a `list of lists of strings`

**Comment by biafra23** [comment]
>     function transferFrom(address _from, address _to, uint256 _tokenId) external payable;

@DmitryBespalov Regarding parameter names. Why do the have an "_" prefix in your examples, when the backend returns them without an "_"? Can I remove these underscores?

**Comment by DmitryBespalov** [comment]
@biafra23 I have added the parameter names from the standard spec, not from the backend response.  Sure you can remove the underscore, but what is important is the position of the parameter and its type, the name is not required anywhere in the ABI, and it is not really a reliable information.

**Comment by DmitryBespalov** [comment]
I think this can be closed? @rmeissner

**Comment by rmeissner** [comment]
Yes
