### ISSUE TITLE
Add `push_info` tracking

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#330]
# What is this feature about? (1 sentence)
This will add info about whether push notifications are enabled to the tracking.

# Why is it needed? What is the value? For whom do we build it?
There is no way to manage product without measuring success. We heard in user research that pushes are something that users would like this. This tracking helps us to see of users receive pushes.

# High-level overview of the feature
- Tracking has been introduced via #299
- Please add the following [custom user properties](https://firebase.google.com/docs/analytics/user-properties?platform=ios):
  - `push_info`
    - string
    - `unknown` if we haven't asked for push access yet (iOS only since we have push permission on Android by default)
    - `enabled` if we have push notification permission (or enabled it after previously denying)
    - `disabled` if the user denied push permission (or removed it after previously allowing)

Tracking info can also be found in the [wiki](https://github.com/gnosis/safe/wiki/Tracking).

**Comment by liliya-soroka** [comment]
The epic is closed a no major issues. One minor issue for discussion
Verified
app version :
ios 2.1.0 (2)
android 2.0.0 (19)
