### ISSUE TITLE
Better formatting of small amounts

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#332]
# What is this feature about? (1 sentence)
This will display `< 0.00001` for amounts smaller than 0.00001 instead of `0.00000`

# Why is it needed? What is the value? For whom do we build it?
- This is how we format amounts: https://github.com/gnosis/safe/wiki/How-to-format-amounts
- We cut off numbers after the 5th decimal, hence amounts smaller than 0.00001 will show up as `0.00000` even though they are > 0.

# High-level overview of the feature
- If a number of smaller than 0.00001, display `< 0.00001` in the interface.
- Check https://github.com/gnosis/safe/wiki/How-to-format-amounts for the full amount formatting spec.

**Comment by liliya-soroka** [comment]
Verified
app version 
ios 2.1.0(2)
android 2.0.0(17)
