### ISSUE TITLE
Display addresses as `0xffff...ffff`

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe#335]
# What is this feature about? (1 sentence)
All addresses are displayed as `0xffff...ffff`.

# Why is it needed? What is the value? For whom do we build it?
Currently we display addresses as `0xff...ffff`. Martin and Stefan gave the feeback that 2 chars in front is not enough. 
Also, Metamask uses `0xffff...ffff` which is probably what most people are used to.

# High-level overview of the feature
- Use `0xffff...ffff` everywhere were we display shortened addresses.
- For the full address that has coloring, the first 6 characters need to be colored instead of 4

**Comment by liliya-soroka** [comment]
Verified
app version
ios - 2.0.0 ( 12)
android - 1.12.1 -115
Released in v 2.0.0
