### ISSUE TITLE
Tap to copy addresses

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#336]
# What is this feature about? (1 sentence)
This allows users to easily copy addresses throughout the app.

# Why is it needed? What is the value? For whom do we build it?
Sometimes it's important to review and share addresses. Hence an easy way to copy them is needed.

# High-level overview of the feature
- Tapping the address copies it to clipboard
- There is a toast/label that says "Copied to clipbard" that hides automatically.
  - Android: https://zpl.io/29QXGqY, https://zpl.io/2yAWvny
  - iOS: https://zpl.io/V0QDPME, https://zpl.io/29x5yZd

The following addresses should be copieable:
- On Receive screen: Safe address
- Safe settings: Owner addresses, contract version, Callback handler, Module addresses
- App settings: ENS resolver address

**Comment by liliya-soroka** [comment]
Verified
app versions:
ios - 2.2.0 -152
android - 2.1.0 - 1172
