### ISSUE TITLE
v1 Display human readable names for "Known" addresses

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#337]
# What is this feature about? (1 sentence)
This feature will display human readable names when interacting with known contracts/protocols such as Uniswap or Compound.

# Why is it needed? What is the value? For whom do we build it?

- The top problem area that we identified is, that users don't know what they are signing and which protocols they are interacting with.
- A first step in getting rid of cryptic addresses is displaying human readable names for known contracts.

# High-level overview of the feature
- There is a list or mapping from addresses to human readable names. 
  - Multiple addresses could map to the same humand readable name.
  - I think this list should be served from the backend, but that's up for discussion.
  - Long term, this list could be an onchain registry curated by Safe governance, but that's for later.
  - Example list: https://docs.google.com/spreadsheets/d/1JVvwTfp3WNQ1CXMx8xVQ2n7Aj-u0KDiXxGHNW5OjHb4/edit#gid=0 
- The web interface should implement this in the same fashion (gnosis/safe-react#1638)
- The protocol/dapp name (and logo perhaps) should be displayed on the tx list.
  - cf. How Safe app txs are displayed in #353 
- On the tx details, the dapp name would also be visible instead of just contract/recipient addresses
  - Same for addresses in decoded data
  - There should be still a way for users to examine the actual address somehow.

- Related client gateway issue: https://github.com/gnosis/safe-client-gateway/issues/198

# Misc 

- "press release": https://docs.google.com/document/d/11ABA0Nj9gQ_yyCTn-4vgNfJ5XqqputXENTNUcIe03E8/edit
- "kickoff meeting": https://docs.google.com/document/d/198DfSRBvyT8UTF8ynNMrcHMFu_2z_d5PFtAgyHs1TAc/edit#
- specs doc https://docs.google.com/document/d/1kY7KQ0x135z4TzUsqjAdQ-7z42oKe7-pY89BfOkHkfE/edit 

# What's included in v1
- Known addresses in transaction list
- Known addresses in transaction details screen's header

**Comment by tschubotz** [comment]
@tschubotz check sourcify. token repos.

**Comment by posthnikova** [comment]
Proposal for web and mobile. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/e920ad40-f5b0-43d3-9df1-8d7f3e7cf7cd)

> If the local state of the app overrides the curated list of contracts from the backend, it could confuse 
> the users if for some reason they add a contract that we later on include in the curated list.

> Should we be able to differentiate between addressbook entries, safe app names and known contracts?

In the first version most likely no, but there are many options how to show it. A known contract could have a different appearance or 'approved' badge, the name would be from address book. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/1f4212d4-c999-4745-8421-e976a42be729)

An easy option could be to just swap the identicon for a logo when the contract is added later. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/17bf2999-8039-49ab-a12d-7fea7b518bd8)

**Comment by tschubotz** [comment]
Thanks for the proposal:

What I like:
- The tx list looks quite clear.
- The exact address is not important here, so I like that it's omitted.
- I like that it's still possible to examine the complete address on the tx details.

Questions I have:
- Assuming a parameter inside of decoded data is a known address, would we still show the mapping there or was it decided to leave this out for a first version? what I mean is the `spender` in this example: ![image.png](https://images.zenhubusercontent.com/57add4fee40e5714b16d4969/8fd27823-2f4e-47e7-a555-e211298a6b45)


>  If the local state of the app overrides the curated list of contracts from the backend, it could confuse  the users if for some reason they add a contract that we later on include in the curated list.

>  Should we be able to differentiate between addressbook entries, safe app names and known contracts?

> In the first version most likely no, but there are many options how to show it. A known contract could have a different appearance or 'approved' badge, the name would be from address book. 

- I agree that in a first version it's ok to not be able to differentiate.
- I like the label-like visualization, however how would this look on the tx list?
- In terms of differentiating address book vs. known contracts: 
  - I like the idea with the "check mark"
  - How about showing the info where a name is coming from when hovering over it?

**Comment by rmeissner** [comment]
> Assuming a parameter inside of decoded data is a known address
It would be nice to know this, as far as I understood from our meetings we would not look at addresses inside the data decoded. As we want to add more advanced handling of the data decoded (e.g. adding token decimals and symbol) in the future too. This would be a similar feature and I would try to handle them in a similar way in a separate issue.

Could we please add how the details would look for a transfer and for a settings change (e.g. enableModule or addOwner)?

**Comment by posthnikova** [comment]
> I like the label-like visualization, however how would this look on the tx list?

With label:   

![image](https://user-images.githubusercontent.com/45787536/102076890-c0308d80-3e08-11eb-8c5f-51b7a125a6ac.png)

In address book this would look the same, only name would be overridden.   
With checkmark:

![image](https://user-images.githubusercontent.com/45787536/102076919-c888c880-3e08-11eb-8985-d15269f44a45.png)

> How about showing the info where a name is coming from when hovering over it?   

We can do that but this is not what I would expect when hovering on checkmark. A checkmark indicates safety, something is approved and safe to use. I would expect info that this contract is known on hover. Isn't just overriding the name enough to differentiate address book from known contracts?   

![image](https://user-images.githubusercontent.com/45787536/102076946-d2123080-3e08-11eb-982a-10d89d285f4d.png)

> Could we please add how the details would look for a transfer and for a settings change 
> (e.g. enableModule or addOwner)?

Added them:   

![image](https://user-images.githubusercontent.com/45787536/102077002-e3f3d380-3e08-11eb-8936-a5c0c25e4303.png)

**Comment by jpalvarezl** [comment]
My main concern during the refinement meeting we had today is regarding the priority of the data source. As an example, if we have the **same safe** observed by **2 different owners** with **different address books** they would have a different UI for the same safe, which is surely confusing. 

Should we only fill in data for known address when the backend doesn't provide it? Then we could gather data for different contract types (Token or "known" address). This would be particularly costly for the mobile apps.

**Comment by posthnikova** [comment]
Changes after refinement meeting:   

![image](https://user-images.githubusercontent.com/45787536/102109470-5f1eaf00-3e34-11eb-9b5c-234827bd2600.png)

• Added outgoing transfer and settings change (addOwner)   
• Added Safe app transaction
• Added NFT transfer

> if we have the same safe observed by 2 different owners with different address books they would have
> a different UI for the same safe, which is surely confusing.

The way it's shown in the first version is confusing. There could be multiple cases of adding an address to address book:   
• From tx details. In this case the user shouldn't be confused, they know where this address comes from.   
• From address book (Create entry). The user might not know that the address is known. Possible confusion because other owners might have a different name or might not have this address in address book.

**Comment by liliya-soroka** [comment]
Note For QA(mobile app) - We need access to the list of known addresses that will be used by back-end

**Comment by posthnikova** [comment]
Update after refinement meeting: Safe app transaction is shown as contract interaction.   

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/9e7df3ec-d122-40a8-94cd-580583ac9882)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/f7ebe7ff-6cdf-4d04-9f95-d54b03f9966d)

**Comment by posthnikova** [comment]
Replace owner:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/148a4ef3-639d-4138-9ae3-f36e231b3fa5)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/b0e4564a-0b65-46b2-98fc-a3170ab263bc)

Set fallback handler:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/562cc71c-afb7-47be-aac5-3b553334177d)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/02ab1c14-340a-411f-9349-ead60448ba7f)

Change mastercopy:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/4b672e65-ea18-45f1-a5f2-b2bc017ae6fc)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/aaefd92c-2e75-4cde-8d8e-9460bde2ae84)

Enable module:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/fa5db71f-822b-4c3f-9220-052e93455047)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/c3fabbe7-b358-463c-a79a-07c5d5a05250)

Disable module:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/3da0c3cb-ab4a-4374-9193-831230a0c115)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/5a45fa61-8a52-43e9-85f7-fe031dcc848a)

Create Safe:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/0651dfec-eff7-4fed-aa9f-c42e75196eb0)

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/f2a80143-179b-41b6-b568-e93c5e7a82b9)

**Comment by sche** [comment]
@posthnikova fallback handler, master copy, module, factory used - they are all gnosis contracts. Should we make icons for them as part of this story?

**Comment by tschubotz** [comment]
> @posthnikova fallback handler, master copy, module, factory used - they are all gnosis contracts. Should we make icons for them as part of this story?

@sche I would vote for using the Gnosis Safe logo for those. What do you think about that?

**Comment by posthnikova** [comment]
Something like this? 

![image](https://user-images.githubusercontent.com/45787536/103793857-6c4e4880-5044-11eb-90f2-7eb4f860f2b3.png)

**Comment by lukasschor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show name for "known" contracts](https://trello.com/c/7Xenp4vG/64-show-name-for-known-contracts)

**Comment by fernandomg** [comment]
For the history list, how should we display/use times? user's specific TZ or +UTC as Etherscan does?

If we go with the +UTC, there will be this (probably) unexpected outcome. Say I'm in UTC-3 if I execute a tx on Jan-29 09:01 PM, the tx will be listed under Jan-30 12:01 AM +UTC.

@posthnikova @tschubotz

**Comment by tschubotz** [comment]
> For the history list, how should we display/use times? user's specific TZ or +UTC as Etherscan does?

User/device specific timezone please. 

Note, that there is a timezone parameter on the gateway which makes sure that the gateway returns everything in the respective time zone already, as far as I understand. https://github.com/gnosis/safe-client-gateway/wiki/transactions_history @rmeissner  @jpalvarezl please correct if I'm wrong.

**Comment by liliya-soroka** [comment]
Verified
app version :
ios - 2.10 .0 - 308
android - 2.10.0-2063rc
