### ISSUE TITLE
Push notifications for signing requests

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#349]
# What is this feature about? (1 sentence)
This will notify the user whenever there is a new transactions waiting for confirmations, ONLY if that device is an owner.

# Why is it needed? What is the value? For whom do we build it?
- We have learned that it's an inconvenience for users to notify other owners about new signing requests.
- This can be improved by push notifications.

# High-level overview of the feature
- The push notification should only be received for Safes where an owner account is added to the app (cf. #348)
- Client should display the local Safe name.
- Texts:
`<safe_name: A transaction requires your confirmation!`
- Ideally, tx details should be opened.
  - If that's not possible, then tx list.

# Misc

- We could show actions on the notification on Android: Let's not do that since we have a confirmation dialog "are you sure you want to sign" (or sth like this)
- Specification working document: https://docs.google.com/document/d/1RqIfZkqdS_TZ4IQVjeWUhNI1ZguD3NfpohSSRLVxB5Q/edit#heading=h.h09ziydayww

**Comment by tschubotz** [comment]
Kick off meeting: https://docs.google.com/document/d/1cboxJiFFDaPB6gQ6fa8rof6Rc0kNDuELqgVnTkAK8IM/edit#

@DmitryBespalov to push this forward

**Comment by liliya-soroka** [comment]
Verified
app version android - 2.7.0 -1664rc
app version ios - 2.7.0 (229)
