### ISSUE TITLE
Data decoding v2 - Special handling for multisends

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#350]
# What is this feature about? (1 sentence)
This feature will allow users to browse the different transactions that are part of a Multisend.

# Why is it needed? What is the value? For whom do we build it?
- Multisends can be used to batch transctions. 
- It improves UX and is used e.g. by Safe apps
- In v1, users would not be able to inspect the details of the Multisend

# High-level overview of the feature

- User sees how many transactions ("actions") are part of the Multisend.
- User can explore the single transactions to see what function has been called with which parameters
- It is enough to decode Multisends 1 level deep for now
- It is also enough to just show the called function name, no special handling for e.g. ERC20 tokens required. (As I understand that reduces complexity. Will be done as part of #351)

# Tracking 

- The screen view identifier should be `transaction_details_action` when it's a single action
- The screen view identifier should be `transaction_details_action_list` when it's a list of multisend actions
- cf. [screen view tracking docs](https://github.com/gnosis/safe/wiki/Overview-screen-tracking)

# Updates

- Tobi, September 1: Add screen tracking info

**Comment by posthnikova** [comment]
Changes after refinement meeting: `
• Remove tx type icon in the list
• Show Action # if method not available
• Show raw data if decoded data not available

![image](https://user-images.githubusercontent.com/45787536/94802439-f9e81f80-03e7-11eb-935e-2dcd2f0545d1.png)

**Comment by liliya-soroka** [comment]
Verified
ios app version - 2.5.0 (183)
android app version - 2.3.0 - 1278rc
