### ISSUE TITLE
Display safeTxHash in advanced tx details

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#352]
# What is this feature about? (1 sentence)
This will display the safeTxHash on the transaction details.

# Why is it needed? What is the value? For whom do we build it?
- We currently only display txHash. That's the public txhash available after submit/execution.
- safeTxHash is needed to sign transactions, including  onchain signing via `approveHash`
- The safeTxHash can be used to verify tx parameters. So that's especially important for validating transactions

# High-level overview of the feature
- safeTxHash is displayed for all txs in the advanced settings
  - Includes Queue and history
- Regular txHash is still additionally displayed when available
- Both should be copy-able.

# Misc

- Web ticket: gnosis/safe-react#1641

# Updates

- Nov 23, Tobi: add more details.

**Comment by tschubotz** [comment]
@tschubotz that's the only way to verify on hw wallets that the user signs the correct thing.

**Comment by tschubotz** [comment]
@posthnikova please make a design proposal.

**Comment by posthnikova** [comment]
iOS and Android:

![image](https://user-images.githubusercontent.com/45787536/100259210-41061300-2f48-11eb-8238-1cfbbc92bcb2.png)

**Comment by liliya-soroka** [comment]
Verified for both 
ios - 2.7.0 (227) and
android - app version 2.5.0 -1595
