### ISSUE TITLE
Don't scroll up tx list when coming back from tx details

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#354]
# What is this feature about? (1 sentence)
This would not automatically scroll up the tx list when going back from tx details.

# Why is it needed? What is the value? For whom do we build it?
- Currently, we always reload and scroll up the tx list, when opening the tx tab. (iOS only scrolls up when there's new data, Android always afaik)
- When checking txs in the tx list, that's inconvenient.

# High-level overview of the feature
- Still refresh tx list, but don't scroll up to the top when going back from tx details.

# Alternatives considered
1. Scroll to tx; Open tx details; [New transactions submitted, or status changed] Go back --> Data is not reloaded; User manually refreshes the data. Least effort, iOS effort XS, 
2. Scroll to tx; Open tx details; [New transactions submitted, or some tx status changed] Go back --> The data is reloaded (you see reloading indicator); The scrolling is at the same transaction position. Technically more effort (tx in the boundary of the page), effort L
3. Go back --> If was at the top of the list (visually), reload the content; If scrolled to other  pages - do not reload anything; effort S
4. Go back --> Query backend to see if we need to reload (ETag/Timestamp) and then reload if data is changed [or display "notification" that new data is available - reload that] - effort M
  a. If new data - scroll up automatically or display "content updated button"
5. Receive notifications (push or web socket) that the list is dirty there are updates - then update. This needs changes to the backend, frontend, effort XL

# Solution
Go with No.3 from the list above because it is not too complicated but also is better than not reloading any data

Always reload if transaction details were opened from the transaction in the 1st "screen" - visible portion of transaction;
Do not reload the screen when transactions were scrolled and then transaction details opened and user got back.

**Comment by liliya-soroka** [comment]
Verified
ios app version -2.7.0 (227)
android app version 2.5.0 -1421rc
