### ISSUE TITLE
Filter out spam ERC20 tokens

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#357]
# What is this feature about? (1 sentence)
This feature ensures that spam tokens which sometime get airdropped to Safes are not shown within the Gnosis Safe interfaces.

# Why is it needed? What is the value? For whom do we build it?
- We see an increased number of spam tokens.
- Some of them even have a fiat value.
- Users can't transfer them out.
- On web we filter them out. We need a unified view on assets across interfaces.

# High-level overview of the feature
- Please do not display tokens that have the `spam` flag set to `true`
- This is only for balances, not for collectibles

# Misc
- Related backend ticket: gnosis/safe-transaction-service#41
- Related web ticket: gnosis/safe-react#1324

**Comment by tschubotz** [comment]
Kick off meeting: https://docs.google.com/document/d/1cboxJiFFDaPB6gQ6fa8rof6Rc0kNDuELqgVnTkAK8IM/edit#heading=h.gcoaz1lqykfa

@jpalvarezl

**Comment by liliya-soroka** [comment]
Reopened:
It's not implemented for the ERC721 tokens

**Comment by jpalvarezl** [comment]
Depending on whether the clients consume the `collectibles` endpoint from the gateway or the core services. As far as I know, they both do.

At the moment, the gateway simple relays the response back and forth between the endpoint and the core services, using the default values that the core services define. Which, according to the swagger, are `false` for both `trusted` and `exclude_spam`.

We would have to define an issue in the gateway, specifying the required default values as we did for the `balances` endpoint.

**Comment by DmitryBespalov** [comment]
@liliya-soroka the ERC721 token filtering is not related to this issue and should not have been implemented.

**Comment by liliya-soroka** [comment]
Verified
the spam token( erc20 tkens only) filtering was implemented in the 2.6.0 release
