### ISSUE TITLE
Display total fiat value of assets

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#360]
# What is this feature about? (1 sentence)
Users see the total USD value of their assets. (since we only support USD so far)

# Why is it needed? What is the value? For whom do we build it?
- We want to position the mobile apps as a way to stay up to date on one's digital assets. The total value of a users portfolio is an important metric that users track, especially during times of volatile prices.
- We learned, that users prefer to see/check the total number of their assets as well.
  - That's why on web, we already display the total asset value.

# High-level overview of the feature
- On the assets tab, the total USD value of all assets is shown.
- Only ERC20 tokens have a USD value so far, so only those are considered
- Spam tokens should not be considered for the total USD value. (#357)
- Only USD since we don't have a fiat selector on mobile

**Comment by tschubotz** [comment]
Kick off meeting: https://docs.google.com/document/d/1cboxJiFFDaPB6gQ6fa8rof6Rc0kNDuELqgVnTkAK8IM/edit#heading=h.zbpnxaoc94jb

@jpalvarezl

**Comment by posthnikova** [comment]
All possible options: 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/06dc3ef0-4d88-4dc1-83b0-d827ad6bdf43)

01, 02 are the easiest, but it's not where I would expect total balance to be shown. 04, 05 need to be shown on all tabs. 

Android – the same but without the large title:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/32698266-b435-4477-a134-e2d1cbff4783)

Huge headers (04, 05, 06) need collapse animation on scroll: 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/13f902a3-22db-4702-bb6f-2b687bee9cba)

**Comment by DmitryBespalov** [comment]
I like number 1 because I think that I found the total value immediately both on Android and on iOS, comparing to others

**Comment by liliya-soroka** [comment]
I like the second with Total and the full amount. It's clear what the number means and it looks better on ios without displaying number right under reload option.

**Comment by jpalvarezl** [comment]
I think only option 01 and 02 make sense from a data layout perspective in the screen. The rest, seems like we would be mixing different things, unless we want this balance info visible across all screens in the app. This would be technically visible from the settings? Or do we hide this somehow depending on which tab is selected? This would be a bit convoluted to implement, I would guess. 

If we need to show anywhere from the app, we would probably need a dedicated endpoint for this.

**Comment by tschubotz** [comment]
I like option 1 and 2. Prefer 2 a bit more since it says what this is ("Total") and all fiat values are on the right side. I think the other options are too crowded. We would have to "decrowd" them by using different font sizes or making the header bigger I think.

**Comment by rmeissner** [comment]
Also prefer 2 same reasons as @tschubotz

**Comment by Uxio0** [comment]
Another vote for 2 here

**Comment by KristinaMayman** [comment]
I also like version 2, although I think the "Total" field could be made more distinct from individual assets, maybe with a stronger border or a colour differentiation?

**Comment by posthnikova** [comment]
Version 2 is on zeplin. Android: https://zpl.io/VOG8gZ8. iOS: https://zpl.io/aB0NNwL.

**Comment by liliya-soroka** [comment]
Verified
app version
ios - 2.5.0 (186)
android - 2.5.0 - 1421rc
