### ISSUE TITLE
Adapt launch screen slogan text

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#361]
# What is this feature about? (1 sentence)
This will just change 1 word on the launch screen: "store" -> "manage"

# Why is it needed? What is the value? For whom do we build it?

We made this small change recently during the last vision discussion.

# High-level overview of the feature
- On the launch screen, we currently display "The most trusted platform to **store** digital assets on Ethereum". 
- Please change this to "The most trusted platform to **manage** digital assets on Ethereum".

**Comment by posthnikova** [comment]
Android: https://zpl.io/2GJ0163
iOS: https://zpl.io/2E0m7q8

**Comment by liliya-soroka** [comment]
Verified
app version 
ios - 2.5.0 (186)
android - 2.5.0 -1421rc
