### ISSUE TITLE
Import owner key screen

### ISSUE THREAD

**Issue by sche** [gnosis/safe#364]
- Scrolling should be available to support small screen resolutions.
- When the screen is opened the “Enter seed phrase” is focused by default.
- This field does not have any text input limitations.
- When selecting the “Next” button OR selecting “Enter” button on the keyboard, the form “submission” should happen.
  - Strip or ignore extra whitespace and punctuation symbols in the phrase. For example, words can be separated by more than one space or by new line symbol
  - Any letter case should be accepted (upper, lower, mixed)
  - Seed phrase validated according to underlying ETH/crypto library
- If the input is valid, the next screen “Import Owner Key” should be presented.
- If the input is not valid, the error state should be displayed.

![image](https://user-images.githubusercontent.com/2284385/94420115-f8b6b880-0183-11eb-90b3-f359d220854b.png)

**ERROR STATE**
- In error state text input should be highlighted, and the “Seed phrase is not valid” message should be displayed.
- Typing in the text field should return it back to the “normal” state immediately.

![image](https://user-images.githubusercontent.com/2284385/94420194-18e67780-0184-11eb-8ad3-0e5d0e3a0e07.png)

**Updates**
Requirements for the sanitisation of the seed phrase:
- Ignore whitespace and punctuation marks leading and following the input
- Ignore extra whitespace (line breaks, tabs, spaces, etc) and punctuation symbols in the phrase. For example, words can be separated by more than one space or by new line symbol
- Everything should be lower cased
- Seed phrase validated according to underlying ETH/crypto library

**Comment by liliya-soroka** [comment]
Comment for the ios app:
When the screen is opened the “Enter seed phrase” isn't focused by default - For limitation of the used framework this is not feasible.
When selecting the “Next” button OR selecting “Enter” button on the keyboard, the form “submission” should happen. - For limitation of the used framework this is not feasible.

**Comment by liliya-soroka** [comment]
Verified for android - 2.4.0 -1326
