### ISSUE TITLE
Remove owner key

### ISSUE THREAD

**Issue by sche** [gnosis/safe#366]
On the App settings screen, there is an “Imported owner key” row, if there is a key imported.

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/d938453e-139a-4081-9a53-35ad0323d378)

Selecting the “remove” icon should display a confirmation.

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/7f1e95fc-2e72-4056-abf8-18c14a8ab711)

**Copy**:

Removing the owner key only removes it from this app. It doesn’t delete any Safes from this app or from blockchain. For Safes controlled by this owner key, you will no longer be able to sign transactions in this app.

On confirming:
- the key should be removed from secure storage.
- The key address should be removed from the app storage.

**Comment by elgatovital** [comment]
wording for the dialog message: 
```
Removing the owner key only removes it from this app. It doesn’t delete any Safes from this app or from blockchain. For Safes controlled by this owner key, you will no longer be able to sign transactions in this app.
```

**Comment by liliya-soroka** [comment]
The additional case should be tested :
tx confirmation after the owner key removing

**Comment by liliya-soroka** [comment]
Verified
ios 2.4.0 -166
android - 2.3.0 - 1299
