### ISSUE TITLE
Confirming transaction

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe#367]
<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/3f2849b6-9986-47df-84d1-e3b2ca3cd5cd" width=300/>

Confirm button should be displayed, if the transaction is in “Awaiting your confirmation” state (the imported key is among safe owners, but not among confirmations)

The confirm button should be stick to the bottom tab bar.

### Selecting “Confirm” should
- Display a confirmation request
![Screenshot 2020-09-28 at 12.09.58.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/8a418e2e-d8f6-4963-95aa-98b5843331b9)
- When user confirmed the pop-up, app makes networking request to the backend to submit the confirmation (see below)
- The activity indicator should be displayed:
  - On iOS activity indicator is displayed full-screen.
  - On Android the confirmation button is blocked, and pull to refresh activity indicator is present.
- When successful, the transaction details data updates the screen, so that "Confirm" button is hidden and a notification should be displayed 
![Screenshot 2020-09-28 at 12.12.26.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/49a9aaf8-77d7-4632-a100-62c11bc36311)

### Submitting the transaction confirmation
- The app shall verify that the safeTxHash from response is valid (by calculating the hash from the transaction fields)
- The app shall pin the server certificates of the client gateway service and transaction service
- The app uses /safes/{address}/transactions/ endpoint of the transaction service to submit  the confirmation
- After getting a successful response, the app will request updated tx details using the gateway service.
  - The screen should be updated with the latest tx info: awaiting execution or awaiting confirmations.
- In case of error, the app hides the loading indicator and displays the actual (latest) state with “Confirm” button, and a snackbar with the error message.
  - In V1 we will always show a “Failed to sign” message for all 422 errors.
  - Error message codes (TBD)
    - Networking error
    - Signing the tx when the key is already not an owner
    - Signing already executed tx
    - What else? (Unexpected error)

- In case of the transaction details request failure, the app displays “Data can not be loaded” placeholder and a standard snackbar with an error message.

### Additional information
- https://github.com/gnosis/safe-contracts/blob/94f9b9083790495f67b661bfa93b06dcba2d3949/contracts/GnosisSafe.sol#L403
- https://docs.gnosis.io/safe/docs/contracts_signatures/ (ECDSA signature)
- https://docs.gnosis.io/safe/docs/contracts_tx_execution/#transaction-hash (Transaction hash)

**Comment by liliya-soroka** [comment]
Verified with note:
The requirement 
"Error message codes (TBD)
Networking error
Signing the tx when the key is already not an owner
Signing already executed tx
What else? (Unexpected error)"
was not implemented in the current task. It will be a part of aligning messages task between ios and android

App version:
android - 2.4.0 -1332rc
ios - 2.4.0 -174
