### ISSUE TITLE
Owner Key Imported in the App settings screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe#369]
<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/b25cb04b-7cc7-431f-b10d-b4f87a491872" width=300/>

The “Owner key successfully imported” notification is presented.

The “Imported owner key” cell is displayed.

**Comment by liliya-soroka** [comment]
Verified
android : app version 2.4.0 - 1326
ios : 2.4.0 - 165
