### ISSUE TITLE
Allow enabling/disabling of screenshot permission [Android only]

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#378]
# What is this feature about? (1 sentence)
This will allow users to enable or disable screenshot permission for their Safe app in order to allow us to perform remote user tests on Android.

# Why is it needed? What is the value? For whom do we build it?

- Currently, we have screenshot permission 
  - forbidden for production apps for security reasons, so malicious other apps cannot access the clipboard and record the screen
  - allowed for staging builds to simplify QA 
- When doing usability tests remotely, users need to share their phone screen. Currently on Android this is prevented, which means those tests can only be performed with iOS, currently. That's not ideal and prevents us from getting insights from Android users.

**Enabling/disabling screenshots is just a possible solution to reach the goal of allowing us to do remote usability tests on Android. If there is another way to allow these tests, please bring it up.**

# High-level overview of the feature
- Screenshots can be enabled/disabled in the advanced app settings.
- There should be a warning like "Danger zone: Enabling screenshots allows external apps to record the content of you screen. We highly recommend leaving this option disabled."
- Toggle off should mean "no screenshots"
- Toggle on should mean "screenshots allowed"
- Default: off
- Turning it off turns it off in the entire app, including the input seed phrase screen.

# Updates

- Nov 19, Tobi: Updates after mobile refinement meeting (see also first comment from Dima below)

**Comment by DmitryBespalov** [comment]
- Toggle "Allow screenshots" in the **Advanced App Settings** that will be "off" by default
- When **off**, the screenshotting is blocked. If a user takes screenshots, they see a message that they can enable screenshots in the settings
- When **on**, the screenshotting is allowed in the whole app

We do not block screenshots in the seed phrase because users could copy-paste the phrase and that is even less secure.

We need a UI for that toggle.

**Comment by posthnikova** [comment]
Advanced settings for Android:

![image](https://user-images.githubusercontent.com/45787536/99956932-26d10700-2d87-11eb-8f73-c24a63fe6454.png)

**Comment by tschubotz** [comment]
I think this looks good @posthnikova . There's a small typo: "[...] of you**r** screen. [...]"

**Comment by biafra23** [comment]
@posthnikova Can I have this added to Zeplin? I need the font size for the description. It seems to be bigger than in the other headers.

**Comment by posthnikova** [comment]
Zeplin: https://zpl.io/VQX89k4, https://zpl.io/VQZyK9k

**Comment by biafra23** [comment]
@tschubotz 
> When off, the screenshotting is blocked. If a user takes screenshots, they see a message that they can enable screenshots in the settings

ATM a system message is displayed that the app prevents taking screenshots. I am not sure we can modify that message. Is this an important requirement?

**Comment by tschubotz** [comment]
> ATM a system message is displayed that the app prevents taking screenshots. I am not sure we can modify that message. Is this an important requirement?

No, not important imo, can be left out if hard to do.

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 - 1595
