### ISSUE TITLE
Add 2 tracking events for mobile signing

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#379]
# What is this feature about? (1 sentence)
This will add 2 more tracking events (`user_key_imported` `user_transaction_confirmed`) in order to analyze the success of the mobile signing feature better. 

# Why is it needed? What is the value? For whom do we build it?

- With Google data studio it's currently not possible to analyze as part of a funnel, how many users successfully imported a key.
- We don't know if people even sign transactions on mobile.

# High-level overview of the feature
Please trigger the following 2 events:
- `user_key_imported`: Triggered each time after successfully importing an owner key.
- `user_transaction_confirmed`: Triggered each time a transaction has been confirmend with the imported owner key.

# Misc

- Has also been added to [tracking docs](https://github.com/gnosis/safe/wiki/Tracking#user-action-tracking)

# Updates

- Nov 19, Tobi: Added link to tracking docs.

**Comment by biafra23** [comment]
@tschubotz Should we also have an event for removing a key?

**Comment by DmitryBespalov** [comment]
For now, adding the "removed key" event is not necessary

**Comment by liliya-soroka** [comment]
Verified
ios app version - 2.7.0 (227)
android app version 2.7.0 - 1634rc
