### ISSUE TITLE
Evaluate promoting Safe mobile app in Apple App Store and Google Play Store

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe#386]
John asked me to look into promoting the Safe app on the Apple App Store and Google Play Store.

- What is possible (key word search "crypto wallet" or similar sear terms) ?
- How expensive is it?

**Comment by tschubotz** [comment]
closing this one as per discussion with John : https://gnosisinc.slack.com/archives/CNG8SUG13/p1609753016012000?thread_ts=1609247174.007300&cid=CNG8SUG13
