### ISSUE TITLE
Settings UI changes after user tests

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#388]
# What is this feature about? (1 sentence)
This feature collects smaller UI changes after user tests.

# Why is it needed? What is the value? For whom do we build it?

- During user tests of the signing feature, we learned about some issues in the UI.
- This was originally part of #380 but was split out since it wasn't related to mobile signing.

# High-level overview of the feature

- Rename 'Contract version' → 'Safe version' in the Safe settings    
- Explain what a fallback handler is. (Link to https://help.gnosis-safe.io/en/articles/4738352-what-is-a-fallback-handler-and-how-does-it-relate-to-the-gnosis-safe)
  - iOS Zeplin [Web](https://zpl.io/aRJXRkp) | [App](zpl://screen?pid=5e8f27b9963e55bb79b13634&sid=5ea96645372030276486bd06)
  - Android Zeplin [Web](https://zpl.io/2p6wGNl) | [App](zpl://screen?pid=5e9efc30726e106958cc43de&sid=5ea968e3c4cec8bf7b255fb3)
- Make small headers more prominent (section headers).
  - iOS Zeplin [Web](https://zpl.io/aBJGQYk) | [App](zpl://screen?sid=5eaa9cf8775d4a236be225dd&pid=5e8f27b9963e55bb79b13634)
  - Android Zeplin [Web](https://zpl.io/2yAKvop) | [App](zpl://screen?pid=5e9efc30726e106958cc43de&sid=5ea968e23ce9bf2491eddccf)

**Comment by posthnikova** [comment]
The link for fallback handler should look like this:

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/f913d022-e63f-44f0-8302-d5e212840043)

**Comment by liliya-soroka** [comment]
@posthnikova and @tschubotz , are we going to use "Callback Handler" instead of "Fallback Handler". If yes, then it make sense to use the same name in "Default Callback Handler" on settings, "UpdateCallbackHandler" on txs list and tx details , in the link under Default Callback handler and in the article.

**Comment by tschubotz** [comment]
That naming is not ideal, but our default fallback handler is called DefaultCallbackHandler since the fallback methods are callback methods of token contracts. 🤯😅
I tried to explain this in the last paragraph of https://help.gnosis-safe.io/en/articles/4738352-what-is-a-fallback-handler-and-how-does-it-relate-to-the-gnosis-safe.

Therefore I think the screen from Sasha is correct, wording wise.

**Comment by KristinaMayman** [comment]
I think the link text looks good! I would put a question mark at the end of it though.

**Comment by posthnikova** [comment]
**iOS**
Settings: https://zpl.io/VxZl9v3
Advanced: https://zpl.io/aRJXRkp

**Android**
Settings: https://zpl.io/2yAKvop
Advanced: https://zpl.io/2p6wGNl

**Comment by liliya-soroka** [comment]
Verified
app version :
ios - 2.10 .0 - 308
android - 2.10.0-2063rc
