### ISSUE TITLE
Upgrade to version 1.2.0

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe#391]
# Blocked by: gnosis/safe-react#1383

# What is this feature about? (1 sentence)
Ask user to upgrade to Safe contract version 1.2.0

# Why is it needed? What is the value? For whom do we build it?
The Gnosis Safe contracts v1.2.0 have passed audit and bug bounty period. So we can make them available for users. 

# High-level overview of the feature
- 1.2.0 is a verified contract version in the Safe settings.
- Web ticket: gnosis/safe-react#1383

# Misc

- Mastercopy 1.2.0 https://etherscan.io/address/0x6851d6fdfafd08c0295c392436245e5bc78b0185
- https://github.com/gnosis/safe-contracts/releases/tag/v1.2.0

# Ask user to upgrade contract to 1.2.0

Depends on: https://app.zenhub.com/workspaces/safe-multisig---web-5ce554debb310a35b2f8b6f8/issues/gnosis/safe-react/1383

- [ ] Safe Settings (Show upgrade available if version < 1.2.0)
- [ ] Safe settings (Show "Up to date" for  v1.2.0 )

**Comment by tschubotz** [comment]
Closing this as will will go straight for 1.3.0 once the time comes.
