### ISSUE TITLE
Educate users about how the private key is stored.

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#392]
# What is this feature about? (1 sentence)
This will provide the users with info on how the private key is stored on mobile so they can decide whether they feel secure enough or not.

# Why is it needed? What is the value? For whom do we build it?

- This is related to the problem "Storing a private key on mobile does not feel secure" on our roadmap.
- We have received the feedback from users that they wanted to know how exactly the private keys are stored on the devices.
- Users do not trust that the private key cannot be exported by someone getting access to the phone
- Providing more info would help getting more re-assurance about the private key(s) being kept secure

# High-level overview of the feature

- Write help center article about how the key is stored on Android and iOS.
  - Android-related article section
  - iOS-related article section
  - We need a placeholder link
- During "import owner key" onboarding, link that help center article for the user to access.

# Misc

- Kick off meeting doc: https://docs.google.com/document/d/1CiFAtEmRngQF2SRQgu6PEhFPbwwZWhkW3VAKxV5oTAc/edit#

**Comment by tschubotz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Educate users about how the private key is stored](https://trello.com/c/6klwJBL6/67-educate-users-about-how-the-private-key-is-stored)

**Comment by posthnikova** [comment]
Designs for mobile:

![image](https://user-images.githubusercontent.com/45787536/106615118-675db580-656c-11eb-8a8b-294aebf02493.png)

**Comment by tschubotz** [comment]
Help center article URL will most likely be https://help.gnosis-safe.io/en/articles/4866738-how-are-private-keys-stored-on-gnosis-safe-mobile 
(Currently not active)

Please check back again when actually implementing the feature.

**Comment by liliya-soroka** [comment]
Verified
app ios - app version 2.14.0 (4)
app android - app version 2.12.0 - 2382
