### ISSUE TITLE
v2 Known Addresses

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe#397]
# What is this feature about? (1 sentence)
This feature will display human readable names when interacting with known contracts/protocols such as Uniswap or Compound.

# Why is it needed? What is the value? For whom do we build it?

- The top problem area that we identified is, that users don't know what they are signing and which protocols they are interacting with.
- A first step in getting rid of cryptic addresses is displaying human readable names for known contracts.

# High-level overview of the feature
- There is a list or mapping from addresses to human readable names. 
  - Multiple addresses could map to the same humand readable name.
  - I think this list should be served from the backend, but that's up for discussion.
  - Long term, this list could be an onchain registry curated by Safe governance, but that's for later.
  - Example list: https://docs.google.com/spreadsheets/d/1JVvwTfp3WNQ1CXMx8xVQ2n7Aj-u0KDiXxGHNW5OjHb4/edit#gid=0 
- The web interface should implement this in the same fashion (gnosis/safe-react#1638)
- The protocol/dapp name (and logo perhaps) should be displayed on the tx list.
  - cf. How Safe app txs are displayed in #353 
- On the tx details, the dapp name would also be visible instead of just contract/recipient addresses
  - Same for addresses in decoded data
  - There should be still a way for users to examine the actual address somehow.

# Spec 
 [Known Addresses V2](https://docs.google.com/document/d/1if8Sowyj1VhiVcRQojwmzMuDdo48dyndRBFrzIEa6zk/edit#)

# What's included in v2
- Display known addresses for Safe Apps transactions.
    - Local address book entries have a priority over Safe Apps data in a similar fashion like it is implemented for custom transactions.
- Display known addresses for safe creation transactions.
- Display known addresses for Safe settings screen.
- Display signers known addresses on transaction details screen. [under discussion]

### Backend Issues
- [`SafeInfo` endpoint in the gateway including`AddressInfo`](https://github.com/gnosis/safe-client-gateway/issues/242)
- [Add `KnownAddress` for all addresses in the `CreationTransaction`](https://github.com/gnosis/safe-client-gateway/issues/245)

# What is not included - decoded data 
- Known addresses in multi send action details
- Known addresses in multi send action list
- Known addresses in transaction action details

# Misc 

- "press release": https://docs.google.com/document/d/11ABA0Nj9gQ_yyCTn-4vgNfJ5XqqputXENTNUcIe03E8/edit
- "kickoff meeting": https://docs.google.com/document/d/198DfSRBvyT8UTF8ynNMrcHMFu_2z_d5PFtAgyHs1TAc/edit#

**Comment by posthnikova** [comment]
Would it be possible to make changes to creation tx on the web in v2?

![image](https://user-images.githubusercontent.com/45787536/107783956-2a9f7480-6d4b-11eb-9ca4-ada6aab98238.png)

**Comment by tschubotz** [comment]
> Would it be possible to make changes to creation tx on the web in v2?

Yes, I would say so!

**Comment by liliya-soroka** [comment]
Verified
app version:
ios - 2.13.0 (366)
android - 2.13.0 -2346rc
