### ISSUE TITLE
v3 Known addresses

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe#398]
# What is this feature about? (1 sentence)
This feature will display human readable names when interacting with known contracts/protocols such as Uniswap or Compound.

# Why is it needed? What is the value? For whom do we build it?

- The top problem area that we identified is, that users don't know what they are signing and which protocols they are interacting with.
- A first step in getting rid of cryptic addresses is displaying human readable names for known contracts.

# High-level overview of the feature

Under construction :construction:

# Spec
- [Feature spec: known addresses v3](https://docs.google.com/document/d/1JADxSxlA3JdFcR31CuGuGe8C_tBPgPKjXXoF_OUUlrc/edit#heading=h.97swru4aj8ws)

# Misc 

- "kickoff meeting": https://docs.google.com/document/d/1B3C23VYyCBjl5UEu8OnpGh5-2utcT7__UsWoe7UZBaY/edit#
- specs doc TBD :construction:

# What's included in v3
- Known addresses in multi send action details
- Known addresses in multi send action list
- Known addresses in transaction action details

**Comment by liliya-soroka** [comment]
Verified
android version 3.0.0
