### ISSUE TITLE
Redesign iOS Overview Transactions & Transaction Details

### ISSUE THREAD

**Issue by posthnikova** [gnosis/safe#40]
Redesigning iOS as part of integration proposal. Current designs put for review here: https://invis.io/PEPL75H7ZV6. Previous version for history: https://docs.google.com/presentation/d/1bgn9qh_HWq0poTdxORHkz580B3nKt50tJF6ySZnZXvo/edit#slide=id.g49dff9ba04_0_60

**Comment by posthnikova** [comment]
Since Michel is working on Overview screen only transaction details should be reviewed: https://invis.io/PEPL75H7ZV6

**Comment by tschubotz** [comment]
I think the link is incorrect on your comment @posthnikova 
I get forward to a receive screen: 

![image](https://user-images.githubusercontent.com/1380529/50336527-a5bfc400-050e-11e9-82e4-6ff4923d7e25.png)

I like the card-approach though since it reminds me of a "receipt". We lose some horizontal screen real estate on the other side though. 
Which version do you prefer?

**Comment by posthnikova** [comment]
@tschubotz This is a link to prototype not individual screen, you can press this icon at the bottom to view all: http://joxi.net/Vm6aMbetDJp7Yr
Receive screen goes to #46 but it's a part of Overview prototype so it's in here.
I like card-based version more

**Comment by posthnikova** [comment]
New iteration put for review here: https://invis.io/PEPL75H7ZV6

What's been done:

1. Considering Receive screen: https://invis.io/PEPL75H7ZV6#/336600642_04_SafeAddress-Export_. I propose tap on address should select the address: https://invis.io/PEPL75H7ZV6#/338935572_04_1_SafeAddress-Export_Tap_ 

2. Considering this screen: https://invis.io/PEPL75H7ZV6#/336600645_07_OverviewTxList_. 1) Agree about standard iOS progress bar. 2) Replied about very small amounts on Invision. 3) Corrected the addresses

**Comment by posthnikova** [comment]
New iteration put for review here: https://invis.io/PEPL75H7ZV6

What's been done:

1. Concerning Transaction details: https://invis.io/PEPL75H7ZV6#/336618171_08_TxView_. The version on white background is the main now. This screen opens after we tap on a list item (http://joxi.net/Q2KeyxdU4xLwkr) and it's more logical to have the next screen slide from right than to open card on grey background. 

2. Concerning Receive screen: https://invis.io/PEPL75H7ZV6#/336600642_04_SafeAddress-Export_. Removed redundant titles (address and QR code) so there's no repetition (this also belongs to #46 )

3. Concerning very small amounts on Transactions list: https://invis.io/PEPL75H7ZV6#/336600645_07_OverviewTxList_. Replied on Invision. My proposal is to show more digits after decimal point.

**Comment by DmitryBespalov** [comment]
I've commented in Invision

**Comment by posthnikova** [comment]
Project put for review here: https://invis.io/PEPL75H7ZV6

Main changes: added incoming/outgoing badges in transactions list, decided on how we display digits, changed Receive screen (see also #46), added list element with token

**Comment by DmitryBespalov** [comment]
👍

**Comment by tschubotz** [comment]
Commented on invision 💬

**Comment by tschubotz** [comment]
Can be closed once Zeplin screen are there.

**Comment by posthnikova** [comment]
Zeplin is here:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c4f17d87a8bebbfe8c4163f

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c4f17d87a8bebbfe8c4163f
