### ISSUE TITLE
Passcode v2

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe#401]
# What is this feature about? (1 sentence)
Protect access to the app with a passcode and biometry

# Why is it needed? What is the value? For whom do we build it?

- This relates to the problem that for some users "Storing a key on mobile doesn't feel secure"
- We have implemented the passcode for dealing with transactions.
- Banking apps and other Ethereum wallets have passcodes.
- It should not be possible to confirm txs by someone who is not authorized. An app or confirmation password is an attempt to prevent that.
- It should not be possible to access the app if the passcode/biometry is set.

# High-level overview of the feature

The passcode protects following operations

- app login; 
- enabling biometrics; 
- reducing security by disabling app login / confirmations protection

Password setup is requested at following stages

- After fresh app install

On reset passcode

- wipe out all user data (if it was forgotten on the app log in)

Show following items in settings:

- disable for signing
- disable for login
- enable/disable biometrics

# Specs
https://docs.google.com/document/d/1NegSN4t1dsysUewY_K7v3FLi_sORpS-QpfiTAUZkrn8/edit#

**Comment by liliya-soroka** [comment]
Verified for ios - app version 2.14.0 (4)

**Comment by DmitryBespalov** [comment]
NOTE: on Android, all except biometrics is implemented. The biometrics will be in Passcode v2.1

**Comment by liliya-soroka** [comment]
I prefere to leave it opened till the biometric is implemented on android, as this epic contains the full information about biometric and no separate epic for Passcode v2.1

**Comment by liliya-soroka** [comment]
Verified
android version - 2.17.0 -2758rc
