### ISSUE TITLE
Display more info for module txs

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#402]
# What is this feature about? (1 sentence)

This will add more info to module txs.

# Why is it needed? What is the value? For whom do we build it?

When enabling / disabling a module, that's displayed. However when executing a tx via a module, there's only very limited info, 

<img src="https://images.zenhubusercontent.com/57add4fee40e5714b16d4969/5b2cc74f-0c70-44bd-83a9-b7226a0c586e"  width="350"/> <img src="https://images.zenhubusercontent.com/57add4fee40e5714b16d4969/bf772588-1534-41b3-b285-2a9572aaa25c" width="200" />

# High-level overview of the feature

tbd

### Enable / disable module
- tbd

### Module tx
- Show when a txs was triggered via module - use known addresses here approprirately.

TODO: Create ticket for web as well.

**Comment by liliya-soroka** [comment]
Tx list with module transactions + known addresses:
mobile app: 
![image](https://user-images.githubusercontent.com/338622/114717788-af9c0f80-9d35-11eb-9676-d5e1a48382c2.png)
web app:
![image](https://user-images.githubusercontent.com/338622/114717833-bf1b5880-9d35-11eb-8891-0e7a4fb6946e.png)

**Comment by johannesmoormann** [comment]
handled here https://github.com/gnosis/safe-react/issues/2990
