### ISSUE TITLE
Change branding from Safe Multisig to Gnosis Safe

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#403]
# What is this feature about? (1 sentence)
This will change our branding and name from Safe Multisig to Gnosis Safe

# Why is it needed? What is the value? For whom do we build it?

- We originally called the "new" mobile and web app "Safe _Multisig_" in order to differentiate it from the legacy mobile app.
- There is some confusion currently about "differences" between Gnosis Safe and Gnosis Safe Multisig.
- It is easier for marketing if the apps are just called "Gnosis Safe"
- The web interface already made this transition.

# High-level overview of the feature
Places where we need to adapt:
- App name
- Splash screen (App start)
- Store presence (Name and description)
- In-app update dialogs

# Spec
- [Google Docs](https://docs.google.com/document/d/11X5MMYn_TBN8oJ3dhdJ6JqX-JOKgPd6SLXxdfzil4aU/edit#)

**Comment by liliya-soroka** [comment]
Verified
android app version 2.18.0 -2816rc
ios app version 2.18.0 ( 474)
