### ISSUE TITLE
Ability to generate and backup accounts 

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#407]
# What is this feature about? (1 sentence)
This feature will allow users to generate new accounts on the mobile app in order to use them for signing.

# Why is it needed? What is the value? For whom do we build it?
- [Trello activity](https://trello.com/c/jBrgmyGX)
- [Trello problem statement](https://trello.com/c/ZDoTWje4)

- Importing a private key is cumbersome and feels unsecure
- New users have to generate a private key elsewhere before starting to use the mobile app as a signer
- We would like to enable users to use the mobile Safe app for signing without the need of having to have another wallet setup

# High-level overview of the feature
- In addition to importing keys, users can generate a new seed phrase on mobile and use it to setup new accounts/ private keys.
- Address of accounts can be copied and displayed as QR code (In order to add them as signers on a Safe)
- Users can name/rename/remove the accounts similar to imported keys.
- Wireframes and flows: [Miro](https://miro.com/app/board/o9J_lVtIE0M=/?moveToWidget=3074457358385440714&cot=14)

# Requirements spec
- [Google docs](https://docs.google.com/document/d/18NfOP4xuYnMJ3coWN2ngVwtfF7jn9ca7OfqG79p2L3Q/edit#heading=h.zg3dyho6naep)

## Expected outcome of this epic

- Ready to implement tasks at the end of `Sprint: May 11 - May 24` so it can be implemented in the sprint afterwards
- User flows and screens designs
- Open questions clarified.
- Plan communicated with the team and asked for feedback in Safe internal channel.

**Comment by liliya-soroka** [comment]
Verified
ios app version  - 2.17.0 
android version 2.17.0 -2799
