### ISSUE TITLE
Add support for 1.3.0 contracts

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#411]
# What is this feature about? (1 sentence)
This will allow to use the Safe mobile app with Safe version 1.3.0.

# Why is it needed? What is the value? For whom do we build it?

- [Trello activity](https://trello.com/c/re6Dzq4h)
- [Trello problem statement](https://trello.com/c/hCqIL76o)

- With future support for Layer 2 networks, the Safe contracts 1.3.0 were released.
- It should be possible to use the Safe on Layer 2 networks in the future.

# High-level overview of the feature
- The Safe works with 1.3.0 Safes on all support networks.
- Users can import 1.3.0 Safes
- Users can confirm txs for 1.3.0 Safes
- Users can reject txs for 1.3.0 Safes
- 1.1.1 and 1.2.0 Safes should also be supported still.

# Spec
- [Google Docs](https://docs.google.com/document/d/14rwTq9J8quBY543IWgLIip9pgeIQhCettIxoMoP1LaM/edit)

**Comment by liliya-soroka** [comment]
Verified
ios app version 3.0.0 (6)
android app version 3.0.0 -3090rc
