### ISSUE TITLE
In-app network switching

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#412]
# What is this feature about? (1 sentence)
Instead of having a different app per network/chain, this will allow users to switch the networks inside a single app.

# Why is it needed? What is the value? For whom do we build it?

- [Trello activity](https://trello.com/c/aPubf1cW)
- [Trello problem statement](https://trello.com/c/IYvILpuX)

- While Gnosis Safe already support multiple networks, they are not easily discoverable and it's cumbersome to switch between them
- We expect a lot more (L2) networks to be available soon
- Users are expected to have Safes on different networks simultaneously
- Releasing a different app per network will not be possible with the iOS store guidelines.

# High-level overview of the feature

- _This needs UX work first._
- Being able to use the same app to interact with Safes on different networks

# Open questions

- Different app for prod vs. testnets?

**Comment by liliya-soroka** [comment]
Verified
app versions 
3.0.0 (1) ios
2.19.0 -3047 android
