### ISSUE TITLE
Make adding multiple networks easier

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#413]
# What is this feature about? (1 sentence)
This allows us to faster/more easily add support for new networks chains.

# Why is it needed? What is the value? For whom do we build it?

- [Trello activity](https://trello.com/c/pN2TQM9P)
- [Trello problem statement](https://trello.com/c/hCqIL76o)

- tbd

# High-level overview of the feature
- tbd, depends on #412 also

**Comment by liliya-soroka** [comment]
Verified
ios app version -3.0.0 (3)
android app version 3.0.0 -3057
