### ISSUE TITLE
Redesign token overview screen

### ISSUE THREAD

**Issue by biocom** [gnosis/safe#42]
**Proposal created:**
https://invis.io/P7PP56T9JSZ

**Changelog:**
- TABS > Modified font-size and icon dimensions.
- TABS > Active tab has a ticker bottom border and the text uses the same blue highlight.
- Exclusively uses token symbol codes on the left side.
- Balances are displayed without the token symbol appended.
- Several lengths of balances are displayed to visualize available length and wrapping.
- ADD TOKEN has been added to be in line with the iOS app.

**Comment by tschubotz** [comment]
I like it.
Should we merge this with #41? since both affect the overview screen?

**Comment by fmrsabino** [comment]
I like it! Have you considered removing the icon from the tabs? Not sure if it'd make it cleaner. We only have two options where, for me, I end up reading the text while ignoring the icon.

**Comment by tschubotz** [comment]
In my opinion, icons help the understanding. Also, user testings indicated that they helped (cc @Mettenim )
I would keep them.

**Comment by posthnikova** [comment]
We should merge this with #39 since Michel is working on this now

**Comment by biocom** [comment]
Final proposals up to review:

Android overview screen:
https://invis.io/YZPP4UBKXMW

iOS overview screen:
https://invis.io/WRPZE7XKM5G

One pending aspect of the overview screen is how we'd handle the display of balance amounts with a lot of decimals. I'd suggest for us to open a separate ticket for that.

**Comment by tschubotz** [comment]
Missing:
- Update with decision from #62 
- Upload to zeplin

**Comment by biocom** [comment]
Uploaded to production.

Android:
https://zpl.io/V0EKY5l

iOS:
https://zpl.io/agN4pJ0

**Comment by posthnikova** [comment]
iOS screen was uploaded to the wrong project so here is the right link:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c4f22a250e77937af4b0e9b 

zpl://project?seid=5c4f22a250e77937af4b0e9b&pid=5c49ce9866e3b3bee966f431
