### ISSUE TITLE
Modify Send Token screen

### ISSUE THREAD

**Issue by biocom** [gnosis/safe#43]
Updating the Send Token screen for Android. Different proposals:

Using upfront visible action buttons, according to approx. existing implementation:
https://invis.io/EZPP8NNYXAQ

Using a grouped input field / action button (three dots) which opens a bottom sheet:
https://invis.io/CSPVFSH7QUN
https://invis.io/QRPP8NRSVHX

Please also follow the comments in each of the respective inVision screen.

**Comment by biocom** [comment]
@Mettenim As requested I created a interactive prototype to test the recipient selection screens. Please look at slide https://invis.io/CSPVFSH7QUN and try to click trough the actions.

**Comment by tschubotz** [comment]
In-house testing for Send screen with bottom sheet (Android): https://projects.invisionapp.com/share/ARPG0XSTJMZ#/screens/336852732
@lukasschor @posthnikova will take this over from Minette

**Comment by biocom** [comment]
Updated the screen with the comments from the user-testing:
https://invis.io/ARPG0XSTJMZ#/336852732_22_Send_Token_Entered_-_5

**Comment by biocom** [comment]
Uploaded screens to production:

https://zpl.io/am93qq6 (init. send funds screen)
https://zpl.io/VQKNee4 (bottom sheet)
https://zpl.io/bAZR888 (picked contact)
https://zpl.io/bWg8wAM (pasted or QR scanned address)
