### ISSUE TITLE
When running Tests for BalanceFormatter NBSP is inserted on MacBook with BigSur

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe#431]
And so the tests are failing. 

We need to find out why NBSPs are inserted instead of regular spaces and make either explicit.

**Comment by sche** [comment]
@biafra23 is it an Android issue?

**Comment by biafra23** [comment]
I think this has been resolved. @elgatovital ?

**Comment by biafra23** [comment]
And it is also in the wrong queue :-)

**Comment by elgatovital** [comment]
yes, it's an android issue and it has been resolved.
