### ISSUE TITLE
Multiple networks - Tracking

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#437]
# What is this feature about? (1 sentence)
This will add some tracking info so we can measure how much the app is used with Safes on different networks.

# Why is it needed? What is the value? For whom do we build it?

- So we know on which networks people use the mobile app.

# Requirements

### Add `chain_id` param to `screen_` events

https://github.com/gnosis/safe/wiki/Tracking#screen-view-tracking

- `none` if the chain id is not known yet
- Chain identifier (e.g. `"1"` for mainnet) if it is already known:
  - By default take it from the currently selected safe chain
  - In the flow of adding a new safe specify it as the `future safe` chain id:
    - `screen_safe_add_address`
    - `screen_safe_add_ens`
    - `screen_safe_add_ud`
    - `screen_camera`
    - `screen_safe_add_name`

### Add `user_safe_added` and `user_safe_removed` events

- https://github.com/gnosis/safe/wiki/Tracking#user_safe_added
- https://github.com/gnosis/safe/wiki/Tracking#user_safe_removed

### Add `chain_id` param for the following events

- `user_transaction_confirmed`
- `user_transaction_confirmed_walletconnect`
- `user_transaction_rejected`
- `user_transaction_rejected_walletconnect`
- `user_transaction_executed_walletconnect`
- `user_dapp_connected_scan_button`
- `user_dapp_connected_universal_link`
- `user_dapp_connected_pasteboard`
- `incoming_transaction_confirmed`
- `incoming_transaction_confirmed_wc`

**Comment by sche** [comment]
@tschubotz I think that `chainId` param is better because if the `name` is changed it might be more work to group together with previous names when analyzing.
I think there will be 2-5 leaders, and some chainIds we will know by heart.

**Comment by tschubotz** [comment]
Sure, then let's switch to `chain_id`! Could you please take updating the ticket and docs?

**Comment by liliya-soroka** [comment]
Verified
app version 3.0.0-3090
app version 3.0.0(6)
