### ISSUE TITLE
Non-owners cannot access Safe apps

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#445]
# Problem summary
The interface currently prevents non-owners from accessing any Safe apps.

# Problem details

- The assets of a Safe and e.g. locked funds in dapps are public data.
- Safe apps such as portfolio trackers provide in some cases a nicer overview of the Safe assets than our interface. 
- Currently it's simply the frontend that prevents non-owners from accessing any Safe app.
- Even when just viewing your own Safe, you always need to connect an owner wallet even though nothing needs to be signed.

# Solution ideas

- Allowing non-owners to view Safe apps.
- Allow non-owners to go through the tx flow until the review screen, but disable the "submit" button.
  - With SafeSnap becoming more and more popular, this could simplify collecting transaction data. Why? Currently, in order to create a tx via SafeSnap, the entire tx (i.e. the payload) needs to be assembled manually. When non-owners could view Safe apps and go through the tx flow, they could copy the resulting payload on the last screen and copy-paste that into SafeSnap. It still needs to be verified if it is correct, however that initial creation of the payload is simplified.

**Comment by katspaugh** [comment]
Solved in the issue linked above.
