### ISSUE TITLE
Owner on mobile cannot initiate transactions

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#446]
# Problem summary
It is currently not possible to initiate a transaction from mobile directly without having a different owner connected to web.

# Problem details

- Tx initiation is only possible via the web interface currently.
- Users can add an owner account to the Safe mobile app.
- This mobile owner can only act as signer, but not as tx initiator.

# Solution ideas

- Allow to connect owner on Safe mobile to web interface via WalletConnect to initiate txs.
- Generally allow tx initiation on mobile.

**Comment by sche** [comment]
Issue moved to [gnosis/safe-pm #19](https://github.com/gnosis/safe-pm/issues/19) via [**ZenHub**](https://www.zenhub.com/)
