### ISSUE TITLE
Storing a private key on mobile does not feel secure

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#449]
# Problem summary
Currently, in order to sign with the Safe mobile app, a key needs to be stored inside the app. That is not an option for all our users.

# Problem details

- Users can import a key on mobile in order to sign txs.
- Users can generate a new key on mobile in order to sign txs, but then that owner needs to be added to a Safe first.
- We got the feedback that not all users feel comfortable importing a key on mobile or even generally storing a key on mobile.

# Solution ideas

- Allow to sign with hardware wallets on mobile
- Allow to sign with other mobile wallets via Walletconnect.
- Research on what other options there might be to "make it feel more secure"
  - Is there a difference to Android and iOS? 
  - Is it related to user education?

**Comment by fmrsabino** [comment]
I recommend this reading for Android: https://source.android.com/security/keystore

> In Android 6.0, Keystore added symmetric cryptographic primitives, AES and HMAC, and an access control system for hardware-backed keys. Access controls are specified during key generation and enforced for the lifetime of the key. Keys can be restricted to be usable only after the user has authenticated, and only for specified purposes or with specified cryptographic parameters. For more information, see the Authorization Tags and Functions pages.

> In addition to expanding the range of cryptographic primitives, Keystore in Android 6.0 adds the following:

> A usage control scheme to allow key usage to be limited, to mitigate the risk of security compromise due to misuse of keys
An access control scheme to enable restriction of keys to specified users, clients, and a defined time range
In Android 7.0, Keymaster 2 added support for key attestation and version binding. Key attestation provides public key certificates that contain a detailed description of the key and its access controls, to make the key's existence in secure hardware and its configuration remotely verifiable.

My personal opinion on this: if we think/assume that the mobile phone is not a secure place to store it then the same argument can be made for hardware wallets. Devices need to go through certification regarding the hardware features that they provide.

As a course of action:
1. I would evaluate both Android and iOS regarding the current hardware security mechanisms being offered.
2. If an improvement can be made on our side then we should consider what are the advantages of using that security mechanism. Example: Maybe we see that Android 7 provides the minimum acceptable requirements for our use case so we think about having Android 7 as part of the requirement to add the Gnosis Safe (at the cost of losing users which are not on that version or above)
3. Optionally we create an help article on the security mechanisms that we both offer on Android and iOS to create awareness.

Finding an attack vector on the latest security mechanisms on both Android and iOS sounds not only unlikely but would be a big issue not only for Gnosis Safe but for any secure data which is currently stored (2FA, passwords, banking, etc...)

------

More on the product side: if we see that the mobile app can be on read-only state then the user doesn't need to provide any private key at all.

**Comment by tschubotz** [comment]
> My personal opinion on this: if we think/assume that the mobile phone is not a secure place to store it then the same argument can be made for hardware wallets. Devices need to go through certification regarding the hardware features that they provide.

Agree. Actually it's why we do multisig in the first place: You ideally need more than just 1 key to authorize txs.



> I would evaluate both Android and iOS regarding the current hardware security mechanisms being offered.
> Optionally we create an help article on the security mechanisms that we both offer on Android and iOS to create awareness.

Actually we partially did that already. This was the outcome: https://help.gnosis-safe.io/en/articles/4866738-how-are-private-keys-stored-on-gnosis-safe-mobile. But I agree we could do more. Afaik on Android currently accessing the key doesn't require any user input. Perhaps that could be adjusted. I think @biafra23 mentioned that during the weekly.
