### ISSUE TITLE
Frequently used Safe apps cannot be accessed easily

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#451]
# Problem summary

Currently, accessing frequently used Safe apps required multiple clicks.

# Problem details

- The Safe apps list became quite messy.
- Frequently used apps are as hard accessible as any other Safe app.

# Solution ideas

- Implement manual Safe apps favorites
- Have a special list or section for the most recent or most used Safe apps.

**Comment by sche** [comment]
@DaniSomoza should we close it?

**Comment by DaniSomoza** [comment]
CC: @dasanra

**Comment by dasanra** [comment]
@sche I would say yes. We already have some solution to make them more easy to access. Having them as favorite will take them to the top of the list.
