### ISSUE TITLE
No way to see why a transaction failed 

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#454]
# Problem summary

There is currently no easy way to see why a transaction failed.

# Problem details

- Every now and then Safe txs fail.
  - cf. https://explore.duneanalytics.com/dashboard/gnosis-safe---transaction-results
- In our interface, we only display "failed", no further information.
- We have a help center article on the topic: https://help.gnosis-safe.io/en/articles/5250281-my-safe-transaction-failed-what-went-wrong

# Solution ideas

- Research and identify the problem and check if there are any quick fixes.

**Comment by sche** [comment]
Issue moved to [gnosis/safe-pm #21](https://github.com/gnosis/safe-pm/issues/21) via [**ZenHub**](https://www.zenhub.com/)
