### ISSUE TITLE
No address book on mobile

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#457]
# Problem summary

We have the address book on web but currently not on mobile

# Problem details

- The address book allows users to provide names to addresses. 
- Those names/labels are used on the tx list and the tx details.
- We implemented import and export on web.

# Solution ideas

- Allow to create, edit, delete address book entries on mobile.
- Allow import and export of the address book between mobile and web

**Comment by sche** [comment]
We can close this problem after Address Book on Mobile v2 is implemented

**Comment by sche** [comment]
Issue moved to [gnosis/safe-pm #20](https://github.com/gnosis/safe-pm/issues/20) via [**ZenHub**](https://www.zenhub.com/)
