### ISSUE TITLE
Align "receive" screen on iOS and Android

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#46]
As part of our alignment of Safe iOS and Android design, we should unify the receive screens on both platforms.

Things I like on iOS:
* Format of the address (Highlighting of first and last 4 chars)
* The info text on top with the purpose of the address etc. ("Receive Ether and tokens ...")
* Bigger (more visible) identicon.

Things I like on Android: 
* Clarity, less cluttered
* Share button more obvious
* Long tap to copy address.

Current iOS Version:
<img src="https://user-images.githubusercontent.com/1380529/50233344-87918100-03b3-11e9-8c34-75dcc2087d33.png" width="200"/>

Current Android version:
<img src="https://user-images.githubusercontent.com/1380529/50233372-99732400-03b3-11e9-94ea-99760f5ed403.png" width="200"/>

**Comment by posthnikova** [comment]
There is a proposal for iOS here: https://invis.io/PEPL75H7ZV6#/336600642_04_SafeAddress-Export_. Info is taken from iOS and center alignment from android. On iOS we use buttons on top everywhere so I'd rather not change this pattern

**Comment by posthnikova** [comment]
New Receive screen put for review here: https://invis.io/PEPL75H7ZV6#/336600642_04_SafeAddress-Export_. If it's approved I guess it should be changed on Android too cc @biocom

**Comment by DmitryBespalov** [comment]
good to me

**Comment by tschubotz** [comment]
I like it, too. 
@biocom What do you think about it? Could you please adapt Android as well?

**Comment by biocom** [comment]
@tschubotz Adapted to match iOS:
https://invis.io/ARPG0XSTJMZ#/339765462_17_-_Receive_Token

Deviated slightly from iOS on certain aspects after discussing with @posthnikova

**Comment by tschubotz** [comment]
🙌  Looks good. 

Long tap on the address should copy it to the clipboard? If so, I would add a small info text stating this.

**Comment by posthnikova** [comment]
I updated Receive screen according to android: https://invis.io/PEPL75H7ZV6#/336600642_04_SafeAddress-Export_

My proposal is to use long tap functionality without displaying additional "Copy" text or action. Because there would be two Copy actions on the screen at the same time, maybe even in different languages, and it would be confusing which of them to use.

Long tap opens "Copy" action: https://invis.io/PEPL75H7ZV6#/338935572_04_1_SafeAddress-Export_Tap_


After tapping "Copy" there is a popover "Copied to clipboard" which disappears after 1 second: https://invis.io/PEPL75H7ZV6#/342561292_04_2_Safe_Address_Export_Copied_

**Comment by biocom** [comment]
After discussing this with @posthnikova we came to the conclusion that:
- We don't need a separate 'copy' button
- We resort to the native tap/hold of the address to get the native 'copy' options (both iOS and Android)
- Also the 'Share' button likely would have a 'share to clipboard' feature of some sorts?

Mockup:
https://projects.invisionapp.com/share/ARPG0XSTJMZ#/screens/339765462_17_-_Receive_Token

Let me know your thoughts.

**Comment by tschubotz** [comment]
"We resort to the native tap/hold of the address to get the native 'copy' options (both iOS and Android)"

Like it, generally. Just today I've seen someone attempting that in the current Android version. He has disappointed that it didn't work.
By native tap/hold you mean that the text would be highlighted? Or no further indication?
Would we display a toast or some other info if the text has been copied to the clipboard? That might be needed.

**Comment by tschubotz** [comment]
Ah I just now read Sasha's comment. She basically suggested the same :D
Agree that we need a "copied successfully" indication

**Comment by tschubotz** [comment]
UX sync outcome:

- Normal tap AND long tap would copy the address straight away -> "Copied to clipboard" info would be displayed.

**Comment by DmitryBespalov** [comment]
👍

**Comment by biocom** [comment]
@tschubotz So the tap/hold is essentially how the current version of the Android app works, on the 'Receive Funds' screen. The toast could look like:
https://invis.io/ARPG0XSTJMZ#/343080915_17_-_Receive_Token_-toast-Copied-

**Comment by posthnikova** [comment]
Final updates:

Receive screen (nothing changed): https://invis.io/PEPL75H7ZV6#/336600642_04_SafeAddress-Export_

After tap AND long tap the address immediately selects and there is a popover "Copied to clipboard", both disappear after 1 second:
https://invis.io/PEPL75H7ZV6#/338935572_04_1_SafeAddress-Export_Tap_

**Comment by biocom** [comment]
Uploaded the Android for production:
https://zpl.io/am6Z9wm
https://zpl.io/aByP18A

**Comment by posthnikova** [comment]
iOS is here:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431?seid=5c4f17d87a8bebbfe8c4163f

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c4f17d87a8bebbfe8c4163f

**Comment by biocom** [comment]
Production screens for Android/iOS have been provided. Closing this ticket.
