### ISSUE TITLE
 Display decoded and raw tx data for all tx types in tx flow

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#460]
# Problem to solve

#441 

# Requirements

- [ ] User can examine advanced info about the Safe tx on tx review screen for all tx types
  - `safeTxHash`
  - `nonce`
  - `to`
  - `value`
  - `data` - no need to display in full, being able to copy is sufficient
  - `operatiom`
  - `safeTxGas`
  - `baseGas`
  - `gasPrice`
  - `gasToken`
  - `refundReceiver`
  - `signatures`
- [ ] If available user can view decoded tx data on tx review screen for all tx types

# Misc

- cf. how it's done for Safe apps already

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1380529/126660765-d96101dc-c105-4fff-9a52-494939fb57c1.png">

**Comment by biafra23** [comment]
@tschubotz What is the "tx review screen"? Do we have it already on mobile? Is it the tx details screen?

**Comment by DmitryBespalov** [comment]
@biafra23 we don't have the tx review screen on mobile yet. We would have it when we would implement the transaction creation from mobile

**Comment by biafra23** [comment]
@DmitryBespalov "tx flow" is the work flow of creating a transaction?

**Comment by DmitryBespalov** [comment]
@biafra23 yes, what is meant is the creation transaction flow on the web

**Comment by liliya-soroka** [comment]
Implemented and verified on mobile:
android version - 3.2.0 -3396rc
ios version 3.3.0 (666)

**Comment by sche** [comment]
@johannesmoormann can we close it?
