### ISSUE TITLE
Improve Safe apps list

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#470]
# Problem to solve

#451 and #452

# Requirements

- [ ] Evaluate status quo and painpoints and adapt the following items depending on the outcome:
- [ ] User can access most recently used Safe apps
- [x] User can search for Safe apps
- [ ] User can filter Safe apps
- [x] User can favorite Safe apps

# Misc

Should we rename Safe apps to Safe dApps?

**Comment by johannesmoormann** [comment]
Solved for now with the current implementation of bookmarking and search function.
