### ISSUE TITLE
UI design for Create Safe flow

### ISSUE THREAD

**Issue by posthnikova** [gnosis/safe#48]
Redesigning iOS as part of integration proposal

**Comment by tschubotz** [comment]
I left some comments on the Invision. In general, I like the card - layout here as well. I'm just worried about consistency. We should think about guidelines when to use cards and when not.

**Comment by DmitryBespalov** [comment]
all good from my side, looks gorgeous.

**Comment by DmitryBespalov** [comment]
👍

**Comment by posthnikova** [comment]
Project is up for review here: https://invis.io/FXPSG91SV8B

Main changes: updated Receive card, added error state

**Comment by tschubotz** [comment]
merging this with Android  #69

**Comment by tschubotz** [comment]
Needs changes after user test #119

**Comment by posthnikova** [comment]
I see Android is updated after user tests.

1) The wording on 2-FA screen updated
2) Minuses removed

There is only one change required: the wording on Creating in progress screen needs update. 
Android screen: https://invis.io/RZQDYUJWHYC#/345460257_New_Safe_-_Deposit_Received
iOS screen: https://invis.io/FXPSG91SV8B#/347431908_13_Creating_Safe_ 

Can we close this after this change is made? @tschubotz @biocom

**Comment by biocom** [comment]
@posthnikova did we decide yet on using cards yet? Right now that screens differs quite a bit.

I know that iOS uses a white bg and Android a grey one. But I'm still very much in favor of having that card style in the progress screen for Android.

Could we say that this is something both platforms could have a bit different in terms of layout implementation? @tschubotz @posthnikova

**Comment by posthnikova** [comment]
> I know that iOS uses a white bg and Android a grey one. But I'm still very much in favor of having 
> that card style in the progress screen for Android.

I'm for white background because there is not too much content and all is related to the same subject

**Comment by biocom** [comment]
No card + white bg for Android needed @biocom

**Comment by biocom** [comment]
Updated https://invis.io/9CQQDZ9QPSK - Please review.

**Comment by tschubotz** [comment]
👌 

Is there a link for the Android flow?
If Android and iOS are similar, then we can also upload the screens to Zeplin and close the ticket  :)

**Comment by posthnikova** [comment]
Zeplin for ios is here:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c767b99c36416627a138d67

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c767b99c36416627a138d67

**Comment by biocom** [comment]
Android production screens:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c504b5b505721bf1335da4c
