### ISSUE TITLE
Test automation

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe#485]
# What is this about? (1 sentence)
Keeping quality while improving development speed

# Why is it needed? What is the value? For whom do we build it?
This would reduce the manual effort for regression testing and would provide early defect detection mechanism when changing the source code hence improving both the time to market and quality.

# High-level overview
- Create a plan for test automation on both mobile platforms.
- Prioritize high-effort and high-value test cases.
- Schedule and manage the effort to automate the tests.

# Expected outcome
- Tasks for Android and iOS repos to automate manual tests.
- Unit testing is required as part of the code review process.
- Unit testing and regression testing (and automation) is included during requirements development.

# Links
- Spec doc https://docs.google.com/document/d/1fGBy6bIVYyYDotGq-FxFCKRC2L3XEUsh_PzR-Ya5Jxw/edit#heading=h.44smlo9g2y3x

**Comment by DmitryBespalov** [comment]
test automation will be as an extra project, I will not track it on the roadmap right now. Closing as won't fix.
