### ISSUE TITLE
EIP-3770 Reference Implementation

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe#487]
# What is this feature about? (1 sentence)
Implement a reference implementation for chain-specific (EIP-3770) addresses in our interfaces

Example of EIP-3770 addresses:
![image](https://user-images.githubusercontent.com/17196842/133583383-14ab4353-7831-418c-87b0-7c5dca43772c.png)

# Why is it needed? What is the value? For whom do we build it?
The motivation of chain-specific addresses is described in the EIP: https://github.com/ethereum/EIPs/pull/3770
The motivation for having a reference implementation is to:

- Rally the community behind adopting the EIP by having some live example that people can take a look at
- Establish a technical reference for other wallets / dApps adopting the EIP
- Already partially solve our problem with users sending funds to wrong networks, as this reference implementation will make it very explicit that a Safe address is only available on a specific chain

# High-level overview of the feature
- Every input field that accepts blockchain addresses should also accept the EIP-3770 format and be able to validate it (i.e. check if the input address has a network prefix that corresponds to the network of the current selected Safe)
- Non EIP-3770 addresses should still be accepted in all input fields (ensure backwards compatibility)
- Output all addresses in the Safe interfaces in the EIP-3770 format 
  - Potential exception: keys/owners as they are not chain-specific for the most part (edge-case: owner is a contract account)
  - Should we actually render the prefix when displaying addresses or just add the prefix when using the copy-to-clipboard button?

# Expected outcome
- User is able to use an address in the EIP-3770 format in every input field and gets an error if the address is not on the correct network
- User sees addresses displayed in the new format wherever chain-specific addresses make sense
- It is expected that other wallets / dApps to not support input of EIP-3770 addresses for some time, which makes it a bit cumbersome for users forwarding EIP-3770 addresses to others or using them outside of the Safe interfaces, but it is worth taking this inconvenience to make the chain-specific nature of Safes very explicit. Worst case users have to remove the prefix manually, so it is not a security issue itself.

# Other things
- If the full implementation has to be split into multiple releases, it might make sense to first implement the input part, before outputting addresses in the new format.
- Probably best to use the ethereum-lists shortName mapping (https://chainid.network/shortNameMapping.json / https://github.com/ethereum-lists/chains/pull/360) to map a chainID to a shortName.
- Kickoff doc: https://docs.google.com/document/d/1iUuNO8ObL45A6lTper1HdZPtZyY88qm_B27g2v2z4gU/edit

**Comment by biafra23** [comment]
What are we going to use for generating QR codes? EIP-55 or EIP-3770 addresses?
Or should we show 2 QR codes?

In a text field it is easy to remove the prefix. But a QR code might be pasted into a validated field of an application we’re not maintaining. So we should probably got for 2 QR codes and label them accordingly.

**Comment by biafra23** [comment]
Should we also accept CAIP-10 account identifiers as inputs?

**Comment by rmeissner** [comment]
> What are we going to use for generating QR codes? EIP-55 or EIP-3770 addresses?

We decided to allow toggling in the QR dialog. The default will be EIP-3770

> Should we also accept CAIP-10 account identifiers as inputs?

This would be optional

**Comment by liliya-soroka** [comment]
Verified ( ios only)  and web
app version 3.4.0
