### ISSUE TITLE
Push Notifications with Delegates v1

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe#496]
# What is this feature about? (1 sentence)
Enabling Ledger Nano X and WalletConnect keys to receive push notifications

# Why is it needed? What is the value? For whom do we build it?
For owners who connect external wallets to their safe and want to be aware of signing requests

# High-level overview of the feature
- When an external wallet (h/w or mobile app) is connected as an owner key then have an option to register for push notifications for that key
- This would create and register a delegate key for all currently available chains
- This would make the app register for push notifications with the delegate key, and so user doesn't need to sign with the actual key every time we need to register for pushes

# Expected outcome
- Able to register and receive signing request push notifications for Ledger Nano X key
- Able to register and receive signing request push notifications for WalletConnect key: Metamask, Rainbow, Trust wallets

# Other things
- Requirements doc: https://docs.google.com/document/d/1xO0q843Qb0MwcLjpANY0bRKdHJC0_hyvj60NQjLnkM0/edit#
- See v2 epic: #484

**Comment by liliya-soroka** [comment]
Verified ( ios only)
app version 3.5.0 (749)
