### ISSUE TITLE
Many users drop on mobile after the first App install

### ISSUE THREAD

**Issue by sche** [gnosis/safe#498]
# Problem summary
Currently, we have new users on mobile that don't know what to do if they don't have a Safe yet.

# Problem details
On mobile, it is not possible to create Safe. Users are often lost when they come to the screen when they need to specify a Safe address for some network

# KPIs
- Percentage of users that install Mobile App and successfully add a Safe that they (co-)own

# Solution ideas
- Enable demo mode on mobile
- Navigate users to the web interface if they are stuck
- Allow importing Safe via owner keys
- Allow Safe creation on Mobile devices

**Comment by DmitryBespalov** [comment]
Question for me here: those users that drop - what do they want? Do they want to use safe or they need a wallet or maybe they don't know themselves?

**Comment by sche** [comment]
Issue moved to [gnosis/safe-pm #16](https://github.com/gnosis/safe-pm/issues/16) via [**ZenHub**](https://www.zenhub.com/)
