### ISSUE TITLE
Update Safe Start Screen

### ISSUE THREAD

**Issue by biocom** [gnosis/safe#50]
@tschubotz  Based on https://github.com/gnosis/safe-android/issues/304

Proposals:
- Android: https://invis.io/ARPG0XSTJMZ#/337567048_-ANDROID-_2-_Welcome_Main
- iOS: https://invis.io/PYPF44ESJ6X#/336311762_01_Start_

**Comment by tschubotz** [comment]
Looks good to me, it's just text in the end :P 
The Android one seems so big to me though?

**Comment by biocom** [comment]
Indeed to your point it's just text, based on the original ticket. I guess from a UI perspective I propose to make it a bit bigger than we had. This is how it looks like for me on Android:
![screenshot_20190108-155653](https://user-images.githubusercontent.com/31534717/50893188-9a223780-1400-11e9-8b55-079c8354a57d.png)

Personally I think the amount of padding around the text is sufficient. But let me know if you think it's too big.

**Comment by tschubotz** [comment]
I think it's fine. Let's use these versions.

**Comment by biocom** [comment]
@fmrsabino @rmeissner  screen uploaded for production (Zeplin):
https://zpl.io/awWeWmj
zpl://screen?sid=5c376867aadb39be23415739&pid=5af063c9b4dc859b6bdaf897

**Comment by posthnikova** [comment]
This is a proposal for iOS: https://invis.io/PYPF44ESJ6X#/336311762_01_Start_

**Comment by tschubotz** [comment]
Spec is written (#88) We can close this as soon as the iOS screen is on Zeplin :)

**Comment by posthnikova** [comment]
Added Start screen for production in Zeplin:

https://app.zeplin.io/project/5b8e45a7e1140d2c63bc08d1/dashboard?seid=5c050e5896a61101f759b799

zpl://project?pid=5b8e45a7e1140d2c63bc08d1&seid=5c050e5896a61101f759b799
