### ISSUE TITLE
Integrate Intercom on Mobile

### ISSUE THREAD

**Issue by sche** [gnosis/safe#500]
# Problem to solve
#499 

# What is this feature about?
Integrate Intercom solution that we use in Web on Mobile

# Links
[Requirements](https://docs.google.com/document/d/1QGZaTEVxUhW4MHCIHjzlVV3lt_EeeQRG0TUu_C-58BQ/edit#)

**Comment by biafra23** [comment]
Research needed:

Is the Intercom SDK open source on Android and IOS?
-> yes: https://github.com/intercom/intercom-ios
Is it possible to use an external intercom app and launch it via intent?

**Comment by liliya-soroka** [comment]
Waiting for "Push notifications" task and 2 bugs are fixed

**Comment by liliya-soroka** [comment]
Closed
app version 3.6.0 (822)
The major issues will be fixed in 3.7.0 release

android app version 3.4.0 -3428rc
