### ISSUE TITLE
Execute Tx on Mobile without relayer v1

### ISSUE THREAD

**Issue by sche** [gnosis/safe#502]
# Problem
#501 

# What is this feature about? (1 sentence)
Add limited functionality for executing transactions with imported owner keys.

# High-level overview of the feature
- Showing balance of native coin on a private key address
- Estimating and sending transactions to the node
- Showing ‘pending’ transaction in the transaction queue
- Having only one pending tx

# Links
[Requirements](https://docs.google.com/document/d/1neOhLLLsC4-7BtJO01GurgyLBUgaPfLzp8tflOiLCrs/edit#)

**Comment by DmitryBespalov** [comment]
I am closing this because the epic is implemented. Other issues are moved to v2.
