### ISSUE TITLE
Initiate assets transfer on mobile (ETH/Chain Token, ERC-20)

### ISSUE THREAD

**Issue by sche** [gnosis/safe#503]
# Problem
#446 , partially #442 

# What is this feature about? (1 sentence)
Allow mobile users to make most common funds transfer operations - ETH/Chain Token and ERC-20 tokens transfer.

# Links
[Requirements](https://docs.google.com/document/d/1Wgl7Ue2LKxoNZVtlZ6PaAnSsNAgfKvmv1oiUMhZwRDI/edit#)

# Acceptance Test Cases

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.1(3)
