### ISSUE TITLE
[WebConnect] Connect Mobile Key To Web

### ISSUE THREAD

**Issue by sche** [gnosis/safe#506]
# Problem
https://github.com/gnosis/safe-pm/issues/19 

# What is this feature about? (1 sentence)
Connecting existing keys in the mobile app to the web app so that they are used as a signer or a wallet.

# High-level overview of the feature
- Connect a key that is added to mobile app to the Web app for transaction signing and execution
- Connect, disconnect, view details of connection
- Signature request for eth_sign and transaction request for eth_sendTransaction

# KPIs
- Web-users using the mobile app
- Tx confirmations done with the mobile app

# Links
[Requirements](https://docs.google.com/document/d/1k6riuNvINVppI6af04hqp4jpa4svFyl2o1VUWwnqefU/edit)
[Technical Documentation](https://docs.google.com/document/d/12WGo9k5BTcGaQDKPiCCCy5QAoW1kXqcp/edit#bookmark=id.gjdgxs)
[Figma](https://www.figma.com/file/IjW9CfVZvUqiMgj28euXVX/Desktop-Pairing?node-id=385%3A2905)

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (884)
