### ISSUE TITLE
[CreateSafe] Create Safe v1

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe#528]
# What is this feature about? (1 sentence)
https://github.com/gnosis/safe-pm/issues/16

This is about creating a safe on mobile

# Why is it needed? What is the value? For whom do we build it?
Users would be able to create safe from their device. New users would be able to use mobile after installation without need to switch to web.

# High-level overview of the feature
- Instructions screen
- Setup Safe screen
- Deploying safe screen
- Success safe screens

# Expected outcome
From the problem statement:

-  The share of the onboarded users has increased over time compared to the previous release (within a date range of at least 30 days)
-  At least 10% of previously dropped users end up with a new Safe.
-   The drop-off hasn't decreased significantly after the solution has been release.

# Other things
- Spec doc: https://docs.google.com/document/d/19y6C9zARGMUyzE5n4ay_SUgLmZPmA0HXS-3TkJyNf5Y/edit# 
- Figma: https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=684%3A7349

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (936)
