### ISSUE TITLE
Add 'failed' transaction detail view

### ISSUE THREAD

**Issue by biocom** [gnosis/safe#53]
Currently we don't have a preview of a FAILED transaction detail screen.

**Comment by biocom** [comment]
Android screen uploaded to Zeplin:
Web: https://zpl.io/boKNxEg
App: zpl://screen?sid=5c360e30414579beec02c0e9&pid=5af063c9b4dc859b6bdaf897

iOS screen pending, issue remains open.

**Comment by biocom** [comment]
As discussed with @tschubotz @posthnikova for iOS we also want to prepare the design to indicate incoming/outgoing/failed transactions with an icon over the identicon. 

Currently there's an existing design for this for Android: 
https://zpl.io/VDOglMq

By having the iOS design for it ready we anticipate for when this feature set would get implemented.

**Comment by posthnikova** [comment]
Added incoming/outgoing/failed badges over the identicons in transactions list.

Current iOS version: https://zpl.io/agNyd7O, zpl://screen?pid=5b8e45a7e1140d2c63bc08d1&sid=5b968ec0d93813278c9fbdfe 

iOS integration: https://invis.io/PEPL75H7ZV6#/336600645_07_OverviewTxList_

**Comment by biocom** [comment]
@posthnikova Looks really good. I like how you enhanced the layout for the TX list (specifically the grey headers). Good to go 👍

**Comment by DmitryBespalov** [comment]
👍

**Comment by tschubotz** [comment]
I'm closing this, since the screens are already implemented and Sasha added them to Zeplin (https://github.com/gnosis/safe/issues/53#issuecomment-453988124) 

The remaining things like the little indicators are discussed already as part of #40
