### ISSUE TITLE
Align UI: Token selection

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe#58]
# What is this feature about? (1 sentence)
This feature will enable users to choose which tokens they see inside their Gnosis Safe app.

# Why is it needed? What is the value? For whom do we build it?
Besides ETH, we currently support ERC20 tokens. There are simply too many tokens to display them all. For a user only a small number is important.

# High-level overview of the feature
- The backend provides a list of tokens including all relevant info (logo, address, decimals etc)
- Users can search by token name and symbol
- User can enable and disable tokens.

# Screens
https://docs.google.com/document/d/182VRSCKcqKmV4dXm7qQFDiW-pN_uWaFqiQ8_McIibaI/edit#

**Comment by tschubotz** [comment]
Android has done this. iOS is doing this as part of #182 so closing the ticket.
