### ISSUE TITLE
Add missing iOS features

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe#59]
(@tschubotz tampered with this description ;) )

# Problem statement
* iOS is still missing quite some features that we already have. We should add them.

# Additional info
* After writing the spec, we should review Android and see if all features are implemented according to it and adapt if necessary.

**Comment by DmitryBespalov** [comment]
@tschubotz what about address book?

**Comment by tschubotz** [comment]
Address book is missing, will add.
"Rate app" is a different feature. Can be part of a different Epic.

**Comment by tschubotz** [comment]
Closing this thing for better overview and the fact that it's just a "collection epic"
