### ISSUE TITLE
Batch / bulk transactions

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#6]
**Background**
Instead of requiring the user to sign multiple transactions when performing just 1 logical action (e.g. when interacting with dApps), we should batch these together via the multi_send library.

**Details**
- We should work on an EIP to standardize this.
- https://github.com/gnosis/safe-contracts/blob/development/contracts/libraries/MultiSend.sol

**Comment by frangio** [comment]
How has this been resolved?

**Comment by tschubotz** [comment]
This one was closed due to inactivity and in order to clean up this repo. Nothing has actually been implemented or released here.
