### ISSUE TITLE
Replace Browser Extension

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe#60]
# Story
As a user I am able to replace the browser extension connected to my Safe in order to change to a new laptop if needed.

# Background
The Android app has that feature already. We left it out for the first iOS version but should add it soon.

# Specs
https://github.com/gnosis/safe/tree/master/specs/replace_browser_extension

**Comment by tschubotz** [comment]
Android flow is still a bit different. Still closing this since I don't see high value in adapting this for Android at the moment.
