### ISSUE TITLE
Truncate/abbreviate balance amounts

### ISSUE THREAD

**Issue by biocom** [gnosis/safe#62]
In the Safe overview (Assets) we need to truncate amounts if they surpass more than 5 or 6 decimals (maybe 4, considering smaller width viewports). Displaying an arbitrary amount of `0.00000200` is one of the cases we need a solution. 

Current implementation (iOS):
- `0.000~ ETH`

A solution proposed in @posthnikova 's comp:
- `< -0.0000` or `< +0.00` (Sasha rightfully states that the arrow doesn't go well with the - or + sign.)

Also for large amounts (`100,000,000.9999`) we need consensus on how we deal with this throughout our web/mobile interfaces. In case of the above figure we could abbreviate it for example to 100 Bln. or 100B. Is abbreviating amounts currently implemented? 

In general the central question is, what purpose the Assets overview serves: a (rough) overview for users to see their balances and for seeing precise amounts, they'd click on the token? Is this an acceptable (initial) learning curve and do we run into edge cases with certain assets/tokens?

- Internal discussion on this: https://projects.invisionapp.com/share/PEPL75H7ZV6#/screens/336600645/comments/108645512

Maybe worth it to check out how others are (trying) to solve for this and some other resources I could find on it:
- https://github.com/balance-io/balance-wallet/issues/13
- https://github.com/balance-io/balance-manager/issues/400
- https://ux.stackexchange.com/questions/23991/conventions-for-the-display-of-large-numbers

@Mettenim feel free to take over this ticket.

**Comment by posthnikova** [comment]
I think it depends on the value of token. I think balances like 100,000,000.9999 are unrealistic but there could be such cases in the future.

I propose not to truncate anything if there is enough space.

• For very small amounts - display up to 7 digits and ~, for example 0.0000003 becomes 0.000000~

• For amounts >1 with a lot of digits after decimal point - display up to 7 digits. If there is not enough space, round them. For example, 1.0874892 becomes 1.087489

• For very large amounts - if the amount is longer that 7 digits AND there is not enough space, abbreviate them. I propose to spell large numbers in full (million, billion). For example, 100,000,000.9999 becomes 1 billion. 1.845.989,0879 becomes 1.85 billion. Also we need to decide which system we use (english? american? german?) (see https://en.wikipedia.org/wiki/Long_and_short_scales)

Let's look at the examples where we need truncation. I'm taking smallest screen (iphone 5) here:

1) Send ETH (Send Token) screen: https://invis.io/FBPH0OFQ57P#/339971943_03_Send-ETH-Filled_
Current balance (up to 10 digits). Here we need to know the exact amount, but abbreviation is possible.
Input field with amount (up to 20 digits), here we too need to type exact amount. No truncation or abbreviation possible.
Current balance, transaction fee, balance after transfer could be truncated to 7 digits or abbreviated

2) Send ETH review screen: https://invis.io/FBPH0OFQ57P#/339971946_06_Send-ETH-Review_IPhone5_
Current balance (7 digits), transaction amount (7 digits)
Current balance, transaction fee, balance after transfer could be truncated to 7 digits

3) Overview transactions list: https://invis.io/PEPL75H7ZV6#/336600645_07_OverviewTxList_
Transactions amounts could be truncated because on transaction details there is exact amount

4) Transaction details: https://invis.io/PEPL75H7ZV6#/336618171_08_TxView_
Transaction amount - up to 12 digits: http://joxi.net/BA0674eUJnLz3m


5) Overview assets
We can display amounts in two lines. There could be 16-20 digits per line, depending on the screen width. Michel has an example for Android here: https://invis.io/ARPG0XSTJMZ#/336820438_-ANDROID-_DEC18_-_Safe_Overview_READY_STATE_-_3

There is also a solution to display moving lines. You know like in iTunes when the track title is too long it moves from side to side.

**Comment by biocom** [comment]
The question is, say we choose to show max 7 digits, in what scenarios do we show _what_ amount of decimals and in what scenarios do we start abbreviating (and not trimming anymore). I think some consistency in terms of applying these rules is desired. E.g. we could say that in some scenarios:
- We trim up to 7 decimals.
- We abbreviate (100K or 100K~) ?
- We show the full amount.

In practice, individual token value might play a role too. See [Balance.io's ticket](https://github.com/balance-io/balance-wallet/issues/13) on this. Although that requires a fiat value coupling, which we currently don't have.

**Asset's overview:**
In the end context and available (device) space matters. For Android in [the overview screen](https://projects.invisionapp.com/share/ARPG0XSTJMZ#/screens/336820438_-ANDROID-_DEC18_-_Safe_Overview_READY_STATE_-_3) we can afford to show much more digits because of wrapping. Although, visually I tend to say that reading the balance column on the right, without having wrapped numbers, reads nicer. So perhaps we should avoid it by setting a max decimal setting (7).

**Transaction overview:**
[The transaction overview list](https://projects.invisionapp.com/share/PEPL75H7ZV6#/screens/336600645_07_OverviewTxList) has a bit less horizontal space available and I'd recommend against wrapping amounts in two lines.

**My conclusion on this:**
- On one hand I would argue that showing full digits where possible is preferable (Send Token, Transaction detail).
- In the Assets overview we could show the full balance with some conditions:
   1. As Sasha suggested, abbreviate large amounts. Need to decide what the cutoff point will be. Start at 1K, 100K or 1M? And as she mentioned, we need to decide what system to use here (make it depended on the device's locale?)

But an argument for also trimming balances in the [Safe overview](https://projects.invisionapp.com/share/ARPG0XSTJMZ#/screens/336820438) is that on tap of a balance, we could display the full amount in the Send Token screen.

   2. Maybe round/cutoff decimals: 0.1958320 (7 decimals) could potentially also just be 0.195832 (6 decimals).
   3. Show a max. of 7 decimals depending on available space. Trim it with the `~` sign: 0.000001~
   4. If the balance amount has 8 decimals or more (e.g. 0.00000001) we could either display it as: 
       - 0~ (potentially confusing as a zero balance)
       - 0.000000~ (max 7 decimals) (probably the more consistent approach)

Curious on your thoughts and I think in order for us to get consensus around this topic, we'd create a mockup displaying the different scenarios.

**Comment by DmitryBespalov** [comment]
have you considered displaying the amount on a separate line, i.e. for long digits, making the size of the row grow vertically?

**Comment by DmitryBespalov** [comment]
Maybe a better way to get ideas would be a short brainstorming session 15-20 minutes on the problem, ideas, and then picking a reasonably good one?

**Comment by biocom** [comment]
> have you considered displaying the amount on a separate line, i.e. for long digits, making the size of the row grow vertically?
Yes, for instance see [the overview screen](https://projects.invisionapp.com/share/ARPG0XSTJMZ#/screens/336820438_-ANDROID-_DEC18_-_Safe_Overview_READY_STATE_-_3).
But see my previous comment on this. I don't think it's applicable right now on every screen (because of constrains and the way we've setup certain screens). Also perhaps we should try to avoid it all together. 

> Maybe a better way to get ideas would be a short brainstorming session 15-20 minutes on the problem, ideas, and then picking a reasonably good one?
Yes definitely. Before doing so, I'd advise to collect some ideas here first so we can create several (simple) mockups, which can be discussing material for a brainstorming session.

**Comment by tschubotz** [comment]
We should check on how other crypto wallets handle this.

Status: Use 3 dots when number is too long, i.e. 123.32534... ETH
Metamask: Cut off after 4 digits. No indicator
imToken: Cut off after 4 digits. No indicator

Here's my thoughts.
- The higher the amounts, the less important digits after the comma get. So using 1M, 1k is oaky imo
- The told (~) seems weird to me. Do you have an example where this is used? I would rather go with three dots and the end instead.
- I don't think it's super important to display the 5th digits after the decimal separator right now. It's a fraction of a Euro cent. We could just but them off.

Here's my proposal:
- Cut off after the 5th decimal, no matter how many decimals there are: 0.12345ETH
- Remove trailing zeroes, i.e. display 0.10000ETH as 0.1ETH.
- Use the 5 decimals up until 999.99999ETH
- Use 1 decimal less from 1,000.0001 until 9,999.9999ETH (Use comma as thousands-separator)
- Use 1 decimal less from 10,000.001 until 99,999.999ETH 
- Use 1 decimal less from 100,000.01 until 999,999.99ETH 
- Use 1 decimal less from 1,000,000.1 until 9,999,999.9ETH 
- From 10,000,000ETH No Decimals until 99,999,999ETH
- Then Use 10.001M until 999.999M
- Then 1.001B until 999.999B
- Then 1.001T until 999.999T
- Then just > 1000T

What do you think?

Also in favor of a brainstorming session soon about this.

**Comment by biocom** [comment]
@tschubotz Good suggestions. Creating a mockup based on your proposal so we can discuss it in the brainstorm session. Will attach here once I have it.

**Comment by fmrsabino** [comment]
> We should check on how other crypto wallets handle this.
> ...
> Here's my proposal:
> 
> * Cut off after the 5th decimal, no matter how many decimals there are: 0.12345ETH
> ...
> What do you think?
> 
> Also in favor of a brainstorming session soon about this.

I like this proposal but do we take into account the actual value of the token?
Eg.: 0.0000001 ≈ 1000$

Would we display it like `0.00000… ETH` in the balance overview?
In this case one possible solution would also be `0.0…1 ETH`.

I also agree that when performing a transaction the full value should be shown.

**Comment by tschubotz** [comment]
I like the prototype.

Also to Sasha's comment
> I propose not to truncate anything if there is enough space.

How much value would that really add? I think people can not digest > 10 digits very well. As long as we link to Etherscan on the tx details where every number can be found.

> I like this proposal but do we take into account the actual value of the token?

I would just say, that's an edge case we should disregard right now. Is there a token that you have in mind which has a value similar to that?

> In this case one possible solution would also be 0.0…1 ETH.

That tells you really nothing since it could be 0.001ETH or 0.00000000000001ETH

> I also agree that when performing a transaction the full value should be shown.

You want to show all 18 decimals? Why?

**Comment by biocom** [comment]
> I also agree that when performing a transaction the full value should be shown.
> You want to show all 18 decimals? Why?

I think we need to distinguish on what screens we show what amount of decimals. I think it makes sense that when you:
- Send a token
- View a transaction detail

You'd be able to both see and input the full amount of decimals for the token. The Send Token screen doubles there in function because I can both see my full decimal balance (which we probably won't show in the assets overview, depending on what direction we go) and I can also input an amount using the full decimals.

**Comment by fmrsabino** [comment]
> That tells you really nothing since it could be 0.001ETH or 0.00000000000001ETH

So to distinguish between `0` and `0.000001` you'd show `0` and `0.00000…` respectively? That can work yeah 👍 

> You want to show all 18 decimals? Why?

I was giving it a second thought and if we come up with a good representation then it might work without full decimals.
I was thinking what'd be the best way to represent different scales on the same screen.

Having has a balance `1K+0.000001` and you want to transfer `0.000001`.
Do you just display `1K-0.000001`?

**Comment by biocom** [comment]
@fmrsabino Agreed. I think the token volatility coupled with visual representation of the amount can lead to (for the user) unexpected UX.

**Comment by tschubotz** [comment]
A long tap on a number could expose the entire number in large type ;)
(Inspired by [1password's large type feature](https://blog.1password.com/1password-x-1.10-large-type-watchtower-and-easy-two-factor-authentication/)

**Comment by fmrsabino** [comment]
> A long tap on a number could expose the entire number in large type ;)
> (Inspired by [1password's large type feature](https://blog.1password.com/1password-x-1.10-large-type-watchtower-and-easy-two-factor-authentication/)

Force/3D touch on iOS? 😆

**Comment by biocom** [comment]
For simplicity's sake and to have a starting point, should we go with the suggestions made by @tschubotz and as shown in https://invis.io/MHQ1TGQZ9U4 ?

The only thing I'd like to know is:
- For the SEND FUNDS and 'TRANSACTION DETAIL' (for a single tx.) would we say that there, we'd always show the full amount of digits?

**Comment by tschubotz** [comment]
> For the SEND FUNDS and 'TRANSACTION DETAIL' (for a single tx.) would we say that there, we'd always show the full amount of digits?

Good questions. What would you suggest? 

Do you have an example how it would look like in a "normal" case (i.e. not gigantically big numbers) and in the worst case (lot's of digits before and after decimal separator)?

**Comment by posthnikova** [comment]
I made an example based on Tobi's proposal. 

Overview assets: 
https://invis.io/PEPL75H7ZV6#/342779362_Overview_Truncated_2_

Overview Transactions:
https://invis.io/PEPL75H7ZV6#/342779364_OverviewTxList_Truncated_2_ 

I also tried to spell large numbers in full (million, billion): https://invis.io/PEPL75H7ZV6#/342779363_Overview_Truncated_, https://invis.io/PEPL75H7ZV6#/342779365_OverviewTxList_Truncated_

**Comment by tschubotz** [comment]
After discussing in the UX sync:

Let's go with the proposal. (with abbreviations for million, billion etc.)

Concerning the Send funds screen:
- Short amounts for Safe balance & network fee
- full amount for the amount to send

**Comment by biafra23** [comment]
@posthnikova @tschubotz 
How should we handle the "<" and ">"  regarding outgoing/negative amounts?
Is `< -0.00001` correct, or should it be `> -0.00001`. Technically the latter is correct.

**Comment by tschubotz** [comment]
There's the same discussion on slack currently happening. I prefer to keep it in one place. https://gnosisinc.slack.com/archives/C63LQTGNB/p1599482003203700
