### ISSUE TITLE
Feedback button & Rate app button in main menu

### ISSUE THREAD

**Issue by biocom** [gnosis/safe#63]
We could add a 'Give Feedback' button where the app version is displayed. The button would link to `safe.support@gnosis.pm` to allow the user to provide feedback.

Using an e-mail link is probably the quickest path to a first implementation. Perhaps for future iterations on this we could explore if there are better options for this.

There should also be the option to rate the app on the app store.

**Comment by tschubotz** [comment]
iOS has this already as part of #91 
Android so far only has designs for the app version, but not the 2 new buttons #52

**Comment by tschubotz** [comment]
Closing since Android does that as part of #52 and iOS as part of #91
