### ISSUE TITLE
Localization - Translate app

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#72]
# Problem statement
* Not all crypto holders speak English. ➡️ We should add more languages.

# Additional info
* Android has already a translated app version.
* Fallback language, in case a word is not available in the respective language, should always be English.
* All user interfaces should still work with all languages.
* We use Lokalise for managing translations. (https://lokalise.co/project/642211945bbb21460ac640.69731803/)
* Please sync with Android and the Chrome extension on localization keys, so we don't have duplicates.

**Comment by DmitryBespalov** [comment]
@tsch

**Comment by DmitryBespalov** [comment]
@tschubotz should we be able to edit the localizations and deploy them to already released apps without additional release? (I think it's a big deal, based on the previous experience, and that is something that would give us more flexibility and error correcting abilities).

**Comment by DmitryBespalov** [comment]
Which Locales do we want to support?

**Comment by tschubotz** [comment]
Translations have a big legal dependency -> Closing this for now
