### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#74]
# What is this feature about? (1 sentence)
This feature allows users to change their password.

# Why is it needed? What is the value? For whom do we build it?
In case the device password is compromised, the user needs a way to change it.

# High-level overview of the feature
- Users first need to confoirm their current password.
- New password needs to comply with requirements.
- New password needs to confirmed as well to prevent typos.

**Comment by sche** [comment]
@tschubotz we need to reflect in the design for iOS the blocking timer that we have for current password screen.
