### ISSUE TITLE
Status Keycard as 2FA device

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#77]
# What is this feature about? (1 sentence)
This feature will enable users to use other 2FA factors such as hardware wallets instead of exclusively the Chrome extension.

# Why is it needed? What is the value? For whom do we build it?
Currently, users are required to connect a Chrome extension as 2FA device. That means for all transactions, they would have to open their laptop computer. Which is not ideal out of several reasons:
- Users are restricted to Chome, i.e. not Safari, Brave etc possible.
- Users trust their hardware wallets more than Chrome extensions.
- Transactions "on the go" are harder.

# High-level overview of the feature
- Users are able to choose which 2FA options to connect.
- Without the Chrome extension, users would not be able anymore to use dapps with their Safe, hence WalletConnect integration (#151) is a prerequisite for this feature.
- We start with the [Status Keycard ](https://keycard.status.im) since it is able to sign arbitrary data. 
- Ledger and Trezor don't support EIP712 yet.

**Comment by tschubotz** [comment]
When recovering a Safe, do we know which 2FA option has been connected? @tschubotz

**Comment by rmeissner** [comment]
on a clean install this is very unlikely (unless we would have a database in our service)

but does it matter? :D

**Comment by tschubotz** [comment]
> on a clean install this is very unlikely (unless we would have a database in our service)
