### ISSUE TITLE
Multiple Safes

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#80]
# What is this feature about? (1 sentence)
This feature will allow iOS users to manage multiple Safes on one device.

# Why is it needed? What is the value? For whom do we build it?
Whenever account information is shared with a dapp, the dapp is able to see the stored assets and their balance. This is not always desirable.
For accounting reasons, some users would like to keep some assets in different Safes.

# High-level overview of the feature
- Users can create and recover multiple Safes.
- Users can switch between Safes.
- Whenever there is an incoming transaction, the correct Safe is used to sign a transaction.
- Users can remove Safes from the device.
- For privacy reasons, each Safe should use a different owner account (#143).

# Screens
https://docs.google.com/document/d/1JXo1D5Hd026cf83N9rWRVi5zG9ImrgCVf6zbEJkcECg/edit#

**Comment by sche** [comment]
For me, 40 indicates that the ticket is too unclear to estimate. We need to understand:
- How the one can switch safes
- Should the safes be synchronized with browser extension? Should we use our services for that (similar to transactions history service)?
- What will be the use cases when we need to switch safes automatically? (e.g. confirmation is required for a different from selected safe)

But as a "step 0" I would first measure what percentage of users use multiple safes on Android.
