### ISSUE TITLE
Address book 

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#81]
# What is this feature about? (1 sentence)
This feature allows users to store a mapping of nicknames to Ethereum addresses inside their Gnosis Safe app.

# Why is it needed? What is the value? For whom do we build it?
Ethereum address are rather cryptic and therefore hard to read and to double-check. It is also cumbersome to always paste / scan a frequently used address.
Therefore we would like to allow users to store addresses and give them a nickname.
This is a feature that users were asking for quite regularly.

# High-level overview of the feature
- Users can add, update, view and delete address book entries.
- An entry has an address and a name.
- Throughout the app, we display the name whenever the address would be displayed, i.e. on transaction details and during the transaction flow.

**Comment by sche** [comment]
@tschubotz @posthnikova Do we have a design for selecting an entry from the address book? (e.g. during funds transfer). We found designs for manage addresses but not for selecting an address.

**Comment by posthnikova** [comment]
@sche This is in Address book section https://zpl.io/bAB7nR6 (tap three dots, select Address book option, select address from list and the address is filled into recipient's field)

**Comment by sche** [comment]
@posthnikova I can't find in Zeplin "select address from list" part. Can you give a link to it?

**Comment by posthnikova** [comment]
@sche This is just the main address book list https://zpl.io/VQBv149

**Comment by sche** [comment]
@posthnikova Thanks. Should the "Back" button be "Cancel" in this case? Presentation style will be modal. And I want to clarify that having a possibility to add new contact in this case is ok. Or should we hide "+" button?

**Comment by posthnikova** [comment]
@sche I supposed the list to be reused here without changes but if you can change button to Cancel it's fine. You should be able to add new contact from here. In this case Save button takes you to the list and you can return to Send screen from there.

**Comment by sche** [comment]
@tschubotz should a safe name be as an address book entry?

**Comment by sche** [comment]
@tschubotz regarding my last question here, should we bound Safe Name to Address book entry?
How it could work:
When a new safe is created, the appropriate entry is created in Address Book. This can be a "special entry". When we try to delete it, the name would be "Delete Safe" or "Remove Safe" with a proper alert. The address would be "read-only", but the name could be modifiable. The Edit Safe name screen could stay the same.
This would allow the unifying logic of displaying addresses names in different parts of the app.

As for now, we display address names ONLY for entries from the address book. Safe Name influences only the main screen name.

**Comment by tschubotz** [comment]
@sche I wouldn't artificially bound it. At some point it's anyway ellipsized, right?
What do you suggest?
