### ISSUE TITLE
Revise token search UI

### ISSUE THREAD

**Issue by biocom** [gnosis/safe#84]
For Android we had these screens from some time ago to allow for inline searching in the token list:
https://zpl.io/aRqlmBe
https://zpl.io/bJKMpnE

Sasha gave some UI feedback and I did some revisions to the layout:
https://invis.io/TGQ0GLXDQW8 (interactive -> click on the search icon)

Changelog:
- Optimized arrow/search icon position and icon size
- The description text now is part of the grey content area. I feel this accentuates the individual token cards better by providing more contrast.
- On tap of the search icon, the search input field now visually looks more like it (similar to say the search feature for the Gmail app)
- Keyboard 'enter' action contains the search icon, just for reference.

Question: Do you think in lists like these (token list) we should keep the current layout or use cards? I feel cards are not appropriate here, but trying to get your thoughts on it.

**Comment by posthnikova** [comment]
I like the new layout. We also need a state when nothing's found. 

Don't you think the list should be alphabetical (currently it isn't)? Don't you think selected items should be at the top of the list? 

As for cards, in this case this is a list so it probably should look like Overview (https://invis.io/ARPG0XSTJMZ#/336820438_-ANDROID-_DEC18_-_Safe_Overview_READY_STATE_-_3)

**Comment by biocom** [comment]
@posthnikova Good points:

> We also need a state when nothing's found.
Yes.

> Don't you think the list should be alphabetical (currently it isn't)?
Yes, I think that's helpful in case someone doesn't want to use the search function.

> Don't you think selected items should be at the top of the list?
I'm not sure if that would be helpful. Especially in combination with sorting the list alphabetical. I could see it having a function where you can easily toggle 'off' the tokens you currently have enabled, right from the top. But perhaps we should stick to sorting the list alphabetical and let the user either use the inline search or just scroll the list?

**Comment by biocom** [comment]
@posthnikova Some updates:

- Search result:
https://invis.io/ARPG0XSTJMZ#/342047727_Manage_Tokens_-_Search_-1_Result-

- No results:
https://invis.io/ARPG0XSTJMZ#/342047726_Manage_Tokens_-_Search_-No_Results-

**Comment by rmeissner** [comment]
Hey, I was thinking about this issue yesterday and realised that there are some technical details that are worth to note (which I will add to the specs of #58):

- The list of tokens we retrieve from the server is paginated:
  -> It can happen that we can retrieve the first page but fail on the second page
  -> How do we make it possible that the user can still disable a selected token

- All the information (even the search) is performed via our service and we require a short time to load it

**Comment by biocom** [comment]
@rmeissner 
> It can happen that we can retrieve the first page but fail on the second page

Could it be an 'infinite' scroll type of pagination, where when loading (fetching the 2nd page of tokens) fails, we could show a button 'retrieve more tokens' or something, allowing for manual fetching in case it fails?

> How do we make it possible that the user can still disable a selected token

I think it that case we'd have to always show the enabled tokens first, besides the list being sorted from A-Z (as discussed @posthnikova)

> All the information (even the search) is performed via our service and we require a short time to load it

Meaning, we'd need a screen indicating that it's 'searching' ?

**Comment by rmeissner** [comment]
> we could show a button 'retrieve more tokens' or something
A button at the end of the list to load more and we can also retry automatically when the user tries to scroll again
> sorted from A-Z 
I would not sort on the client, rather let the backend decide how they are sorted and we take it as it is. I still think adding the enabled token before that list would make sense.
> Meaning, we'd need a screen indicating that it's 'searching' ?
I would use the default loading indicator for this (the one we already use while loading the list)

**Comment by biocom** [comment]
@rmeissner Sounds good. So the only thing you need in terms of UI is a button placement for the manual 'load more'.

**Comment by fmrsabino** [comment]
I don't think we need a "load more" button. We can retry with exponential
backoff if the user is at the end of the list. What do you think?

**Comment by biocom** [comment]
@fmrsabino Would that mean the user would have to repeatedly try to refresh themselves, without any visible feedback? Or would we show a spinner of some sorts indicating that it's loading?

**Comment by fmrsabino** [comment]
@biocom We can show a spinner when it's loading and an error message if there was a problem loading more entries. But no strong opinion here 👍

**Comment by biocom** [comment]
I think that approach works. Uploaded screens to Zeplin for production.:

https://zpl.io/aRqlmBe
https://zpl.io/bJKMpnE
https://zpl.io/beo3BBN
https://zpl.io/2jv3roQ

Summary:
- Show a spinner when more tokens are fetched and display an error message in case there was a problem loading.
- Enabled tokens are always the first listed in the overview, before the other disabled tokens.

Closing ticket.

**Comment by biocom** [comment]
Production screens moved to group: https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c7678b1d391d651e702a727
