### ISSUE TITLE
Incoming transactions & transaction history

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#9]
# What is this feature about? (1 sentence)
This feature will enable users to see incoming transactions as well as the history of transactions related to their Safe.

# Why is it needed? What is the value? For whom do we build it?
Currently, we only store past transactions locally on mobile devices. That means when a Safe is removed and recovered, that list is cleared. 
Furthermore, we only show "outgoing transactions", i.e. transfers and contract interactions initiated bt the Safe itself.
Users were expecting both features.

# High-level overview of the feature
- The backend is tracing and storing all Safe transactions.
- There will be an endpoint the clients can use to pull transaction data.

# Open questions / potential issues
* It's a bit tricky to figure this out since we work with internal transactions.
* eth.events is also researching on how to make internal txs accessible.
* Does it make sense to detect also outgoing txs in a similar fashion?

# Screens
- No specific new screens. Regular transaction list and overview screens from #71 should be used.

**Comment by DmitryBespalov** [comment]
@tschubotz I would expect the safe to list all of the transactions made with the safe - incoming and outgoing, so I could see the change in the balances, for example. 

I would even expect a transaction to show up in the safe if it wasn't made through the app (or if I wasn't involved in sending the transaction - let's say I just confirmed the transaction, as a part of the team safe transaction sending, for example).
