### ISSUE TITLE
Redesign iOS Menu

### ISSUE THREAD

**Issue by posthnikova** [gnosis/safe#91]
Redesigning iOS menu as part of integration proposal. Screens put for review here: https://invis.io/3HQ098MTCPU

**Comment by tschubotz** [comment]
Token search & manage tokens is included in this @posthnikova

**Comment by posthnikova** [comment]
Project put for review here: https://invis.io/3HQ098MTCPU 

Main changes: added Licences item in the list, corrected app version,

**Comment by DmitryBespalov** [comment]
👍

**Comment by posthnikova** [comment]
Replied to all comments here: https://invis.io/3HQ098MTCPU

**Comment by tschubotz** [comment]
Dima responded, the comment is resolved.
Can be closed as soon as the screens are on Zeplin @posthnikova :)

**Comment by tschubotz** [comment]
Thanks
