### ISSUE TITLE
Change password UI

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe#93]
# Android
Currently, there are no screens in Zeplin. Do we want to redesign something there?

# iOS
We have currently the following 4 screens by Minette. Do we want to use them or reiterate?
- https://zpl.io/VYGoNDn
- https://zpl.io/aRWGDAe
- https://zpl.io/a75Q6kv
- https://zpl.io/VOKAjjL

**Comment by posthnikova** [comment]
Integration designs are for review here: https://invis.io/46Q8VG0UX9J

**Comment by tschubotz** [comment]
commented on invision 💬

**Comment by posthnikova** [comment]
I replied to everyone here: https://invis.io/46Q8VG0UX9J

**Comment by biocom** [comment]
As for Android, I got the impression that we wanted to keep the current dialogs to change the password. Do we feel we want to change the Android UI at this point to match iOS or leave as is?

**Comment by tschubotz** [comment]
@biocom Let's align the design, i.e. if we believe separate screens (iOS) is better, then let's create designs for this for Android as well. 
We'll have to see when we implement this on Android, but I would like to get the designs ready.

**Comment by biocom** [comment]
@tschubotz Oke.

**Comment by biocom** [comment]
Got the designs for Android, based on iOS here:
https://invis.io/UDQF6KQB54V

Personally I think the current dialog is more efficient. Let me know your thoughts.

**Comment by tschubotz** [comment]
Aren't they basically the same? It's only dialog/popup vs. no dialog/popup.
What do you think @posthnikova ?

**Comment by biocom** [comment]
@tschubotz As per the latest Android proposal: Yes they are essentially the same in terms of content.

I guess it does feel difference staying in the context of the 'Settings' view but having a dialog in it. Subtle difference I suppose and I think either will work.

**Comment by tschubotz** [comment]
Can be closed as soon as Zeplin screens are up/

**Comment by biocom** [comment]
Added the Android screens to Zeplin - https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c6569fd5a5404463af4bf4d

**Comment by posthnikova** [comment]
Zeplin is here:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c6695f7eca40f4676c75c2a 

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c6695f7eca40f4676c75c2a

Reopening it because @sche has objections

**Comment by sche** [comment]
My comments:
1) Do we need "Enter current password" screen here? Currently, on iOS all restricted operations require "unlock" procedure. I would keep it for current operation as well.
2) For setting up a new password we could use already existing screens that we use during onboarding. It will save dev time.
3) IMO design should be consistent with setting a password during onboarding. So I would change it in onboarding as well or would make it here as two separate screens.

**Comment by tschubotz** [comment]
> 1. Do we need "Enter current password" screen here? Currently, on iOS all restricted operations require "unlock" procedure. I would keep it for current operation as well.

So you are proposing the following flow: (1) Enter new pw (2) confirm new (pw) and then (3) enter OLD pw to save? I think that is super confusing. No other app does it that way.

> 2. For setting up a new password we could use already existing screens that we use during onboarding. It will save dev time.

Not sure if the valley background and ther cards make too much sense here.

3\. IMO design should be consistent with setting a password during onboarding. So I would change it in onboarding as well or would make it here as two separate screens.

I don't think this has to be the same. Onboading is a special flow after all.

**Comment by sche** [comment]
> So you are proposing the following flow: (1) Enter new pw (2) confirm new (pw) and then (3) enter OLD pw to save? I think that is super confusing. No other app does it that way.
I propose to (1) always show unlock screen when you try to change the password. (2) enternew password. (3) confirm new password
> Not sure if the valley background and ther cards make too much sense here.
Background easy to change. UX will stay the same.

**Comment by biocom** [comment]
I agree with the 'change password' not having to be the same with the on-boarding flow.

**Comment by tschubotz** [comment]
> I propose to (1) always show unlock screen when you try to change the password. (2) enternew password. (3) confirm new password

Ah that's what you mean. Okay, then the flow is similar, just the UI is different.
I'm against just using the plain "unlock" screen because it doesn't tell you why it is brought up. In the Chrome extension we have it like that for example and it feels weird. I more custom UI saying "Enter current password" is better imo. That's what pretty much all other mobile apps out there do. 

I'll close the ticket again. Let me know if there are any objections @posthnikova @biocom

**Comment by tschubotz** [comment]
Need to reopen this after starting to write the spec:

(1) 
- Both clients
- During onboarding (zpl.io/bzAp7BG) we start with the pw requirements in grey and only start to validate once the user starts typing. Now in the change pw flow, we immediately start with the red stuff (https://zpl.io/bJ7NOeW).
-> I would show the requirements in grey first. It's less intimidating. Could you please add this screen to Zeplin?

(2)
- Android only
- @biocom could you please add a screen where the confirmed new password does not match. i.e. the Android equivalent to this iOS screen: zpl.io/2EBwy7x

**Comment by tschubotz** [comment]
(3) 
- Android only
- Android equivalent to iOS: https://zpl.io/25OggEW

**Comment by biocom** [comment]
@tschubotz Updated the inVision project for Android: https://invis.io/UDQF6KQB54V

**Comment by sche** [comment]
@tschubotz suggested design blocks one valid use case: If a user forgot the password because of frequent use of touch id and wants to set a new password.
IMO we should let a user change the password by face id / touch id verification.

**Comment by posthnikova** [comment]
Password requirements are grey now: https://invis.io/46Q8VG0UX9J#/343680969_04_New_Password

Updated on zeplin too:

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c6695f7eca40f4676c75c2a

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c6695f7eca40f4676c75c2a

**Comment by biocom** [comment]
Android production screens:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c6569fd5a5404463af4bf4d

[zpl://project?seid=5c6569fd5a5404463af4bf4d&pid=5af063c9b4dc859b6bdaf897](url)
